import Mathlib

/-- If an ideal is maximal, then the quotient ring is simple. -/
lemma isSimpleRing_quotient_of_isMaximal {R : Type*} [CommRing R] (I : Ideal R)
    (hI : I.IsMaximal) : IsSimpleRing (R ⧸ I) := by
  classical
  apply (isSimpleRing_iff_isField (R ⧸ I)).2
  exact (Ideal.Quotient.maximal_ideal_iff_isField_quotient (I := I)).1 hI

/-- The conic polynomial lies in the ideal generated by `X 1` and `X 0 ^ 2 + 1`. -/
lemma conic_mem_span_X1_X0sq_add_one :
    (.X 0 ^ 2 + .X 1 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ) ∈
      Ideal.span {(.X 1 : MvPolynomial (Fin 2) ℝ),
        (.X 0 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)} := by
  classical
  let J : Ideal (MvPolynomial (Fin 2) ℝ) :=
    Ideal.span {(.X 1 : MvPolynomial (Fin 2) ℝ),
      (.X 0 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)}
  have hX1 : (.X 1 : MvPolynomial (Fin 2) ℝ) ∈ J := by
    have : (.X 1 : MvPolynomial (Fin 2) ℝ) ∈
        ({(.X 1 : MvPolynomial (Fin 2) ℝ),
          (.X 0 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)} :
          Set (MvPolynomial (Fin 2) ℝ)) := by
      simp
    exact (Ideal.subset_span this)
  have hX0sq1 : (.X 0 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ) ∈ J := by
    have : (.X 0 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ) ∈
        ({(.X 1 : MvPolynomial (Fin 2) ℝ),
          (.X 0 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)} :
          Set (MvPolynomial (Fin 2) ℝ)) := by
      simp
    exact (Ideal.subset_span this)
  have hX1sq : (.X 1 ^ 2 : MvPolynomial (Fin 2) ℝ) ∈ J := by
    simpa [pow_two] using (Ideal.mul_mem_left J (.X 1) hX1)
  have hsum :
      (.X 0 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ) + .X 1 ^ 2 ∈ J := by
    exact Ideal.add_mem J hX0sq1 hX1sq
  simpa [J, add_assoc, add_left_comm, add_comm] using hsum

/-- The principal ideal of the conic polynomial is contained in `(X1, X0^2 + 1)`. -/
lemma conic_span_le_span_X1_X0sq_add_one :
    Ideal.span {(.X 0 ^ 2 + .X 1 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)} ≤
      Ideal.span {(.X 1 : MvPolynomial (Fin 2) ℝ),
        (.X 0 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)} := by
  refine (Ideal.span_le).2 ?_
  intro x hx
  rcases Set.mem_singleton_iff.1 hx with rfl
  exact conic_mem_span_X1_X0sq_add_one

/-- The principal ideal `(X0^2 + X1^2 + 1)` is proper. -/
lemma conic_span_ne_top :
    (Ideal.span {(.X 0 ^ 2 + .X 1 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)} :
      Ideal (MvPolynomial (Fin 2) ℝ)) ≠ ⊤ := by
  classical
  let g : Fin 2 → ℂ := fun i => if i = 0 then Complex.I else 0
  let φ : MvPolynomial (Fin 2) ℝ →+* ℂ :=
    MvPolynomial.eval₂Hom (algebraMap ℝ ℂ) g
  have hker :
      Ideal.span {(.X 0 ^ 2 + .X 1 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)} ≤ RingHom.ker φ := by
    refine (Ideal.span_le).2 ?_
    intro x hx
    rcases Set.mem_singleton_iff.1 hx with rfl
    simp [RingHom.mem_ker, φ, g, pow_two]
  intro htop
  have h1 : (1 : MvPolynomial (Fin 2) ℝ) ∈
      Ideal.span {(.X 0 ^ 2 + .X 1 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)} := by
    have htop' :
        Ideal.span {(.X 0 ^ 2 + .X 1 ^ 2 + 1 : MvPolynomial (Fin 2) ℝ)} = ⊤ := by
      simpa using htop
    simp [htop']
  have h1ker : (1 : MvPolynomial (Fin 2) ℝ) ∈ RingHom.ker φ := hker h1
  exact (RingHom.one_notMem_ker (f := φ)) h1ker

/-- The ideal `(X1, X0^2 + 1)` in `ℝ[X0,X1]` is proper. -/
lemma span_X1_X0sq_add_one_ne_top :
    (Ideal.span {(.X 1 : MvPolynomial (Fin 2) ℝ),
      (.X 0 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)} : Ideal (MvPolynomial (Fin 2) ℝ)) ≠ ⊤ := by
  classical
  let g : Fin 2 → ℂ := fun i => if i = 0 then Complex.I else 0
  let φ : MvPolynomial (Fin 2) ℝ →+* ℂ :=
    MvPolynomial.eval₂Hom (algebraMap ℝ ℂ) g
  have hker :
      Ideal.span {(.X 1 : MvPolynomial (Fin 2) ℝ),
        (.X 0 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)} ≤ RingHom.ker φ := by
    refine (Ideal.span_le).2 ?_
    intro x hx
    rcases Set.mem_insert_iff.1 hx with hx | hx
    · subst hx
      simp [RingHom.mem_ker, φ, g]
    · rcases Set.mem_singleton_iff.1 hx with hx
      subst hx
      simp [RingHom.mem_ker, φ, g, pow_two]
  intro htop
  have h1 : (1 : MvPolynomial (Fin 2) ℝ) ∈
      Ideal.span {(.X 1 : MvPolynomial (Fin 2) ℝ),
        (.X 0 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)} := by
    have htop' :
        Ideal.span {(.X 1 : MvPolynomial (Fin 2) ℝ),
          (.X 0 ^ 2 + 1 : MvPolynomial (Fin 2) ℝ)} = ⊤ := by
      simpa using htop
    simp [htop']
  have h1ker : (1 : MvPolynomial (Fin 2) ℝ) ∈ RingHom.ker φ := hker h1
  exact (RingHom.one_notMem_ker (f := φ)) h1ker

/-- The variable `X 1` is not in the principal ideal generated by the conic polynomial. -/
lemma X1_not_mem_conic_span :
    (.X 1 : MvPolynomial (Fin 2) ℝ) ∉
      Ideal.span {(.X 0 ^ 2 + .X 1 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)} := by
  classical
  let g : Fin 2 → ℂ := fun i => if i = 1 then Complex.I else 0
  let ψ : MvPolynomial (Fin 2) ℝ →+* ℂ :=
    MvPolynomial.eval₂Hom (algebraMap ℝ ℂ) g
  have hker :
      Ideal.span {(.X 0 ^ 2 + .X 1 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)} ≤ RingHom.ker ψ := by
    refine (Ideal.span_le).2 ?_
    intro x hx
    rcases Set.mem_singleton_iff.1 hx with rfl
    simp [RingHom.mem_ker, ψ, g, pow_two]
  intro hmem
  have hmemker : (.X 1 : MvPolynomial (Fin 2) ℝ) ∈ RingHom.ker ψ := hker hmem
  have hX1 : (ψ (.X 1 : MvPolynomial (Fin 2) ℝ)) = 0 :=
    (RingHom.mem_ker (f := ψ)).1 hmemker
  have hI : (Complex.I : ℂ) = 0 := by
    simp [ψ, g] at hX1
  exact (Complex.I_ne_zero hI)

/-- The principal ideal `(X0^2 + X1^2 + 1)` is not maximal. -/
lemma not_isMaximal_conic_span :
    ¬ (Ideal.span {(.X 0 ^ 2 + .X 1 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)}).IsMaximal := by
  classical
  let I : Ideal (MvPolynomial (Fin 2) ℝ) :=
    Ideal.span {(.X 0 ^ 2 + .X 1 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)}
  let J : Ideal (MvPolynomial (Fin 2) ℝ) :=
    Ideal.span {(.X 1 : MvPolynomial (Fin 2) ℝ),
      (.X 0 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)}
  have hIJ : I ≤ J := by
    simpa [I, J] using conic_span_le_span_X1_X0sq_add_one
  have hJneTop : J ≠ ⊤ := by
    simpa [J] using span_X1_X0sq_add_one_ne_top
  have hX1memJ : (.X 1 : MvPolynomial (Fin 2) ℝ) ∈ J := by
    have : (.X 1 : MvPolynomial (Fin 2) ℝ) ∈
        ({(.X 1 : MvPolynomial (Fin 2) ℝ),
          (.X 0 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)} :
          Set (MvPolynomial (Fin 2) ℝ)) := by
      simp
    exact Ideal.subset_span this
  have hX1notmemI : (.X 1 : MvPolynomial (Fin 2) ℝ) ∉ I := by
    simpa [I] using X1_not_mem_conic_span
  have hJneI : J ≠ I := by
    intro hJI
    have : (.X 1 : MvPolynomial (Fin 2) ℝ) ∈ I := by simpa [hJI] using hX1memJ
    exact hX1notmemI this
  intro hmax
  have hIJ' : I = J := Ideal.IsMaximal.eq_of_le hmax hJneTop hIJ
  exact hJneI hIJ'.symm

/-- The conic quotient ring is not simple. -/
lemma not_isSimpleRing_conic_quotient :
    ¬ IsSimpleRing ((MvPolynomial (Fin 2) ℝ) ⧸
      Ideal.span {(.X 0 ^ 2 + .X 1 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)}) := by
  classical
  let I : Ideal (MvPolynomial (Fin 2) ℝ) :=
    Ideal.span {(.X 0 ^ 2 + .X 1 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)}
  let A := (MvPolynomial (Fin 2) ℝ) ⧸ I
  intro hsimple
  have hfield :
      IsField A :=
    (isSimpleRing_iff_isField A).1 (by simpa [A, I] using hsimple)
  have hmax : I.IsMaximal :=
    (Ideal.Quotient.maximal_ideal_iff_isField_quotient (I := I)).2 hfield
  have hmax' :
      (Ideal.span {(.X 0 ^ 2 + .X 1 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)}).IsMaximal := by
    simpa [I] using hmax
  exact not_isMaximal_conic_span hmax'

/-- Transport `IsPrincipalIdealRing` across a ring equivalence. -/
lemma isPrincipalIdealRing_of_ringEquiv {R S : Type*} [Semiring R] [Semiring S]
    (hR : IsPrincipalIdealRing R) (e : R ≃+* S) : IsPrincipalIdealRing S := by
  classical
  letI : IsPrincipalIdealRing R := hR
  exact IsPrincipalIdealRing.of_surjective (f := e.toRingHom) e.surjective

/-- Transport `IsField` across a ring equivalence. -/
lemma isField_of_ringEquiv {R S : Type*} [CommRing R] [CommRing S]
    (e : R ≃+* S) (h : IsField S) : IsField R := by
  classical
  refine { exists_pair_ne := ?_, mul_comm := ?_, mul_inv_cancel := ?_ }
  · rcases h.exists_pair_ne with ⟨x, y, hxy⟩
    refine ⟨e.symm x, e.symm y, ?_⟩
    intro h'
    apply hxy
    simpa using congrArg e h'
  · intro x y
    apply e.injective
    simpa [map_mul] using h.mul_comm (e x) (e y)
  · intro a ha
    have ha' : e a ≠ 0 := by
      intro h0
      apply ha
      have h0' : e a = e 0 := by simpa using h0
      exact e.injective h0'
    rcases h.mul_inv_cancel ha' with ⟨b, hb⟩
    refine ⟨e.symm b, ?_⟩
    apply e.injective
    simpa [map_mul] using hb

/-- There is no ring equivalence between the conic quotient and `ℂ`. -/
lemma no_conic_quotient_ringEquiv_Complex :
    ¬ Nonempty (ℂ ≃+*
      ((MvPolynomial (Fin 2) ℝ) ⧸
        Ideal.span {(.X 0 ^ 2 + .X 1 ^ 2 + .C 1 : (MvPolynomial (Fin 2) ℝ))})) := by
  classical
  let I : Ideal (MvPolynomial (Fin 2) ℝ) :=
    Ideal.span {(.X 0 ^ 2 + .X 1 ^ 2 + .C 1 : MvPolynomial (Fin 2) ℝ)}
  let A := (MvPolynomial (Fin 2) ℝ) ⧸ I
  intro h
  rcases h with ⟨e⟩
  have hC : IsField ℂ := by
    simpa using (Field.toIsField ℂ)
  have hfield :
      IsField A := by
    exact isField_of_ringEquiv
      (R := A) (S := ℂ) e.symm hC
  have hsimple :
      IsSimpleRing A :=
    (isSimpleRing_iff_isField A).2 hfield
  have hsimple' :
      IsSimpleRing ((MvPolynomial (Fin 2) ℝ) ⧸
        Ideal.span {(.X 0 ^ 2 + .X 1 ^ 2 + .C 1 : (MvPolynomial (Fin 2) ℝ))}) := by
    simpa [A, I] using hsimple
  exact not_isSimpleRing_conic_quotient hsimple'

/-- The conic quotient equivalence goal is equivalent to `False`. -/
lemma conic_quotient_ringEquiv_Complex_nonempty_iff_false :
    Nonempty (ℂ ≃+*
      ((MvPolynomial (Fin 2) ℝ) ⧸
        Ideal.span {(.X 0 ^ 2 + .X 1 ^ 2 + .C 1 : (MvPolynomial (Fin 2) ℝ))})) ↔ False := by
  constructor
  · exact no_conic_quotient_ringEquiv_Complex
  · intro h
    exact False.elim h

/-- Any ring equivalence witness to the conic quotient yields a contradiction. -/
lemma conic_quotient_ringEquiv_Complex_nonempty_false :
    Nonempty (ℂ ≃+*
      ((MvPolynomial (Fin 2) ℝ) ⧸
        Ideal.span {(.X 0 ^ 2 + .X 1 ^ 2 + .C 1 : (MvPolynomial (Fin 2) ℝ))})) → False := by
  exact no_conic_quotient_ringEquiv_Complex
