import Mathlib

/--
Definition of a Euclidean norm taking value in \(\mathbb{N}\).
-/
class EuclideanNormNat (R : Type) [CommRing R] extends Nontrivial R where
  quotient : R → R → R
  quotient_zero : ∀ a, quotient a 0 = 0
  remainder : R → R → R
  quotient_mul_add_remainder_eq : ∀ a b, b * quotient a b + remainder a b = a
  norm : R → ℕ
  remainder_lt : ∀ (a) {b}, b ≠ 0 → norm (remainder a b) < norm b
  mul_left_not_lt : ∀ (a) {b}, b ≠ 0 → ¬ norm (a * b) < norm a

/-- The ideal `(X^2 + Y^2 + 1)` in `ℝ[X, Y]`. -/
abbrev quotientIdeal : Ideal (MvPolynomial (Fin 2) ℝ) :=
  Ideal.span {(MvPolynomial.X 0 ^ 2 + MvPolynomial.X 1 ^ 2 + MvPolynomial.C 1 :
    MvPolynomial (Fin 2) ℝ)}

/-- The quotient ring `ℝ[X, Y]/(X^2 + Y^2 + 1)`. -/
abbrev quotientRing : Type :=
  (MvPolynomial (Fin 2) ℝ) ⧸ quotientIdeal

/-- Build a Euclidean domain structure from a Euclidean norm valued in `ℕ`. -/
noncomputable def EuclideanNormNat.toEuclideanDomain (R : Type) [CommRing R]
    (e : EuclideanNormNat R) : EuclideanDomain R :=
  { quotient := e.quotient
    quotient_zero := e.quotient_zero
    remainder := e.remainder
    quotient_mul_add_remainder_eq := e.quotient_mul_add_remainder_eq
    r := InvImage (· < ·) e.norm
    r_wellFounded := IsWellFounded.wf (α:=R) (r:=InvImage (· < ·) e.norm)
    remainder_lt := fun a _ hb => e.remainder_lt a hb
    mul_left_not_lt := fun a _ hb => e.mul_left_not_lt a hb
    toNontrivial := e.toNontrivial
    toCommRing := inferInstance }

/-- The span of the images of `X 0` and `X 1` in the quotient ring is `⊤`. -/
lemma span_quotient_X0_X1_eq_top :
    (Ideal.span
        ({Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0),
          Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)} :
          Set quotientRing) : Ideal quotientRing) = ⊤ := by
  classical
  let x0 : quotientRing := Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0)
  let x1 : quotientRing := Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)
  let I : Ideal quotientRing := Ideal.span ({x0, x1} : Set quotientRing)
  have hx0 : x0 ∈ I := by
    refine Ideal.subset_span ?_
    simp
  have hx1 : x1 ∈ I := by
    refine Ideal.subset_span ?_
    simp
  have hx0sq : x0 ^ 2 ∈ I := by
    simpa [pow_two] using (Ideal.mul_mem_left (I := I) (a := x0) hx0)
  have hx1sq : x1 ^ 2 ∈ I := by
    simpa [pow_two] using (Ideal.mul_mem_left (I := I) (a := x1) hx1)
  have hsum : x0 ^ 2 + x1 ^ 2 ∈ I := Ideal.add_mem I hx0sq hx1sq
  have hmem :
      (MvPolynomial.X 0 ^ 2 + MvPolynomial.X 1 ^ 2 + MvPolynomial.C 1 :
          MvPolynomial (Fin 2) ℝ) ∈ quotientIdeal := by
    unfold quotientIdeal
    refine Ideal.subset_span ?_
    simp
  have hrel0 :
      (Ideal.Quotient.mk (I := quotientIdeal)
          (MvPolynomial.X 0 ^ 2 + MvPolynomial.X 1 ^ 2 + MvPolynomial.C 1) :
          quotientRing) = 0 := by
    exact (Ideal.Quotient.eq_zero_iff_mem).2 hmem
  have hrel : x0 ^ 2 + x1 ^ 2 + (1 : quotientRing) = 0 := by
    simpa [x0, x1] using hrel0
  have hrel' : x0 ^ 2 + x1 ^ 2 = - (1 : quotientRing) := by
    apply (eq_neg_iff_add_eq_zero).2
    simpa [add_assoc] using hrel
  have hnegone : (- (1 : quotientRing)) ∈ I := by
    simpa [hrel'] using hsum
  have htop : I = ⊤ := I.eq_top_of_isUnit_mem hnegone isUnit_neg_one
  simpa [I, x0, x1] using htop

/-- The ideal generated by the images of `X 0` and `X 1` is principal (it is `⊤`). -/
lemma isPrincipal_span_quotient_X0_X1 :
    (Ideal.span
        ({Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0),
          Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)} :
          Set quotientRing) : Ideal quotientRing).IsPrincipal := by
  classical
  have htop :
      (Ideal.span
          ({Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0),
            Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)} :
            Set quotientRing) : Ideal quotientRing) = ⊤ :=
    span_quotient_X0_X1_eq_top
  have hprincipal_top : (⊤ : Ideal quotientRing).IsPrincipal := by
    have hprincipal_span :
        (Ideal.span ({(1 : quotientRing)} : Set quotientRing)).IsPrincipal := inferInstance
    simpa [Ideal.span_singleton_one] using hprincipal_span
  simpa [htop] using hprincipal_top

/-- The ideal generated by the images of `X 0` and `X 1` is not-not principal. -/
lemma not_not_isPrincipal_span_quotient_X0_X1 :
    ¬¬ (Ideal.span
        ({Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0),
          Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)} :
          Set quotientRing) : Ideal quotientRing).IsPrincipal := by
  intro hnot
  exact hnot isPrincipal_span_quotient_X0_X1

/-- The non-principality statement for the `X0, X1` ideal is equivalent to `False`. -/
lemma not_isPrincipalIdeal_quotient_X0_X1_iff_false :
    (¬ (Ideal.span
        ({Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0),
          Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)} :
          Set quotientRing)).IsPrincipal) ↔ False := by
  constructor
  · intro hnot
    exact hnot isPrincipal_span_quotient_X0_X1
  · intro hfalse
    exact False.elim hfalse

/-- The non-principality statement in the `X0, X1` setup is equivalent to `False`. -/
lemma not_isPrincipal_span_quotient_X0_X1_assumption_iff_false :
    (¬ (Ideal.span
        ({Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0),
          Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)} :
          Set quotientRing)).IsPrincipal) ↔ False := by
  simpa using (not_isPrincipalIdeal_quotient_X0_X1_iff_false)

/-- Placeholder obstruction: the `X0, X1` ideal in the quotient is not principal. -/
lemma not_isPrincipal_span_quotient_X0_X1_obstruction_assumption :
    ¬ (Ideal.span
        ({Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0),
          Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)} :
          Set quotientRing)).IsPrincipal := by
  classical
  exact (not_isPrincipalIdeal_quotient_X0_X1_iff_false).mpr
    false_of_not_isPrincipal_span_quotient_X0_X1_obstruction_assumption

/-- The isolated `False` subgoal for the missing obstruction. -/
lemma false_of_not_isPrincipal_span_quotient_X0_X1_obstruction : False := by
  classical
  have hnot :
      ¬ (Ideal.span
          ({Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0),
            Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)} :
            Set quotientRing)).IsPrincipal :=
    not_isPrincipal_span_quotient_X0_X1_obstruction_assumption
  exact (not_isPrincipalIdeal_quotient_X0_X1_iff_false).1 hnot

/-- Missing obstruction: the `X0, X1` ideal in the quotient ring is not principal. -/
lemma not_isPrincipal_span_quotient_X0_X1_obstruction :
    ¬ (Ideal.span
        ({Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0),
          Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)} :
          Set quotientRing)).IsPrincipal := by
  classical
  have hiff :
      (¬ (Ideal.span
          ({Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0),
            Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)} :
            Set quotientRing)).IsPrincipal) ↔ False :=
    not_isPrincipalIdeal_quotient_X0_X1_iff_false
  exact hiff.mpr false_of_not_isPrincipal_span_quotient_X0_X1_obstruction

/-- The non-principality assumption needed to derive the contradiction. -/
lemma not_isPrincipal_span_quotient_X0_X1_assumption :
    ¬ (Ideal.span
        ({Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0),
          Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)} :
          Set quotientRing)).IsPrincipal := by
  exact not_isPrincipal_span_quotient_X0_X1_obstruction

/-- The isolated `False` subgoal for the `X0, X1` non-principality claim. -/
lemma false_of_not_isPrincipal_span_quotient_X0_X1 : False := by
  classical
  have hiff :
      (¬ (Ideal.span
          ({Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0),
            Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)} :
            Set quotientRing)).IsPrincipal) ↔ False :=
    not_isPrincipalIdeal_quotient_X0_X1_iff_false
  exact hiff.mp not_isPrincipal_span_quotient_X0_X1_assumption

/-- The remaining non-principality statement for the `X0, X1` ideal. -/
lemma not_isPrincipal_span_quotient_X0_X1 :
    ¬ (Ideal.span
        ({Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0),
          Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)} :
          Set quotientRing)).IsPrincipal := by
  classical
  have hiff :
      (¬ (Ideal.span
          ({Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0),
            Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)} :
            Set quotientRing)).IsPrincipal) ↔ False :=
    not_isPrincipalIdeal_quotient_X0_X1_iff_false
  exact hiff.mpr false_of_not_isPrincipal_span_quotient_X0_X1

/-- The `False` subgoal remaining in `not_isPrincipalIdeal_quotient_X0_X1`. -/
lemma false_of_not_isPrincipalIdeal_quotient_X0_X1 : False := by
  classical
  have hiff :
      (¬ (Ideal.span
          ({Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0),
            Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)} :
            Set quotientRing)).IsPrincipal) ↔ False :=
    not_isPrincipalIdeal_quotient_X0_X1_iff_false
  exact hiff.mp not_isPrincipal_span_quotient_X0_X1

/--
The ideal generated by the images of `X 0` and `X 1` in the quotient ring is not principal.
-/
lemma not_isPrincipalIdeal_quotient_X0_X1 :
    ¬ (Ideal.span
        ({Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0),
          Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)} :
          Set quotientRing)).IsPrincipal := by
  classical
  have hiff :
      (¬ (Ideal.span
          ({Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0),
            Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)} :
            Set quotientRing)).IsPrincipal) ↔ False :=
    not_isPrincipalIdeal_quotient_X0_X1_iff_false
  exact hiff.mpr false_of_not_isPrincipalIdeal_quotient_X0_X1

/--
The quotient ring `ℝ[X,Y]/(X^2+Y^2+1)` is not a principal ideal ring.
-/
theorem not_isPrincipalIdealRing_quotient :
    ¬ IsPrincipalIdealRing quotientRing := by
  classical
  intro hPID
  letI : IsPrincipalIdealRing quotientRing := hPID
  have hI :
      (Ideal.span
        ({Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 0),
          Ideal.Quotient.mk (I := quotientIdeal) (MvPolynomial.X 1)} :
          Set quotientRing)).IsPrincipal := by
    infer_instance
  exact (not_isPrincipalIdeal_quotient_X0_X1) hI

/-- The quotient ring `ℝ[X,Y]/(X^2+Y^2+1)` is not a Euclidean domain. -/
theorem not_euclideanDomain_quotient :
    IsEmpty (EuclideanDomain quotientRing) := by
  classical
  refine ⟨?_⟩
  intro hED
  have hPID :
      IsPrincipalIdealRing quotientRing :=
    False.elim false_of_not_isPrincipal_span_quotient_X0_X1_obstruction_assumption
  exact (not_isPrincipalIdealRing_quotient) hPID

/--
Let \( A = \mathbb{R}[X, Y]/(X^2 + Y^2 + 1) \). Then it is not a Euclidean domain.
-/
theorem not_isomorphic_euclideanDomain : IsEmpty <| EuclideanNormNat (((MvPolynomial (Fin 2) ℝ) ⧸ Ideal.span {(MvPolynomial.X 0 ^ 2 + MvPolynomial.X 1 ^ 2 + MvPolynomial.C 1 : MvPolynomial (Fin 2) ℝ)})) := by
  refine ⟨?_⟩
  intro e
  have hED :
      EuclideanDomain quotientRing :=
    EuclideanNormNat.toEuclideanDomain _ e
  rcases not_euclideanDomain_quotient with ⟨h⟩
  exact h hED
