import Mathlib
import Mathlib.LinearAlgebra.Dimension.Finrank

open Polynomial

/-- If `α` is a root of an irreducible polynomial, then `minpoly F α` is associated to it. -/
lemma intermediateField_rank_eq_ringChar_associated_minpoly
    (F : Type) [Field F] (K : Type) [Field K] [Algebra F K]
    (f : Polynomial F) (hf : Irreducible f) (α : K) (hα : f.aeval α = 0) :
    Associated (minpoly F α) f := by
  have hAlg : IsAlgebraic F α := ⟨f, hf.ne_zero, hα⟩
  have hInt : IsIntegral F α := IsAlgebraic.isIntegral hAlg
  have hmin_irred : Irreducible (minpoly F α) := minpoly.irreducible hInt
  have hmin_dvd : minpoly F α ∣ f := minpoly.dvd F α hα
  exact Irreducible.associated_of_dvd hmin_irred hf hmin_dvd

/-- Transfer a root of `f` at `α + 1` to a root of `minpoly F α`. -/
lemma intermediateField_rank_eq_ringChar_aeval_minpoly_alpha_add_one
    (F : Type) [Field F] (K : Type) [Field K] [Algebra F K]
    (f : Polynomial F) (α : K) (hassoc : Associated (minpoly F α) f)
    (hα1 : f.aeval (α + 1) = 0) :
    (minpoly F α).aeval (α + 1) = 0 := by
  obtain ⟨u, hu⟩ := hassoc
  have hzero :
      aeval (α + 1) (minpoly F α * (u : Polynomial F)) = 0 := by
    simpa [hu] using hα1
  have hzero' :
      aeval (α + 1) (minpoly F α) * aeval (α + 1) (u : Polynomial F) = 0 := by
    simpa [map_mul] using hzero
  have hunit : IsUnit (aeval (α + 1) (u : Polynomial F)) := by
    exact
      IsUnit.map
        (f := (Polynomial.aeval (R := F) (A := K) (α + 1)).toRingHom) u.isUnit
  exact (mul_eq_zero.mp hzero').resolve_right hunit.ne_zero

/-- In a normal extension, a root of `minpoly F α` yields a Galois automorphism sending `α` to it. -/
lemma intermediateField_rank_eq_ringChar_exists_sigma
    (F : Type) [Field F] (K : Type) [Field K] [Algebra F K] [Normal F K]
    (f : Polynomial F) (hf : Irreducible f) (α : K) (hα : f.aeval α = 0)
    (hmin : (minpoly F α).aeval (α + 1) = 0) :
    ∃ σ : Gal(K/F), σ α = α + 1 := by
  have hAlg : IsAlgebraic F α := ⟨f, hf.ne_zero, hα⟩
  simpa using (minpoly.exists_algEquiv_of_root' (K := F) (L := K) (x := α + 1) (y := α)
    hAlg hmin)

/-- Casting `n + 1` into a semiring agrees with casting `n` and adding `1`. -/
@[simp] lemma nat_cast_succ_eq (K : Type) [Semiring K] (n : ℕ) :
    (↑(n + 1) : K) = (↑n : K) + 1 := by
  simp [Nat.cast_add, Nat.cast_one]

/-- Adding the cast of `n` and `1` agrees with adding the cast of `n + 1`. -/
lemma add_natCast_succ (K : Type) [Semiring K] (α : K) (n : ℕ) :
    α + ((↑n : K) + 1) = α + (↑(n + 1) : K) := by
  simp [nat_cast_succ_eq]

/-- Powers of an automorphism sending `α` to `α + 1` translate `α` by `n`. -/
lemma intermediateField_rank_eq_ringChar_sigma_pow_apply
    (F : Type) [Field F] (K : Type) [Field K] [Algebra F K]
    (α : K) (σ : Gal(K/F)) (hσ : σ α = α + 1) :
    ∀ n : ℕ, (σ ^ n) α = α + n := by
  intro n
  induction n with
  | zero =>
      simp
  | succ n ih =>
      calc
        (σ ^ (n + 1)) α = (σ ^ n) (σ α) := by
          simp [pow_succ, AlgEquiv.mul_apply]
        _ = (σ ^ n) (α + 1) := by simp [hσ]
        _ = (σ ^ n) α + 1 := by
          simp
        _ = α + (↑n + 1) := by
          simp [ih, add_assoc]
        _ = α + (↑(n + 1) : K) := by
          exact add_natCast_succ (K := K) (α := α) n

/-- The order of an automorphism shifting `α` by `1` is divisible by the characteristic. -/
lemma intermediateField_rank_eq_ringChar_ringChar_dvd_orderOf
    (F : Type) [Field F] (K : Type) [Field K] [Algebra F K]
    (α : K) (σ : Gal(K/F)) (hσ : σ α = α + 1) :
    ringChar F ∣ orderOf σ := by
  classical
  have hpow := intermediateField_rank_eq_ringChar_sigma_pow_apply (F := F) (K := K) α σ hσ
  have hσpow : (σ ^ orderOf σ) α = α + orderOf σ := hpow _
  have hfix : (σ ^ orderOf σ) α = α := by
    simp
  have hαeq : α + (orderOf σ : K) = α := hσpow.symm.trans hfix
  have hzero : (orderOf σ : K) = 0 := by
    have h' : α + (orderOf σ : K) = α + 0 := by simpa using hαeq
    exact add_left_cancel h'
  have hdivK : ringChar K ∣ orderOf σ := ringChar.dvd (R := K) hzero
  simpa [Algebra.ringChar_eq F K] using hdivK

/-- The fixed field of a cyclic subgroup generated by `τ` has degree `orderOf τ`. -/
lemma intermediateField_rank_eq_ringChar_fixedField_rank
    (F : Type) [Field F] (K : Type) [Field K] [Algebra F K] [FiniteDimensional F K]
    (τ : Gal(K/F)) (hτ : orderOf τ = ringChar F) :
    Module.rank (IntermediateField.fixedField (Subgroup.zpowers τ)) K = ringChar F := by
  classical
  have hcard :
      Module.finrank (IntermediateField.fixedField (Subgroup.zpowers τ)) K =
        Fintype.card (Subgroup.zpowers τ) := by
    simpa using
      (IntermediateField.finrank_fixedField_eq_card
        (F := F) (E := K) (H := Subgroup.zpowers τ))
  have hcard' : Fintype.card (Subgroup.zpowers τ) = orderOf τ := by
    simpa using (Fintype.card_zpowers (x := τ))
  have hfinrankNat :
      Module.finrank (IntermediateField.fixedField (Subgroup.zpowers τ)) K = orderOf τ := by
    simpa [hcard'] using hcard
  have hrank :
      Module.rank (IntermediateField.fixedField (Subgroup.zpowers τ)) K =
        (Module.finrank (IntermediateField.fixedField (Subgroup.zpowers τ)) K : Cardinal) := by
    simp
  have hrank' :
      Module.rank (IntermediateField.fixedField (Subgroup.zpowers τ)) K =
        (orderOf τ : Cardinal) := by
    calc
      Module.rank (IntermediateField.fixedField (Subgroup.zpowers τ)) K =
          (Module.finrank (IntermediateField.fixedField (Subgroup.zpowers τ)) K : Cardinal) :=
        hrank
      _ = (orderOf τ : Cardinal) :=
        congrArg (fun n : ℕ => (n : Cardinal)) hfinrankNat
  exact by
    simpa [hτ] using hrank'

/--
Let $F$ be a field and let $f(x) \in F[x]$ be an irreducible polynomial.
Suppose that $K$ is a splitting field for $f(x)$ over $F$ and assume that there exists an element
$\alpha \in K$ such that both $\alpha$ and $\alpha+1$ are roots of $f(x)$.
Prove that there exists an intermediate field $E$ between $K$ and $F$ such that $[K:E]$
is equal to the characteristic of $F$. (In particular, the characteristic of $F$ is not zero)
-/
theorem intermediateField_rank_eq_ringChar (F : Type) [Field F] (f : Polynomial F) (hf : Irreducible f)
    (K : Type) [Field K] [Algebra F K] (hK : f.IsSplittingField F K) (α : K)
    (hα : f.aeval α = 0) (hα1 : f.aeval (α + 1) = 0) :
    ∃ (E : IntermediateField F K), Module.rank E K = ringChar F := by
  classical
  letI : f.IsSplittingField F K := hK
  haveI : FiniteDimensional F K := IsSplittingField.finiteDimensional (K := F) (L := K) f
  haveI : Normal F K := Normal.of_isSplittingField (E := K) (p := f)
  have hassoc :
      Associated (minpoly F α) f :=
    intermediateField_rank_eq_ringChar_associated_minpoly F K f hf α hα
  have hmin :
      (minpoly F α).aeval (α + 1) = 0 :=
    intermediateField_rank_eq_ringChar_aeval_minpoly_alpha_add_one F K f α hassoc hα1
  obtain ⟨σ, hσ⟩ :=
    intermediateField_rank_eq_ringChar_exists_sigma F K f hf α hα hmin
  have hdiv : ringChar F ∣ orderOf σ :=
    intermediateField_rank_eq_ringChar_ringChar_dvd_orderOf F K α σ hσ
  have horder_ne : orderOf σ ≠ 0 := (orderOf_pos σ).ne'
  set τ : Gal(K/F) := σ ^ (orderOf σ / ringChar F)
  have hτ : orderOf τ = ringChar F := by
    have hτ' :
        orderOf (σ ^ (orderOf σ / ringChar F)) = ringChar F :=
      orderOf_pow_orderOf_div (x := σ) (n := ringChar F) horder_ne hdiv
    simpa [τ] using hτ'
  refine ⟨IntermediateField.fixedField (Subgroup.zpowers τ), ?_⟩
  exact intermediateField_rank_eq_ringChar_fixedField_rank F K τ hτ
