import Mathlib

/--
The field $K = \mathbb{Q}(\sqrt{p_1}, \dots, \sqrt{p_r})$
for a finite list of integers $p_1, \dots, p_r$.
-/
abbrev RatAdjoinSqrt {I : Type} (p : I → ℕ) : Type :=
  Algebra.adjoin ℚ (Set.range (fun i ↦ Real.sqrt (p i)))

noncomputable section

/-- The real square root of a natural number is integral over ℚ. -/
lemma isIntegral_real_sqrt_nat (n : ℕ) : IsIntegral ℚ (Real.sqrt n) := by
  refine ⟨Polynomial.X ^ 2 - Polynomial.C (n : ℚ), ?_, ?_⟩
  ·
    simpa using
      (Polynomial.monic_X_pow_sub_C (R:=ℚ) (a:=(n:ℚ)) (n:=2) (by decide))
  ·
    have hnonneg : (0 : ℝ) ≤ (n : ℝ) := by
      exact_mod_cast (Nat.zero_le n)
    have hsq : (Real.sqrt n) ^ 2 = (n : ℝ) := by
      simpa using (Real.sq_sqrt (x := (n : ℝ)) hnonneg)
    simp [hsq]

/-- The ℚ-subalgebra generated by square roots is algebraic over ℚ. -/
lemma ratAdjoinSqrt_subalgebra_isAlgebraic {I : Type} (p : I → ℕ) :
    (Algebra.adjoin ℚ (Set.range fun i => Real.sqrt (p i))).IsAlgebraic := by
  classical
  refine
    (Algebra.isAlgebraic_adjoin_iff (R:=ℚ) (S:=ℝ)
      (s:=Set.range fun i => Real.sqrt (p i))).2 ?_
  intro x hx
  rcases hx with ⟨i, rfl⟩
  exact (isIntegral_real_sqrt_nat (p i)).isAlgebraic

/-- The `IntermediateField` adjoin agrees with the `Subalgebra` adjoin for these generators. -/
lemma ratAdjoinSqrt_eq_intermediateField_adjoin {I : Type} (p : I → ℕ) :
    (IntermediateField.adjoin ℚ (Set.range fun i => Real.sqrt (p i))).toSubalgebra =
      Algebra.adjoin ℚ (Set.range fun i => Real.sqrt (p i)) := by
  classical
  refine
    (IntermediateField.adjoin_toSubalgebra_of_isAlgebraic (F:=ℚ) (E:=ℝ)
      (S:=Set.range fun i => Real.sqrt (p i)) ?_)
  intro x hx
  rcases hx with ⟨i, rfl⟩
  exact (isIntegral_real_sqrt_nat (p i)).isAlgebraic

/-- Each generator `√(p i)` lies in the ℚ-subalgebra adjoined by all these square roots. -/
lemma sqrt_mem_ratAdjoinSqrt {I : Type} (p : I → ℕ) (i : I) :
    (Real.sqrt (p i)) ∈
      (Algebra.adjoin ℚ (Set.range fun i => Real.sqrt (p i)) : Subalgebra ℚ ℝ) := by
  simpa using
    (Algebra.subset_adjoin (R:=ℚ) (A:=ℝ)
      (s:=Set.range fun i => Real.sqrt (p i)) ⟨i, rfl⟩)

/-- The square of the distinguished generator equals the algebraMap of `p i`. -/
lemma sqrt_sq_in_ratAdjoinSqrt {I : Type} (p : I → ℕ) (i : I) :
    ((⟨Real.sqrt (p i), sqrt_mem_ratAdjoinSqrt p i⟩ : RatAdjoinSqrt p)^2) =
      algebraMap ℚ (RatAdjoinSqrt p) (p i : ℚ) := by
  ext
  simp

/-- Any ℚ-algebra automorphism sends each generator to itself or its negation. -/
lemma algEquiv_sqrt_eq_or_eq_neg {I : Type} (p : I → ℕ)
    (σ : RatAdjoinSqrt p ≃ₐ[ℚ] RatAdjoinSqrt p) (i : I) :
    σ (⟨Real.sqrt (p i), sqrt_mem_ratAdjoinSqrt p i⟩ : RatAdjoinSqrt p) =
        (⟨Real.sqrt (p i), sqrt_mem_ratAdjoinSqrt p i⟩ : RatAdjoinSqrt p) ∨
      σ (⟨Real.sqrt (p i), sqrt_mem_ratAdjoinSqrt p i⟩ : RatAdjoinSqrt p) =
        - (⟨Real.sqrt (p i), sqrt_mem_ratAdjoinSqrt p i⟩ : RatAdjoinSqrt p) := by
  let x : RatAdjoinSqrt p := ⟨Real.sqrt (p i), sqrt_mem_ratAdjoinSqrt p i⟩
  have hx : x ^ 2 = algebraMap ℚ (RatAdjoinSqrt p) (p i : ℚ) := by
    simpa [x] using (sqrt_sq_in_ratAdjoinSqrt (p:=p) i)
  have hx' : σ (x ^ 2) = σ (algebraMap ℚ (RatAdjoinSqrt p) (p i : ℚ)) := by
    simpa [hx]
  have hx'' : (σ x) ^ 2 = algebraMap ℚ (RatAdjoinSqrt p) (p i : ℚ) := by
    simpa [map_pow, AlgEquiv.commutes] using hx'
  have hsq : (σ x) ^ 2 = x ^ 2 := by
    simpa [hx] using hx''
  simpa [x] using (sq_eq_sq_iff_eq_or_eq_neg).1 hsq

/-! Helper constructions for the sign map. -/

/-- The distinguished generator `√(p i)` as an element of `RatAdjoinSqrt p`. -/
abbrev sqrtGen {I : Type} (p : I → ℕ) (i : I) : RatAdjoinSqrt p :=
  ⟨Real.sqrt (p i), sqrt_mem_ratAdjoinSqrt p i⟩

/-- The pointwise sign associated to an automorphism on generators. -/
def toSignsFun {I : Type} (p : I → ℕ)
    (σ : RatAdjoinSqrt p ≃ₐ[ℚ] RatAdjoinSqrt p) : I → ZMod 2 :=
  fun i =>
    if σ (sqrtGen p i) = sqrtGen p i then (0 : ZMod 2) else 1

/-- Each generator `sqrtGen p i` is nonzero for prime `p i`. -/
lemma sqrtGen_ne_zero {I : Type} (p : I → ℕ)
    (hp : ∀ i, (p i).Prime) (i : I) :
    (sqrtGen p i : RatAdjoinSqrt p) ≠ 0 := by
  intro h
  have hval : (Real.sqrt (p i)) = 0 := by
    exact congrArg Subtype.val h
  have hpos : (0 : ℝ) < (p i : ℝ) := by
    exact_mod_cast (Nat.Prime.pos (hp i))
  exact (Real.sqrt_ne_zero'.mpr hpos) hval

/-- If an automorphism acts on generators with a prescribed sign function, then `toSignsFun` is that function. -/
lemma toSignsFun_eq_of_sqrtGen {I : Type} (p : I → ℕ)
    (hp : ∀ i, (p i).Prime)
    (σ : RatAdjoinSqrt p ≃ₐ[ℚ] RatAdjoinSqrt p) (ε : I → ZMod 2)
    (hσ : ∀ i, σ (sqrtGen p i) =
      if ε i = 0 then sqrtGen p i else -sqrtGen p i) :
    toSignsFun p σ = ε := by
  classical
  funext i
  have hσi := hσ i
  fin_cases hε : ε i
  · simp [toSignsFun, hσi, hε]
  ·
    have hne : -sqrtGen p i ≠ sqrtGen p i := by
      intro hneg
      have hval : -(Real.sqrt (p i)) = Real.sqrt (p i) := by
        exact congrArg Subtype.val hneg
      have hzero : (Real.sqrt (p i)) = 0 := by
        nlinarith
      have hzero_sub : (sqrtGen p i : RatAdjoinSqrt p) = 0 := by
        apply Subtype.ext
        simpa [sqrtGen] using hzero
      exact (sqrtGen_ne_zero (p:=p) (hp:=hp) i) hzero_sub
    simp [toSignsFun, hσi, hε, hne]

/-- `toSignsFun` applied to the identity automorphism is the zero function. -/
lemma toSignsFun_one {I : Type} (p : I → ℕ) :
    toSignsFun p (AlgEquiv.refl (R:=ℚ) (A₁:=RatAdjoinSqrt p)) = 0 := by
  funext i
  simp [toSignsFun, sqrtGen]

/-- `toSignsFun` respects composition of automorphisms. -/
lemma toSignsFun_mul {I : Type} (p : I → ℕ)
    (σ τ : RatAdjoinSqrt p ≃ₐ[ℚ] RatAdjoinSqrt p) :
    toSignsFun p (σ * τ) = toSignsFun p σ + toSignsFun p τ := by
  funext i
  have hσ := algEquiv_sqrt_eq_or_eq_neg (p:=p) σ i
  have hτ := algEquiv_sqrt_eq_or_eq_neg (p:=p) τ i
  rcases hσ with hσ | hσ <;> rcases hτ with hτ | hτ
  · simp [toSignsFun, hσ, hτ]
  · simp [toSignsFun, hσ, hτ]
  · simp [toSignsFun, hσ, hτ]
  · have hcomp :
        (σ * τ) (sqrtGen p i) = sqrtGen p i := by
        calc
          (σ * τ) (sqrtGen p i)
              = σ (τ (sqrtGen p i)) := rfl
          _ = σ (-sqrtGen p i) := by simp [hτ]
          _ = -σ (sqrtGen p i) := by simp
          _ = -(-sqrtGen p i) := by simp [hσ]
          _ = sqrtGen p i := by simp
    have hsum :
        (if -sqrtGen p i = sqrtGen p i then (0 : ZMod 2) else 1) +
            (if -sqrtGen p i = sqrtGen p i then (0 : ZMod 2) else 1) = 0 := by
      simpa using
        (ZModModule.add_self (G:=ZMod 2)
          (if -sqrtGen p i = sqrtGen p i then (0 : ZMod 2) else 1))
    simp [toSignsFun, hσ, hτ, hcomp, hsum]

/-- The sign map sends the identity automorphism to `1`. -/
lemma toSigns_map_one {I : Type} (p : I → ℕ) :
    (Multiplicative.ofAdd
        (toSignsFun p (AlgEquiv.refl (R:=ℚ) (A₁:=RatAdjoinSqrt p))) :
        Multiplicative (I → ZMod 2)) = 1 := by
  -- `Multiplicative` is definitional, so this reduces to `toSignsFun_one`.
  simp [toSignsFun_one]

/-- The sign map respects multiplication of automorphisms. -/
lemma toSigns_map_mul {I : Type} (p : I → ℕ)
    (σ τ : RatAdjoinSqrt p ≃ₐ[ℚ] RatAdjoinSqrt p) :
    (Multiplicative.ofAdd (toSignsFun p (σ * τ)) :
        Multiplicative (I → ZMod 2)) =
      (Multiplicative.ofAdd (toSignsFun p σ)) *
        (Multiplicative.ofAdd (toSignsFun p τ)) := by
  -- Definitional equality + `toSignsFun_mul`.
  simpa [toSignsFun_mul]

/-- The sign map as a multiplicative homomorphism. -/
def toSigns {I : Type} (p : I → ℕ) :
    (RatAdjoinSqrt p ≃ₐ[ℚ] RatAdjoinSqrt p) →*
      (Multiplicative (I → ZMod 2)) :=
  { toFun := fun σ => Multiplicative.ofAdd (toSignsFun p σ)
    map_one' := toSigns_map_one (p:=p)
    map_mul' := toSigns_map_mul (p:=p) }

/-- The sign map on automorphisms is injective. -/
lemma toSigns_injective {I : Type} (p : I → ℕ) :
    Function.Injective (toSigns (p:=p)) := by
  classical
  intro σ τ h
  have hfun : toSignsFun p σ = toSignsFun p τ := by
    simpa [toSigns] using h
  have hgen : ∀ i, σ (sqrtGen p i) = τ (sqrtGen p i) := by
    intro i
    have hfun_i : toSignsFun p σ i = toSignsFun p τ i := by
      simpa using congrArg (fun f => f i) hfun
    have hσ := algEquiv_sqrt_eq_or_eq_neg (p:=p) σ i
    have hτ := algEquiv_sqrt_eq_or_eq_neg (p:=p) τ i
    cases hσ with
    | inl hσeq =>
        have hτeq : τ (sqrtGen p i) = sqrtGen p i := by
          by_contra hτne
          have hcontr : (0 : ZMod 2) = 1 := by
            simpa [toSignsFun, hσeq, hτne] using hfun_i
          exact (by decide : (0 : ZMod 2) ≠ 1) hcontr
        simpa [hσeq, hτeq]
    | inr hσeq =>
        have hτeq : τ (sqrtGen p i) = -sqrtGen p i := by
          cases hτ with
          | inl hτpos =>
              have hcontr : (1 : ZMod 2) = 0 := by
                simpa [toSignsFun, hσeq, hτpos] using hfun_i
              exact (by decide : (1 : ZMod 2) ≠ 0) hcontr
          | inr hτneg =>
              exact hτneg
        simpa [hσeq, hτeq]
  apply AlgEquiv.ext
  intro x
  -- Induct on the generators of the adjoin to show `σ` and `τ` agree everywhere.
  simpa using
    (Algebra.adjoin_induction (s := Set.range fun i => Real.sqrt (p i))
      (p := fun x hx => (σ ⟨x, hx⟩ = τ ⟨x, hx⟩))
      (fun x hx => by
        rcases hx with ⟨i, rfl⟩
        simpa [sqrtGen] using hgen i)
      (fun r => by simp)
      (fun x y hx hy hx' hy' => by
        calc
          σ ⟨x + y, add_mem hx hy⟩
              = σ ⟨x, hx⟩ + σ ⟨y, hy⟩ := by
                  simpa using (map_add σ ⟨x, hx⟩ ⟨y, hy⟩)
          _ = τ ⟨x, hx⟩ + τ ⟨y, hy⟩ := by
                  simpa [hx', hy']
          _ = τ ⟨x + y, add_mem hx hy⟩ := by
                  symm
                  simpa using (map_add τ ⟨x, hx⟩ ⟨y, hy⟩))
      (fun x y hx hy hx' hy' => by
        calc
          σ ⟨x * y, mul_mem hx hy⟩
              = σ ⟨x, hx⟩ * σ ⟨y, hy⟩ := by
                  simpa using (map_mul σ ⟨x, hx⟩ ⟨y, hy⟩)
          _ = τ ⟨x, hx⟩ * τ ⟨y, hy⟩ := by
                  simpa [hx', hy']
          _ = τ ⟨x * y, mul_mem hx hy⟩ := by
                  symm
                  simpa using (map_mul τ ⟨x, hx⟩ ⟨y, hy⟩))
      x.property)

/-- Nonempty index case for `exists_algEquiv_of_signs`. -/
lemma exists_algEquiv_of_signs_nonempty {I : Type} [Finite I] (p : I → ℕ)
    (hp : ∀ (i : I), (p i).Prime) (h_inj : p.Injective) [Nonempty I] :
    ∀ ε : I → ZMod 2,
      ∃ σ : RatAdjoinSqrt p ≃ₐ[ℚ] RatAdjoinSqrt p,
        ∀ i, σ (sqrtGen p i) =
          if ε i = 0 then sqrtGen p i else -sqrtGen p i := by
  sorry

/-- Every sign pattern is realized by an automorphism of the multiquadratic subfield. -/
lemma exists_algEquiv_of_signs {I : Type} [Finite I] (p : I → ℕ)
    (hp : ∀ (i : I), (p i).Prime) (h_inj : p.Injective) :
    ∀ ε : I → ZMod 2,
      ∃ σ : RatAdjoinSqrt p ≃ₐ[ℚ] RatAdjoinSqrt p,
        ∀ i, σ (sqrtGen p i) =
          if ε i = 0 then sqrtGen p i else -sqrtGen p i := by
  classical
  by_cases hI : IsEmpty I
  ·
    haveI : IsEmpty I := hI
    intro ε
    refine ⟨AlgEquiv.refl (R:=ℚ) (A₁:=RatAdjoinSqrt p), ?_⟩
    intro i
    cases (IsEmpty.false i)
  ·
    haveI : Nonempty I := (not_isEmpty_iff.mp hI)
    exact exists_algEquiv_of_signs_nonempty (p:=p) (hp:=hp) (h_inj:=h_inj)

lemma toSigns_surjective {I : Type} [Finite I] (p : I → ℕ)
    (hp : ∀ (i : I), (p i).Prime) (h_inj : p.Injective) :
    Function.Surjective (toSigns (p:=p)) := by
  classical
  by_cases hI : IsEmpty I
  ·
    haveI : IsEmpty I := hI
    /-- If the index type is empty, the sign map is trivially surjective. -/
    have hsurj_empty :
        Function.Surjective (toSigns (p:=p)) := by
      intro ε
      refine ⟨AlgEquiv.refl (R:=ℚ) (A₁:=RatAdjoinSqrt p), ?_⟩
      simpa using (Subsingleton.elim _ _ : (1 : Multiplicative (I → ZMod 2)) = ε)
    simpa using hsurj_empty
  ·
    -- Nonempty case: need explicit automorphisms realizing arbitrary sign patterns.
    haveI : Fintype I := Fintype.ofFinite I
    intro ε
    obtain ⟨σ, hσ⟩ :=
      exists_algEquiv_of_signs (p:=p) (hp:=hp) (h_inj:=h_inj) ε
    refine ⟨σ, ?_⟩
    have hfun : toSignsFun p σ = ε :=
      toSignsFun_eq_of_sqrtGen (p:=p) (hp:=hp) (σ:=σ) (ε:=ε) hσ
    simpa [toSigns, hfun]

/--
Auxiliary statement isolating the remaining construction of the multiquadratic automorphism group.
-/
lemma galoisGroup_iso_of_distinct_primes_aux {I : Type} [Finite I] (p : I → ℕ)
    (hp : ∀ (i : I), (p i).Prime) (h_inj : p.Injective) :
    Nonempty ((RatAdjoinSqrt p ≃ₐ[ℚ] RatAdjoinSqrt p) ≃*
      (Multiplicative (I → (ZMod 2)))) := by
  classical
  refine ⟨MulEquiv.ofBijective (toSigns (p:=p)) ?_⟩
  exact ⟨toSigns_injective (p:=p), toSigns_surjective (p:=p) (hp:=hp) (h_inj:=h_inj)⟩

/--
Let $p_1, \dots, p_r$ be $r$ different prime numbers.
Prove that the Galois group of $K =\mathbb{Q}(\sqrt{p_1}, \dots, \sqrt{p_r})$ over $\mathbb{Q}$
is $(\mathbb{Z}/2\mathbb{Z})^r$, here $\mathbb{Z}/2\mathbb{Z}$ is the cyclic group of order 2.
-/
theorem galoisGroup_iso_of_distinct_primes {I : Type} [Finite I] (p : I → ℕ)
    (hp : ∀ (i : I), (p i).Prime) (h_inj : p.Injective) :
    Nonempty ((RatAdjoinSqrt p ≃ₐ[ℚ] RatAdjoinSqrt p) ≃* (Multiplicative (I → (ZMod 2)))) := by
  classical
  simpa using (galoisGroup_iso_of_distinct_primes_aux (p:=p) (hp:=hp) (h_inj:=h_inj))

end
