import Mathlib

open Module
open Polynomial

/-- A primitive `p^2`-th root of unity gives a nonempty set of primitive roots. -/
lemma FATEX27.primitiveRoots_p2_nonempty (p : ℕ) (hp : p.Prime) {K : Type} [Field K] {ζ : K}
    (h : IsPrimitiveRoot ζ (p^2)) : (primitiveRoots (p^2) K).Nonempty := by
  classical
  refine ⟨ζ, ?_⟩
  have hpos : 0 < p ^ 2 := by
    exact pow_pos hp.pos 2
  exact (mem_primitiveRoots (R:=K) (k:=p^2) hpos).2 h

set_option maxHeartbeats 8000000 in
/-- Roots of `X^p - a` lie in the field generated by roots of `X^(p^2) - a`. -/
lemma FATEX27.rootSet_X_pow_sub_C_subset_adjoin_rootSet_p2
    (p : ℕ) (hp : 0 < p) {K : Type} [Field K] (a : K) :
    (X ^ p - C a).rootSet (AlgebraicClosure K) ⊆
      (IntermediateField.adjoin K ((X ^ (p^2) - C a).rootSet (AlgebraicClosure K)) :
        Set (AlgebraicClosure K)) := by
  classical
  intro y hy
  have hy0 : (aeval y) (X ^ p - C a) = 0 :=
    aeval_eq_zero_of_mem_rootSet hy
  have hy_pow : y ^ p = algebraMap K (AlgebraicClosure K) a := by
    have hy0' := hy0
    rw [Polynomial.aeval_sub, aeval_X_pow, aeval_C] at hy0'
    exact sub_eq_zero.mp hy0'
  obtain ⟨x, hx⟩ := IsAlgClosed.exists_pow_nat_eq (k := AlgebraicClosure K) y hp
  have hx_pow : x ^ (p^2) = algebraMap K (AlgebraicClosure K) a := by
    calc
      x ^ (p^2) = x ^ (p * p) := by simp [pow_two]
      _ = (x ^ p) ^ p := by simp [pow_mul]
      _ = y ^ p := by simp [hx]
      _ = algebraMap K (AlgebraicClosure K) a := hy_pow
  have hne : (X ^ (p^2) - C a : K[X]) ≠ 0 := X_pow_sub_C_ne_zero (pow_pos hp 2) a
  have hxroot : x ∈ (X ^ (p^2) - C a).rootSet (AlgebraicClosure K) := by
    refine (mem_rootSet_of_ne (S:=AlgebraicClosure K) hne).2 ?_
    rw [Polynomial.aeval_sub, aeval_X_pow, aeval_C, hx_pow]
    exact sub_eq_zero.mpr rfl
  have hxL' :
      x ∈ (IntermediateField.adjoin K ((X ^ (p^2) - C a).rootSet (AlgebraicClosure K))) :=
    (IntermediateField.subset_adjoin K
      (S := (X ^ (p^2) - C a).rootSet (AlgebraicClosure K)) hxroot)
  have hxpow_mem :
      x ^ p ∈ (IntermediateField.adjoin K
        ((X ^ (p^2) - C a).rootSet (AlgebraicClosure K))) := by
    have hxpow_mem' :
        x ^ p ∈ (IntermediateField.adjoin K
          ((X ^ (p^2) - C a).rootSet (AlgebraicClosure K))).toSubfield :=
      (IntermediateField.adjoin K
        ((X ^ (p^2) - C a).rootSet (AlgebraicClosure K))).toSubfield.pow_mem
        ((IntermediateField.mem_toSubfield
          (s := IntermediateField.adjoin K
            ((X ^ (p^2) - C a).rootSet (AlgebraicClosure K))) (x := x)).2 hxL') p
    exact (IntermediateField.mem_toSubfield
      (s := IntermediateField.adjoin K
        ((X ^ (p^2) - C a).rootSet (AlgebraicClosure K))) (x := x ^ p)).1 hxpow_mem'
  simpa [hx] using hxpow_mem

/-- A primitive 4th root gives a square root of `-1`. -/
lemma FATEX27.isSquare_neg_one_of_isPrimitiveRoot_four {K : Type} [Field K] {ζ : K}
    (hζ : IsPrimitiveRoot ζ 4) : IsSquare (-1 : K) := by
  classical
  have hpos : 0 < (4 : ℕ) := by decide
  have hprod : (4 : ℕ) = 2 * 2 := by simp
  have hζ2 : IsPrimitiveRoot (ζ ^ 2) 2 := by
    simpa using (IsPrimitiveRoot.pow (n:=4) (a:=2) (b:=2) hpos hζ hprod)
  have hneg : ζ ^ 2 = (-1 : K) := by
    simpa using (IsPrimitiveRoot.eq_neg_one_of_two_right hζ2)
  refine ⟨ζ, ?_⟩
  simpa [pow_two] using hneg.symm

/-- Irreducibility of `X^2 - a` implies `a` is not a square. -/
lemma FATEX27.not_isSquare_of_irreducible_X2_sub_C {K : Type} [Field K] {a : K}
    (hIrred : Irreducible (X ^ 2 - C a : K[X])) : ¬ IsSquare a := by
  intro hsq
  rcases hsq with ⟨b, hb⟩
  have hne := pow_ne_of_irreducible_X_pow_sub_C (n:=2) (a:=a) hIrred (m:=2)
    (dvd_rfl) (by decide : (2 : ℕ) ≠ 1) b
  exact hne (by simpa [pow_two] using hb.symm)

/-- Expanded product of two monic quadratics. -/
lemma FATEX27.mul_quadratic {K : Type} [Field K] (b c d e : K) :
    ((X : K[X]) ^ 2 + C b * X + C c) * ((X : K[X]) ^ 2 + C d * X + C e) =
      X ^ 4 + C (b + d) * X ^ 3 + C (c + b * d + e) * X ^ 2 +
        C (b * e + c * d) * X + C (c * e) := by
  simp [C_add, C_mul]
  ring_nf

/-- If `X^4 - a` is reducible, then `a` or `-a` is a square. -/
lemma FATEX27.isSquare_or_isSquare_neg_of_reducible_X4_sub_C {K : Type} [Field K] {a : K} :
    (¬ Irreducible (X ^ 4 - C a : K[X])) → (IsSquare a ∨ IsSquare (-a)) := by
  classical
  intro hred
  let f : K[X] := X ^ 4 - C a
  have hmonic : f.Monic := by
    simpa [f] using (monic_X_pow_sub_C (R:=K) (a:=a) (n:=4) (by decide : (4 : ℕ) ≠ 0))
  have hdegf : f.natDegree = 4 := by
    simp [f]
  have hne1 : f ≠ 1 := by
    intro h
    have hdeg0 : f.natDegree = 0 := by
      simp [h]
    have : (4 : ℕ) = 0 := by
      calc
        (4 : ℕ) = f.natDegree := hdegf.symm
        _ = 0 := hdeg0
    exact (Nat.succ_ne_zero 3) this
  have hnot :
      ¬ (∀ q, q.Monic → q.natDegree ∈ Finset.Ioc 0 (f.natDegree / 2) → ¬ q ∣ f) :=
    (not_congr (Monic.irreducible_iff_lt_natDegree_lt (p:=f) hmonic hne1)).1
      (by simpa [f] using hred)
  push_neg at hnot
  rcases hnot with ⟨q, hqmonic, hqdeg, hqdiv⟩
  have hdegf2 : f.natDegree / 2 = 2 := by simp [hdegf]
  have hqdeg' : 0 < q.natDegree ∧ q.natDegree ≤ 2 := by
    simpa [Finset.mem_Ioc, hdegf2] using hqdeg
  have hqdeg_pos : 0 < q.natDegree := hqdeg'.1
  have hqdeg_le : q.natDegree ≤ 2 := hqdeg'.2
  by_cases hq1 : q.natDegree = 1
  · -- Linear factor gives a fourth root, hence a square.
    have hqmono1 : IsMonicOfDegree q 1 := by
      refine (isMonicOfDegree_iff (R:=K) q 1).2 ?_
      refine ⟨le_of_eq hq1, ?_⟩
      have hcoeff : q.coeff q.natDegree = 1 := by simpa using hqmonic.coeff_natDegree
      simpa [hq1] using hcoeff
    obtain ⟨r, hr⟩ := (isMonicOfDegree_one_iff (R:=K) (f:=q)).1 hqmono1
    have hdiv' : X - C (-r) ∣ f := by
      have hq' : q = X - C (-r) := by simpa [sub_eq_add_neg] using hr
      simpa [hq'] using hqdiv
    have hroot : IsRoot f (-r) := (dvd_iff_isRoot).1 hdiv'
    have hpow : (-r) ^ 4 = a := by
      have hval : (X ^ 4 - C a : K[X]).eval (-r) = 0 := by
        simpa [f] using hroot
      have hval' : (-r) ^ 4 - a = 0 := by
        simpa [Polynomial.eval_sub, Polynomial.eval_pow, eval_X, eval_C] using hval
      exact sub_eq_zero.mp hval'
    refine Or.inl ?_
    refine ⟨(-r) ^ 2, ?_⟩
    have hsq : a = (-r) ^ 2 * (-r) ^ 2 := by
      calc
        a = (-r) ^ 4 := hpow.symm
        _ = (-r) ^ (2 * 2) := by simp
        _ = ((-r) ^ 2) ^ 2 := by simpa using (pow_mul (-r) 2 2)
        _ = (-r) ^ 2 * (-r) ^ 2 := by simp [pow_two]
    exact hsq
  · -- Quadratic factorization gives a square or negative square.
    have hqdeg2 : q.natDegree = 2 := by
      have hqle' : q.natDegree = 2 ∨ q.natDegree < 2 := Nat.eq_or_lt_of_le hqdeg_le
      cases hqle' with
      | inl h => exact h
      | inr hlt =>
        have hle1 : q.natDegree ≤ 1 := Nat.lt_succ_iff.mp hlt
        have hcases : q.natDegree = 0 ∨ q.natDegree = 1 := by
          cases Nat.eq_or_lt_of_le hle1 with
          | inl h1 => exact Or.inr h1
          | inr hlt1 => exact Or.inl (Nat.lt_one_iff.mp hlt1)
        cases hcases with
        | inl h0 => exact (hqdeg_pos.ne' h0).elim
        | inr h1 => exact (hq1 h1).elim
    rcases hqdiv with ⟨r, hr⟩
    have hrmonic : r.Monic := by
      have hqrmonic : (q * r).Monic := by simpa [hr] using hmonic
      exact Monic.of_mul_monic_left hqmonic hqrmonic
    have hdeg_qr : (q * r).natDegree = 4 := by
      simpa [hr, f] using hdegf
    have hdeg_r : r.natDegree = 2 := by
      have hdeg_sum : q.natDegree + r.natDegree = 4 := by
        simpa [hqmonic.natDegree_mul hrmonic] using hdeg_qr
      have hdeg_sum' : 2 + r.natDegree = 2 + 2 := by
        simpa [hqdeg2] using hdeg_sum
      exact Nat.add_left_cancel hdeg_sum'
    have hqmono2 : IsMonicOfDegree q 2 := by
      refine (isMonicOfDegree_iff (R:=K) q 2).2 ?_
      refine ⟨le_of_eq hqdeg2, ?_⟩
      have hcoeff : q.coeff q.natDegree = 1 := by simpa using hqmonic.coeff_natDegree
      simpa [hqdeg2] using hcoeff
    have hrmono2 : IsMonicOfDegree r 2 := by
      refine (isMonicOfDegree_iff (R:=K) r 2).2 ?_
      refine ⟨le_of_eq hdeg_r, ?_⟩
      have hcoeff : r.coeff r.natDegree = 1 := by simpa using hrmonic.coeff_natDegree
      simpa [hdeg_r] using hcoeff
    obtain ⟨b, c, hqform⟩ := (isMonicOfDegree_two_iff (R:=K) (f:=q)).1 hqmono2
    obtain ⟨d, e, hrform⟩ := (isMonicOfDegree_two_iff (R:=K) (f:=r)).1 hrmono2
    have hfac' : f =
        X ^ 4 + C (b + d) * X ^ 3 + C (c + b * d + e) * X ^ 2 +
          C (b * e + c * d) * X + C (c * e) := by
      simpa [hqform, hrform, FATEX27.mul_quadratic] using hr
    have hcoeff3 : b + d = 0 := by
      have hcoeff := congrArg (fun p => p.coeff 3) hfac'
      simp [f, coeff_add, coeff_X_pow, add_mul, add_assoc, mul_assoc] at hcoeff
      simpa [eq_comm] using hcoeff
    have hcoeff1 : b * e + c * d = 0 := by
      have hcoeff := congrArg (fun p => p.coeff 1) hfac'
      simp [f, coeff_add, coeff_X_pow, add_mul, add_assoc, mul_assoc] at hcoeff
      simpa [eq_comm] using hcoeff
    have hcoeff2 : c + b * d + e = 0 := by
      have hcoeff := congrArg (fun p => p.coeff 2) hfac'
      simp [f, coeff_add, coeff_X_pow, add_mul, add_assoc, mul_assoc] at hcoeff
      have : c + (b * d + e) = 0 := by simpa [eq_comm] using hcoeff
      simpa [add_assoc] using this
    have hcoeff0 : c * e = -a := by
      have hcoeff := congrArg (fun p => p.coeff 0) hfac'
      simp [f, coeff_add, coeff_X_pow, add_mul, add_assoc, mul_assoc] at hcoeff
      simpa [eq_comm] using hcoeff.symm
    have hd : d = -b := eq_neg_of_add_eq_zero_right hcoeff3
    have hbe' : b * (e - c) = 0 := by
      have hbe : b * e - c * b = 0 := by
        simpa [hd, sub_eq_add_neg, mul_comm, mul_left_comm, mul_assoc] using hcoeff1
      simpa [mul_sub, mul_comm, mul_left_comm, mul_assoc] using hbe
    rcases mul_eq_zero.mp hbe' with hb | hec
    · -- b = 0, so a is a square.
      have hd0 : d = 0 := by simpa [hb] using hd
      have hce : c + e = 0 := by
        simpa [hb, hd0, add_assoc] using hcoeff2
      have he : e = -c := eq_neg_of_add_eq_zero_right hce
      have hsq : c * c = a := by
        have hneg : c * (-c) = -a := by simpa [he] using hcoeff0
        have hneg' : -(c * c) = -a := by
          simpa [mul_comm, mul_left_comm, mul_assoc] using hneg
        exact neg_injective hneg'
      refine Or.inl ?_
      refine ⟨c, ?_⟩
      simpa [pow_two] using hsq.symm
    · -- e = c, so -a is a square.
      have he : e = c := by
        have : e - c = 0 := hec
        exact sub_eq_zero.mp this
      have hsq : c * c = -a := by
        simpa [he] using hcoeff0
      refine Or.inr ?_
      refine ⟨c, ?_⟩
      simpa [pow_two] using hsq.symm

/-- If `-1` and `-a` are squares, then `a` is a square. -/
lemma FATEX27.isSquare_of_isSquare_neg_one_of_isSquare_neg {K : Type} [Field K] {a : K}
    (hneg1 : IsSquare (-1 : K)) (hneg : IsSquare (-a)) : IsSquare a := by
  have hmul : IsSquare ((-1 : K) * (-a)) := IsSquare.mul hneg1 hneg
  simpa using hmul

/-- Irreducibility of `X^(p^2) - a` from irreducibility of `X^p - a`. -/
lemma FATEX27.irreducible_X_pow_sub_C_p2 (p : ℕ) (hp : p.Prime) {K : Type} [Field K]
    {ζ : K} (hζ : IsPrimitiveRoot ζ (p^2)) {a : K}
    (hIrred : Irreducible (X ^ p - C a)) :
    Irreducible (X ^ (p^2) - C a) := by
  classical
  by_cases h2 : p = 2
  · -- Quadratic case: reduce to `X^4 - a`.
    subst h2
    have hsqneg1 : IsSquare (-1 : K) := by
      simpa using (FATEX27.isSquare_neg_one_of_isPrimitiveRoot_four (K:=K) (ζ:=ζ)
        (by simpa using hζ))
    have hnot : ¬ IsSquare a := by
      simpa using (FATEX27.not_isSquare_of_irreducible_X2_sub_C (K:=K) (a:=a)
        (by simpa using hIrred))
    by_contra hred
    have hsq := FATEX27.isSquare_or_isSquare_neg_of_reducible_X4_sub_C (K:=K) (a:=a) hred
    cases hsq with
    | inl hsq_a => exact hnot hsq_a
    | inr hsq_neg =>
        have hsq_a : IsSquare a :=
          FATEX27.isSquare_of_isSquare_neg_one_of_isSquare_neg (K:=K) (a:=a) hsqneg1 hsq_neg
        exact hnot hsq_a
  · refine X_pow_sub_C_irreducible_of_prime_pow (K:=K) hp h2 2 ?_
    intro b
    exact pow_ne_of_irreducible_X_pow_sub_C hIrred (dvd_rfl) hp.ne_one b

set_option maxHeartbeats 800000 in
set_option synthInstance.maxHeartbeats 50000 in
/--
Let $p$ be a prime number. Let $K/\mathbb{Q}$ be a finite extension, such that the $p^{2}$th root of unity is contained in $K$.
Let $L/K$ be a Galois extension of degree $p$, show that there exists a Galois extension $L'/L$ of degree $p$,
such that the extension $L'/K$ is Galois.
-/
theorem isGalois_and_rank_eq_of_isPrimitiveRoot_sq (p : ℕ) (hp : p.Prime) {K : Type} [Field K]
    [NumberField K] {ζ : K} (h : IsPrimitiveRoot ζ (p^2))
    {L : IntermediateField K (AlgebraicClosure K)} [IsGalois K L]
    (hdeg : Module.rank K L = p) :
    ∃ (L' : Type) (_ : Field L') (_ : Algebra K L')
    (_ : Algebra L L') (_ : IsScalarTower K L L'),
    IsGalois K L' ∧ IsGalois L L' ∧ Module.rank L L' = p := by
  classical
  -- Convert the rank hypothesis into finrank and obtain finite dimensionality.
  have hfinrank : finrank K L = p := by
    simpa using (Module.finrank_eq_of_rank_eq (R:=K) (M:=L) hdeg)
  haveI : FiniteDimensional K L := by
    refine FiniteDimensional.of_finrank_pos ?_
    simpa [hfinrank] using hp.pos

  -- Produce a primitive p-th root of unity in K from the given p²-th root.
  have hprim : (primitiveRoots (finrank K L) K).Nonempty := by
    classical
    have hζp : IsPrimitiveRoot (ζ ^ p) p := by
      have hpos : 0 < p ^ 2 := by
        exact pow_pos hp.pos 2
      have hprod : p ^ 2 = p * p := by
        simp [pow_two]
      exact IsPrimitiveRoot.pow (n:=p^2) (a:=p) (b:=p) hpos h hprod
    refine ⟨ζ ^ p, ?_⟩
    have hpos' : 0 < finrank K L := by
      simpa [hfinrank] using hp.pos
    exact (mem_primitiveRoots (R:=K) (k:=finrank K L) hpos').2 (by simpa [hfinrank] using hζp)

  -- The Galois group has prime order, hence it is cyclic.
  have hcyc : IsCyclic Gal(L/K) := by
    classical
    let _ : Fact p.Prime := ⟨hp⟩
    have hcard : Nat.card Gal(L/K) = p := by
      simpa [hfinrank] using (IsGalois.card_aut_eq_finrank (F:=K) (E:=L))
    exact isCyclic_of_prime_card (α:=Gal(L/K)) (p:=p) hcard

  -- Extract the Kummer polynomial X^p - a whose splitting field is L.
  have hgalcyc : IsGalois K L ∧ IsCyclic Gal(L/K) :=
    ⟨(inferInstance : IsGalois K L), hcyc⟩
  obtain ⟨a, hIrred, hSplit⟩ :=
    ((isCyclic_tfae K L hprim).out 0 1).mp hgalcyc
  have hIrred' : Irreducible (X ^ p - C a) := by
    simpa [hfinrank] using hIrred
  have hSplit' : IsSplittingField K L (X ^ p - C a) := by
    simpa [hfinrank] using hSplit

  -- Remaining step: build the p²-Kummer splitting field inside the algebraic closure,
  -- show it contains L, and compute the relative rank.
  -- This is the remaining Kummer-theoretic construction.
  classical
  let g : K[X] := X ^ (p^2) - C a
  let L' : IntermediateField K (AlgebraicClosure K) :=
    IntermediateField.adjoin K (g.rootSet (AlgebraicClosure K))
  have hSplit_p2 : IsSplittingField K L' g := by
    refine (IntermediateField.adjoin_rootSet_isSplittingField (K:=K)
      (L:=AlgebraicClosure K) (p:=g) ?_)
    exact IsAlgClosed.splits_codomain (f := algebraMap K (AlgebraicClosure K)) g
  have hζ2 : (primitiveRoots (p^2) K).Nonempty :=
    FATEX27.primitiveRoots_p2_nonempty p hp h
  have hIrred_p2 : Irreducible (X ^ (p^2) - C a) :=
    FATEX27.irreducible_X_pow_sub_C_p2 p hp h hIrred'
  have hL_eq :
      (L : IntermediateField K (AlgebraicClosure K)) =
        IntermediateField.adjoin K ((X ^ p - C a).rootSet (AlgebraicClosure K)) := by
    have h' := (IntermediateField.isSplittingField_iff (K:=K) (L:=AlgebraicClosure K) (F:=L)
      (p:=X ^ p - C a)).1 hSplit'
    exact h'.2
  have hsubset :
      (X ^ p - C a).rootSet (AlgebraicClosure K) ⊆ (L' : Set (AlgebraicClosure K)) :=
    FATEX27.rootSet_X_pow_sub_C_subset_adjoin_rootSet_p2 p hp.pos a
  have hLle : L ≤ L' := by
    have hle' :
        IntermediateField.adjoin K ((X ^ p - C a).rootSet (AlgebraicClosure K)) ≤ L' :=
      (IntermediateField.adjoin_le_iff).2 hsubset
    simpa [hL_eq] using hle'
  let algLL' : Algebra L L' := (IntermediateField.inclusion hLle).toRingHom.toAlgebra
  have towerLL' : IsScalarTower K L L' := by
    letI : Algebra L L' := algLL'
    infer_instance
  letI : Algebra L L' := algLL'
  letI : IsScalarTower K L L' := towerLL'
  letI : IsSplittingField K L' (X ^ (p^2) - C a) := hSplit_p2
  have hGaloisKL' : IsGalois K L' :=
    isGalois_of_isSplittingField_X_pow_sub_C hζ2 hIrred_p2 L'
  letI : IsGalois K L' := hGaloisKL'
  have hGaloisLL' : IsGalois L L' :=
    IsGalois.tower_top_of_isGalois K L L'
  have hfinrank_p2 : finrank K L' = p^2 :=
    finrank_of_isSplittingField_X_pow_sub_C hζ2 hIrred_p2 L'
  haveI : FiniteDimensional K L' := by
    refine FiniteDimensional.of_finrank_pos ?_
    simpa [hfinrank_p2] using pow_pos hp.pos 2
  have hmul :
      finrank K L * finrank L L' = finrank K L' :=
    (Module.finrank_mul_finrank K L L')
  have hmul' : p * finrank L L' = p^2 := by
    simpa [hfinrank, hfinrank_p2] using hmul
  have hfinrank_LL' : finrank L L' = p := by
    have hmul'' : p * finrank L L' = p * p := by
      simpa [pow_two] using hmul'
    exact Nat.mul_left_cancel hp.pos hmul''
  haveI : Nat.AtLeastTwo p := ⟨hp.two_le⟩
  have hrank_LL' : Module.rank L L' = p := by
    exact (rank_eq_ofNat_iff_finrank_eq_ofNat (R:=L) (M:=L') p).2 hfinrank_LL'
  refine ⟨L', inferInstance, inferInstance, algLL', towerLL', ?_⟩
  exact ⟨hGaloisKL', hGaloisLL', hrank_LL'⟩
