import Mathlib

open Polynomial DualNumber
/--
Let \( k \) be a field, and let \( R = k[t]/(t^2) \). Set
\[
p(x) = tx^3 + tx^2 - x^2 - x \in R[x].
\]
Let \( S = R[x]/(p) \).
-/
abbrev S (k : Type) [Field k] : Type := ((DualNumber k)[X] ⧸ Ideal.span {((C ε) * X^3 + (C ε) * X^2 - X^2 - X : (DualNumber k)[X])})

/-- Prefer the commutative semiring structure on dual numbers for module instances. -/
local instance (k : Type) [Field k] : Semiring (DualNumber k) :=
  (inferInstance : CommSemiring (DualNumber k)).toSemiring

/-- Prefer the additive monoid structure inherited from quotient rings of `k[ε][X]`. -/
noncomputable local instance (k : Type) [Field k] (I : Ideal (DualNumber k)[X]) :
    AddCommMonoid ((DualNumber k)[X] ⧸ I) :=
  (inferInstance : Semiring ((DualNumber k)[X] ⧸ I)).toNonAssocSemiring.toAddCommMonoid

/--
\(S\) has a \(R\) module structure inherited from R[x].
-/
noncomputable instance (k : Type) [Field k] : Module (DualNumber k) (S k) := Algebra.toModule

/-- Factorization of the defining cubic polynomial. -/
lemma p_factor (k : Type) [Field k] :
    ((C (ε : DualNumber k)) * X^3 + (C (ε : DualNumber k)) * X^2 - X^2 - X :
        (DualNumber k)[X]) =
      ((C (ε : DualNumber k)) * X - 1) * (X^2 + X) := by
  ring

/-- The polynomial `(C ε) * X` is nilpotent. -/
lemma nilpotent_Ceps_mul_X (k : Type) [Field k] :
    IsNilpotent ((C (ε : DualNumber k)) * (X : (DualNumber k)[X])) := by
  refine ⟨2, ?_⟩
  have hceps : (C (ε : DualNumber k) : (DualNumber k)[X]) ^ 2 = 0 := by
    calc
      (C (ε : DualNumber k) : (DualNumber k)[X]) ^ 2 =
          C ((ε : DualNumber k) ^ 2) := by
        simp [Polynomial.C_pow]
      _ = 0 := by
        simp [pow_two, DualNumber.eps_mul_eps]
  calc
    ((C (ε : DualNumber k)) * (X : (DualNumber k)[X]))^2
        = (C (ε : DualNumber k))^2 * (X : (DualNumber k)[X])^2 := by
          simpa using (mul_pow (C (ε : DualNumber k)) (X : (DualNumber k)[X]) 2)
    _ = 0 := by
          simp [hceps]

/-- The principal ideals generated by the cubic polynomial and `X^2 + X` coincide. -/
lemma span_p_eq_span_q (k : Type) [Field k] :
    Ideal.span ({((C (ε : DualNumber k)) * X^3 + (C (ε : DualNumber k)) * X^2 - X^2 - X :
      (DualNumber k)[X])} : Set _) =
      Ideal.span ({(X^2 + X : (DualNumber k)[X])} : Set _) := by
  have hunit :
      IsUnit ((C (ε : DualNumber k)) * X - 1 : (DualNumber k)[X]) :=
    (nilpotent_Ceps_mul_X (k:=k)).isUnit_sub_one
  calc
    Ideal.span ({((C (ε : DualNumber k)) * X^3 + (C (ε : DualNumber k)) * X^2 - X^2 - X :
      (DualNumber k)[X])} : Set _) =
        Ideal.span ({((C (ε : DualNumber k)) * X - 1) * (X^2 + X : (DualNumber k)[X])} : Set _) := by
          simp [p_factor (k:=k)]
    _ = Ideal.span ({(X^2 + X : (DualNumber k)[X])} : Set _) := by
          simpa using
            (Ideal.span_singleton_mul_left_unit (a:=((C (ε : DualNumber k)) * X - 1)) hunit
              (X^2 + X : (DualNumber k)[X]))

/-- The polynomial `X^2 + X` is monic. -/
lemma monic_q (k : Type) [Field k] : (X^2 + X : (DualNumber k)[X]).Monic := by
  have hdeg : Polynomial.degree (X : (DualNumber k)[X]) < (2 : ℕ) := by
    simp [Polynomial.degree_X]
  simpa using (Polynomial.monic_X_pow_add (p:= (X : (DualNumber k)[X])) (n:=2) hdeg)

/-- The polynomial `X^2 + X` has natDegree `2`. -/
lemma natDegree_q (k : Type) [Field k] : ((X^2 + X : (DualNumber k)[X]).natDegree) = 2 := by
  have h1 : Polynomial.degree (X : (DualNumber k)[X]) = (1 : WithBot ℕ) := by
    simp [Polynomial.degree_X]
  have h2 : Polynomial.degree (X^2 : (DualNumber k)[X]) = (2 : WithBot ℕ) := by
    simp
  have hdeg :
      Polynomial.degree (X : (DualNumber k)[X]) <
        Polynomial.degree (X^2 : (DualNumber k)[X]) := by
    simp [h1, h2]
  calc
    (X^2 + X : (DualNumber k)[X]).natDegree = (X^2 : (DualNumber k)[X]).natDegree :=
      Polynomial.natDegree_add_eq_left_of_degree_lt hdeg
    _ = 2 := by
      simp

set_option maxHeartbeats 400000 in
/--
Let \( k \) be a field, and let \( R = k[t]/(t^2) \). Set
\[
p(x) = tx^3 + tx^2 - x^2 - x \in R[x].
\]
Show that \( S = R[x]/(p) \) is a free \( R \)-module of rank \( 2 \).
-/
theorem free_dualNumber_and_rank_eq_2 (k : Type) [Field k] :
    Module.Free (DualNumber k) (S k) ∧ Module.rank (DualNumber k) (S k) = 2 := by
  classical
  let q : (DualNumber k)[X] := X^2 + X
  let p : (DualNumber k)[X] :=
    (C (ε : DualNumber k)) * X^3 + (C (ε : DualNumber k)) * X^2 - X^2 - X
  letI : Module (DualNumber k)
      ((DualNumber k)[X] ⧸ Ideal.span ({q} : Set (DualNumber k)[X])) := Algebra.toModule
  letI : Module (DualNumber k)
      ((DualNumber k)[X] ⧸ Ideal.span ({p} : Set (DualNumber k)[X])) := Algebra.toModule
  have hspan :
      Ideal.span ({p} : Set (DualNumber k)[X]) = Ideal.span ({q} : Set (DualNumber k)[X]) := by
    simpa [p, q] using (span_p_eq_span_q (k:=k))
  have hmonic : q.Monic := by
    simpa [q] using (monic_q (k:=k))
  have hfree :
      Module.Free (DualNumber k)
        ((DualNumber k)[X] ⧸ Ideal.span ({q} : Set (DualNumber k)[X])) :=
    hmonic.free_quotient
  have hdeg : q.natDegree = 2 := by
    simpa [q] using (natDegree_q (k:=k))
  have hrank :
      Module.rank (DualNumber k)
          ((DualNumber k)[X] ⧸ Ideal.span ({q} : Set (DualNumber k)[X])) = 2 := by
    classical
    let b :
        Module.Basis (Fin q.natDegree) (DualNumber k)
          ((DualNumber k)[X] ⧸ Ideal.span ({q} : Set (DualNumber k)[X])) :=
      (AdjoinRoot.powerBasis' (g:=q) hmonic).basis
    have hrank' :
        Module.rank (DualNumber k)
            ((DualNumber k)[X] ⧸ Ideal.span ({q} : Set (DualNumber k)[X])) =
          Cardinal.mk (Fin q.natDegree) := by
      exact (b.mk_eq_rank'').symm
    have hdeg' : Cardinal.mk (Fin q.natDegree) = 2 := by
      exact (Cardinal.mk_fin q.natDegree).trans (congrArg (fun n : ℕ => (n : Cardinal)) hdeg)
    exact hrank'.trans hdeg'
  let e :=
    (Ideal.quotientEquivAlgOfEq (R₁ := DualNumber k) (A := (DualNumber k)[X]) hspan)
  refine And.intro ?_ ?_
  ·
    haveI :
        Module.Free (DualNumber k)
          ((DualNumber k)[X] ⧸ Ideal.span ({q} : Set (DualNumber k)[X])) := hfree
    have hfree' :
        Module.Free (DualNumber k)
          ((DualNumber k)[X] ⧸ Ideal.span ({p} : Set (DualNumber k)[X])) :=
      Module.Free.of_equiv e.toLinearEquiv.symm
    dsimp [S, p]
    exact hfree'
  ·
    have hrank' :
        Module.rank (DualNumber k)
            ((DualNumber k)[X] ⧸ Ideal.span ({p} : Set (DualNumber k)[X])) = 2 := by
      calc
        Module.rank (DualNumber k)
            ((DualNumber k)[X] ⧸ Ideal.span ({p} : Set (DualNumber k)[X])) =
          Module.rank (DualNumber k)
            ((DualNumber k)[X] ⧸ Ideal.span ({q} : Set (DualNumber k)[X])) := by
              simpa using (e.toLinearEquiv.rank_eq)
        _ = 2 := hrank
    dsimp [S, p]
    exact hrank'
