import Mathlib

/--
Let \(p\) be a prime, let \(G\) be a finite p-group.
Let A be a maximal normal abelian subgroup of \(G\).
Prove that A is also a maximal abelian subgroup of \(G\).
-/
-- If `H ≤ K` and `K` is abelian, then `K` centralizes `H`.
lemma subgroup_le_centralizer_of_le_and_comm
    {G : Type} [Group G] {H K : Subgroup G} (hHK : H ≤ K) (hKcomm : IsMulCommutative K) :
    K ≤ Subgroup.centralizer (H : Set G) := by
  have hKleCK : K ≤ Subgroup.centralizer (K : Set G) :=
    (Subgroup.le_centralizer_iff_isMulCommutative).2 hKcomm
  have hHleCK : H ≤ Subgroup.centralizer (K : Set G) := le_trans hHK hKleCK
  exact (Subgroup.le_centralizer_iff).1 hHleCK

-- Elements of `H` commute with all elements of `centralizer H`.
lemma subgroup_le_centralizer_centralizer
    {G : Type} [Group G] (H : Subgroup G) :
    H ≤ Subgroup.centralizer (Subgroup.centralizer (H : Set G) : Set G) := by
  intro h hh
  refine (Subgroup.mem_centralizer_iff).2 ?_
  intro c hc
  have hc' : h * c = c * h := (Subgroup.mem_centralizer_iff).1 hc h hh
  simp [hc'.symm]

-- If the centralizer equals the subgroup, commutativity transfers directly.
lemma centralizer_isMulCommutative_of_eq
    {G : Type} [Group G] (H : Subgroup G) (h_comm : IsMulCommutative H)
    (h_eq : Subgroup.centralizer (H : Set G) = H) :
    IsMulCommutative (Subgroup.centralizer (H : Set G)) := by
  rw [h_eq]
  exact h_comm

-- If `x` centralizes `H`, then the subgroup generated by `H` and `x` is abelian.
lemma abelian_closure_union_of_centralizer
    {G : Type} [Group G] (H : Subgroup G) {x : G}
    (hx : x ∈ Subgroup.centralizer (H : Set G)) (h_comm : IsMulCommutative H) :
    IsMulCommutative (Subgroup.closure ((H : Set G) ∪ {x})) := by
  classical
  letI := h_comm
  have hcomm :
      ∀ a ∈ (H : Set G) ∪ {x}, ∀ b ∈ (H : Set G) ∪ {x}, a * b = b * a := by
    intro a ha b hb
    rcases ha with ha | ha
    · rcases hb with hb | hb
      · -- both in H
        have h1 :
            ((⟨a, ha⟩ : H) * (⟨b, hb⟩ : H)) =
              ((⟨b, hb⟩ : H) * (⟨a, ha⟩ : H)) := by
          simp [mul_comm]
        exact congrArg Subtype.val h1
      · -- a in H, b = x
        have hxcomm := (Subgroup.mem_centralizer_iff).1 hx a ha
        have hb' : b = x := by simpa using hb
        simpa [hb'] using hxcomm
    · rcases hb with hb | hb
      · -- a = x, b in H
        have hxcomm := (Subgroup.mem_centralizer_iff).1 hx b hb
        have ha' : a = x := by simpa using ha
        simpa [ha'] using hxcomm.symm
      · -- both are x
        have ha' : a = x := by simpa using ha
        have hb' : b = x := by simpa using hb
        simp [ha', hb']
  letI := Subgroup.closureCommGroupOfComm (k := (H : Set G) ∪ {x}) hcomm
  refine ⟨Std.Commutative.mk ?_⟩
  intro a b
  simp [mul_comm]

-- A subsingleton subgroup is abelian.
lemma isMulCommutative_of_subsingleton
    {G : Type} [Group G] (K : Subgroup G) [Subsingleton K] :
    IsMulCommutative K := by
  refine ⟨Std.Commutative.mk ?_⟩
  intro a b
  exact Subsingleton.elim _ _

-- A `1`-group is trivial.
lemma subsingleton_of_isPGroup_one
    {G : Type} [Group G] (h : IsPGroup 1 G) :
    Subsingleton G := by
  classical
  refine ⟨?eq⟩
  intro a b
  have ha : a = 1 := by
    obtain ⟨k, hk⟩ := h a
    simpa using hk
  have hb : b = 1 := by
    obtain ⟨k, hk⟩ := h b
    simpa using hk
  simp [ha, hb]

-- The conjugation action of `G` on a normal subgroup descends to its quotient by the center.
instance conj_quotientAction_center {G : Type} [Group G] {C : Subgroup G} [C.Normal] :
    MulAction.QuotientAction (ConjAct G) (Subgroup.center C) := by
  refine ⟨?inv_mul_mem⟩
  intro g a a' ha
  have hchar : (Subgroup.center C).Characteristic := inferInstance
  have hle :
      (Subgroup.center C) ≤
        (Subgroup.center C).comap
          (MulAut.conjNormal (G:=G) (H:=C) (ConjAct.ofConjAct g)).toMonoidHom := by
    simpa using
      (Subgroup.characteristic_iff_le_comap).1 hchar
        (MulAut.conjNormal (G:=G) (H:=C) (ConjAct.ofConjAct g))
  have hx :
      (a⁻¹ * a') ∈
        (Subgroup.center C).comap
          (MulAut.conjNormal (G:=G) (H:=C) (ConjAct.ofConjAct g)).toMonoidHom :=
    hle ha
  have hx' :
      (MulAut.conjNormal (G:=G) (H:=C) (ConjAct.ofConjAct g) (a⁻¹ * a')) ∈
        Subgroup.center C := by
    simpa [Subgroup.mem_comap] using hx
  simpa [ConjAct.smul_def, mul_assoc] using hx'

-- A maximal normal abelian subgroup in a finite p-group is self-centralizing.
lemma centralizer_isMulCommutative_of_maximal_normal_abelian_in_pgroup
    (p : ℕ) (G : Type) [Group G] [Finite G] (h_pgroup : IsPGroup p G) (hp : p.Prime)
    (H : Subgroup G) (h_normal : H.Normal) (h_comm : IsMulCommutative H)
    (h_maximal_normal_abelian : ∀ (K : Subgroup G), K.Normal → IsMulCommutative K → H ≤ K → H = K) :
    IsMulCommutative (Subgroup.centralizer (H : Set G)) := by
  classical
  let C : Subgroup G := Subgroup.centralizer (H : Set G)
  have hHleC : H ≤ C :=
    (Subgroup.le_centralizer_iff_isMulCommutative).2 h_comm
  have hHleCC : H ≤ Subgroup.centralizer (C : Set G) :=
    subgroup_le_centralizer_centralizer H
  have hHleZ : H ≤ (Subgroup.center C).map C.subtype := by
    intro h hh
    have hhC : (⟨h, hHleC hh⟩ : C) ∈ Subgroup.center C := by
      refine (Subgroup.mem_center_iff).2 ?_
      intro c
      apply Subtype.ext
      have hcomm : c.1 * h = h * c.1 :=
        (Subgroup.mem_centralizer_iff).1 (hHleCC hh) c.1 c.2
      exact hcomm
    exact Subgroup.mem_map_of_mem C.subtype hhC
  have hCnormal : C.Normal := by
    infer_instance
  haveI : C.Normal := hCnormal
  have hZnormal : ((Subgroup.center C).map C.subtype).Normal := by
    infer_instance
  have hZcomm : IsMulCommutative ((Subgroup.center C).map C.subtype) := by
    infer_instance
  have hHeqZ : H = (Subgroup.center C).map C.subtype :=
    h_maximal_normal_abelian _ hZnormal hZcomm hHleZ
  -- If we can show the centralizer is abelian, maximality yields equality and then commutativity.
  -- The remaining missing step is a proof that the centralizer of a maximal normal abelian
  -- subgroup in a finite p-group is abelian.
  have hCcomm : IsMulCommutative C := by
    by_cases hCeq : C = H
    · rw [hCeq]; exact h_comm
    · -- TODO: need a proof that the centralizer of a maximal normal abelian subgroup is abelian,
      -- or a contradiction from `hCeq` using maximality in a finite p-group and `hHeqZ`.
      -- This is the blocker for the current hypotheses.
      have hCcomm_prime : Nat.Prime p → IsMulCommutative C := by
        intro hp
        have hCne : (Subgroup.center C).map C.subtype ≠ C := by
          intro hCeq'
          have hHC : H = C := by
            simpa [hCeq'] using hHeqZ
          exact hCeq hHC.symm
        have hCneZ : (Subgroup.center C) ≠ ⊤ := by
          intro htop
          apply hCne
          ext x
          constructor
          · intro hx
            rcases (Subgroup.mem_map).1 hx with ⟨y, hy, rfl⟩
            simp
          · intro hx
            refine (Subgroup.mem_map).2 ?_
            refine ⟨⟨x, hx⟩, ?_, rfl⟩
            simp [htop]
        have hC_pgroup : IsPGroup p C := h_pgroup.to_subgroup C
        have hQ_pgroup :
            IsPGroup p (C ⧸ Subgroup.center C) :=
          hC_pgroup.to_quotient (Subgroup.center C)
        haveI : Nontrivial (C ⧸ Subgroup.center C) :=
          (QuotientGroup.nontrivial_iff).2 hCneZ
        have hG_pgroup : IsPGroup p (ConjAct G) := h_pgroup.of_equiv ConjAct.toConjAct
        haveI : Fact p.Prime := ⟨hp⟩
        obtain ⟨n, hn0, hn⟩ :=
          hQ_pgroup.nontrivial_iff_card.mp
            (inferInstance : Nontrivial (C ⧸ Subgroup.center C))
        have hcard : p ∣ Nat.card (C ⧸ Subgroup.center C) := by
          exact hn.symm ▸ dvd_pow_self _ (ne_of_gt hn0)
        have hfixed_one :
            (1 : C ⧸ Subgroup.center C) ∈
              MulAction.fixedPoints (ConjAct G) (C ⧸ Subgroup.center C) := by
          intro x
          calc
            x • (1 : C ⧸ Subgroup.center C)
                = (QuotientGroup.mk (x • (1 : C)) : C ⧸ Subgroup.center C) := by
                  simpa using
                    (MulAction.Quotient.smul_mk
                      (H := Subgroup.center C) (b := x) (a := (1 : C)))
            _ = (QuotientGroup.mk (1 : C) : C ⧸ Subgroup.center C) := by
                  simp
            _ = (1 : C ⧸ Subgroup.center C) := rfl
        obtain ⟨z, hz_fixed, hz_ne⟩ :=
          hG_pgroup.exists_fixed_point_of_prime_dvd_card_of_fixed_point
            (α := C ⧸ Subgroup.center C) hcard hfixed_one
        let x : C := z.out
        have hz_mk : (QuotientGroup.mk (z.out) : C ⧸ Subgroup.center C) = z := by
          simp
        have hz_mk' : (QuotientGroup.mk x : C ⧸ Subgroup.center C) = z := by
          simp [x, hz_mk]
        have hx_not_center : (x : C) ∉ Subgroup.center C := by
          intro hx
          have : (QuotientGroup.mk x : C ⧸ Subgroup.center C) = 1 :=
            (QuotientGroup.eq_one_iff (x := (x : C))).2 hx
          have : 1 = z := by
            simpa [hz_mk'] using this.symm
          exact hz_ne this
        have hx_comm : ∀ g : G, ((ConjAct.toConjAct g) • x) / x ∈ Subgroup.center C := by
          intro g
          have hz_fixed' : ∀ g' : ConjAct G, g' • z = z :=
            (MulAction.mem_fixedPoints).1 hz_fixed
          have hz_eq : (ConjAct.toConjAct g) • z = z :=
            hz_fixed' (ConjAct.toConjAct g)
          have hz_eq' :
              (ConjAct.toConjAct g) • (QuotientGroup.mk x : C ⧸ Subgroup.center C) =
                QuotientGroup.mk x := by
            simpa [hz_mk'] using hz_eq
          have hz_eq'' :
              (QuotientGroup.mk ((ConjAct.toConjAct g) • x) :
                  C ⧸ Subgroup.center C) = QuotientGroup.mk x := by
            simpa [MulAction.Quotient.smul_mk] using hz_eq'
          exact
            (QuotientGroup.eq_iff_div_mem (N := Subgroup.center C)
              (x := (ConjAct.toConjAct g) • x) (y := x)).1 hz_eq''
        have hx_not_H : x.1 ∉ H := by
          intro hxH
          have hxH' : x.1 ∈ (Subgroup.center C).map C.subtype := by
            simpa [hHeqZ] using hxH
          rcases
              (Subgroup.mem_map (f := C.subtype) (K := Subgroup.center C) (y := x.1)).1 hxH'
            with ⟨y, hy, hyx⟩
          have hxy : (y : C) = x := by
            apply Subtype.ext
            simpa using hyx
          exact hx_not_center (by simpa [hxy] using hy)
        let K : Subgroup G := Subgroup.closure ((H : Set G) ∪ {x.1})
        have hHleK : H ≤ K := by
          intro h hh
          exact Subgroup.subset_closure (Or.inl hh)
        have hxK : x.1 ∈ K := by
          exact Subgroup.subset_closure (Or.inr rfl)
        have hKcomm : IsMulCommutative K := by
          have hxC : x.1 ∈ Subgroup.centralizer (H : Set G) := x.property
          exact abelian_closure_union_of_centralizer H hxC h_comm
        have hKnormal : K.Normal := by
          refine ⟨?conj⟩
          intro y hy g
          refine
            Subgroup.closure_induction
              (p := fun y hy => g * y * g⁻¹ ∈ K) ?mem ?one ?mul ?inv hy
          · intro y hy
            rcases hy with hy | hy
            · have hy' : g * y * g⁻¹ ∈ H := h_normal.conj_mem y hy g
              exact Subgroup.subset_closure (Or.inl hy')
            · have hcomm' :
                  (g * x.1 * g⁻¹ * x.1⁻¹ : G) ∈ (Subgroup.center C).map C.subtype := by
                exact Subgroup.mem_map_of_mem C.subtype (by
                  simpa [ConjAct.smul_def, div_eq_mul_inv, mul_assoc] using hx_comm g)
              have hy' : y = x.1 := by
                simpa using hy
              have hcomm : g * x.1 * g⁻¹ * x.1⁻¹ ∈ H := by
                simpa [hHeqZ] using hcomm'
              have hcommK : g * x.1 * g⁻¹ * x.1⁻¹ ∈ K := hHleK hcomm
              have hmul : (g * x.1 * g⁻¹ * x.1⁻¹) * x.1 ∈ K :=
                Subgroup.mul_mem K hcommK hxK
              simpa [hy', mul_assoc] using hmul
          · simp
          · intro a b ha hb ha' hb'
            simpa [mul_assoc] using Subgroup.mul_mem K ha' hb'
          · intro a ha ha'
            simpa [mul_assoc] using Subgroup.inv_mem K ha'
        have hKeq : H = K := h_maximal_normal_abelian K hKnormal hKcomm hHleK
        have hx_in_H : x.1 ∈ H := by
          simpa [hKeq] using hxK
        exact (hx_not_H hx_in_H).elim
      exact hCcomm_prime hp
  -- The earlier facts are kept for the intended maximality argument.
  simpa [C] using hCcomm

lemma centralizer_le_of_maximal_normal_abelian_in_pgroup
    (p : ℕ) (G : Type) [Group G] [Finite G] (h_pgroup : IsPGroup p G) (hp : p.Prime)
    (H : Subgroup G) (h_normal : H.Normal) (h_comm : IsMulCommutative H)
    (h_maximal_normal_abelian : ∀ (K : Subgroup G), K.Normal → IsMulCommutative K → H ≤ K → H = K) :
    Subgroup.centralizer (H : Set G) ≤ H := by
  have hHleC : H ≤ Subgroup.centralizer (H : Set G) :=
    (Subgroup.le_centralizer_iff_isMulCommutative).2 h_comm
  have hCnormal : (Subgroup.centralizer (H : Set G)).Normal := by
    infer_instance
  have hCcomm :
      IsMulCommutative (Subgroup.centralizer (H : Set G)) :=
    centralizer_isMulCommutative_of_maximal_normal_abelian_in_pgroup
      p G h_pgroup hp H h_normal h_comm h_maximal_normal_abelian
  have hHeqC : H = Subgroup.centralizer (H : Set G) :=
    h_maximal_normal_abelian _ hCnormal hCcomm hHleC
  exact le_of_eq hHeqC.symm

theorem maximal_abelian_normal_subgroup_of_p_group_is_maximal_abelian_subgroup
    (p : ℕ) (hp : p.Prime) (G : Type) [Group G] [Finite G] (h_pgroup : IsPGroup p G)
    (H : Subgroup G) (h_normal : H.Normal) (h_comm : IsMulCommutative H)
    (h_maximal_normal_abelian : ∀ (K : Subgroup G), K.Normal → IsMulCommutative K → H ≤ K → H = K) :
    ∀ (K : Subgroup G), IsMulCommutative K → H ≤ K → H = K := by
  intro K hKcomm hHK
  -- Key missing step: in a finite p-group, an abelian subgroup containing a maximal normal abelian
  -- subgroup is itself normal.
  have hKnormal : K.Normal := by
    have hKleC : K ≤ Subgroup.centralizer (H : Set G) :=
      subgroup_le_centralizer_of_le_and_comm hHK hKcomm
    have hC_le : Subgroup.centralizer (H : Set G) ≤ H :=
      centralizer_le_of_maximal_normal_abelian_in_pgroup
        p G h_pgroup hp H h_normal h_comm h_maximal_normal_abelian
    have hKleH : K ≤ H := le_trans hKleC hC_le
    have hKH : K = H := le_antisymm hKleH hHK
    simpa [hKH] using h_normal
  exact h_maximal_normal_abelian K hKnormal hKcomm hHK
