import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.

/-- The ideal generated by `P ^ k` is contained in the ideal generated by `P` when `1 <= k`. -/
lemma ideal_span_pow_le_span {F : Type*} [CommSemiring F] (P : Polynomial F) {k : Nat}
    (hk : 1 <= k) :
    Ideal.span ({P ^ k} : Set (Polynomial F)) <= Ideal.span ({P} : Set (Polynomial F)) := by
  refine Ideal.span_le.2 ?_
  intro x hx
  rcases Set.mem_singleton_iff.mp hx with rfl
  have hk0 : k ≠ 0 := by
    exact Nat.ne_of_gt (Nat.lt_of_lt_of_le (Nat.succ_pos 0) hk)
  rcases Nat.exists_eq_succ_of_ne_zero hk0 with ⟨m, rfl⟩
  refine Ideal.mem_span_singleton'.2 ?_
  refine ⟨P ^ m, ?_⟩
  simp [pow_succ, mul_comm, mul_left_comm, mul_assoc]

noncomputable section

/-- Helper for n000004: the ideal `(P^k)` in `F[X]`. -/
abbrev helperFor_n000004_polynomialPowerIdeal (F : Type*) [Field F] (P : Polynomial F) (k : ℕ) :
    Ideal (Polynomial F) :=
  Ideal.span ({P ^ k} : Set (Polynomial F))

/-- Helper for n000004: the quotient ring `F[X]/(P^k)`. -/
abbrev helperFor_n000004_polynomialPowerQuotient (F : Type*) [Field F] (P : Polynomial F) (k : ℕ) :=
  (Polynomial F) ⧸ helperFor_n000004_polynomialPowerIdeal F P k

/-- Helper for n000004: the class of `P` in `F[X]/(P^k)`. -/
abbrev helperFor_n000004_polynomialPowerQuotientP (F : Type*) [Field F] (P : Polynomial F) (k : ℕ) :
    helperFor_n000004_polynomialPowerQuotient F P k :=
  Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k) P

/-- Helper for n000004: the class of `X` in `F[X]/(P^k)`. -/
abbrev helperFor_n000004_polynomialPowerQuotientX (F : Type*) [Field F] (P : Polynomial F) (k : ℕ) :
    helperFor_n000004_polynomialPowerQuotient F P k :=
  Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k) Polynomial.X

/-- Helper for n000004: evaluation at `Xbar` equals the quotient map. -/
lemma helperFor_n000004_eval₂_Xbar_eq_mk
    (F : Type*) [Field F] (P : Polynomial F) (k : ℕ) (f : Polynomial F) :
    Polynomial.eval₂ (algebraMap F (helperFor_n000004_polynomialPowerQuotient F P k))
        (helperFor_n000004_polynomialPowerQuotientX F P k) f =
      Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k) f := by
  let I : Ideal (Polynomial F) := helperFor_n000004_polynomialPowerIdeal F P k
  have h :=
    (Polynomial.eval₂_algebraMap_X (p := f) (f := Ideal.Quotient.mkₐ F I))
  simpa [helperFor_n000004_polynomialPowerQuotientX,
    helperFor_n000004_polynomialPowerIdeal, Ideal.Quotient.mkₐ_eq_mk] using h

/-- Helper for n000004: the class of `P ^ k` is zero in the quotient by `(P ^ k)`. -/
lemma helperFor_n000004_mk_P_pow_eq_zero
    {F : Type*} [Field F] {P : Polynomial F} {k : ℕ} :
    Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k) (P ^ k) = 0 := by
  rw [Ideal.Quotient.eq_zero_iff_mem]
  refine Ideal.subset_span ?_
  simp

/-- Helper for n000004: the class of `P` is nilpotent in the quotient by `(P ^ k)`. -/
lemma helperFor_n000004_isNilpotent_mk_P
    {F : Type*} [Field F] {P : Polynomial F} {k : ℕ} :
    IsNilpotent
      (Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k) P) := by
  refine ⟨k, ?_⟩
  rw [← (Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k)).map_pow P k]
  exact helperFor_n000004_mk_P_pow_eq_zero (P := P) (k := k)

/-- Helper for n000004: nilpotence of the class of `A * P` in the quotient by `(P ^ k)`. -/
lemma helperFor_n000004_isNilpotent_mk_mul_left
    {F : Type*} [Field F] {P : Polynomial F} {k : ℕ} (A : Polynomial F) :
    IsNilpotent
      (Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k) (A * P)) := by
  let I : Ideal (Polynomial F) := helperFor_n000004_polynomialPowerIdeal F P k
  have hnilP : IsNilpotent (Ideal.Quotient.mk I P) := by
    change IsNilpotent
      (Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k) P)
    exact helperFor_n000004_isNilpotent_mk_P (P := P) (k := k)
  rcases hnilP with ⟨m, hm⟩
  refine ⟨m, ?_⟩
  have hmul :
      Ideal.Quotient.mk I (A * P) =
        Ideal.Quotient.mk I A * Ideal.Quotient.mk I P := by
    simpa using (Ideal.Quotient.mk I).map_mul A P
  calc
    (Ideal.Quotient.mk I (A * P)) ^ m =
        (Ideal.Quotient.mk I A * Ideal.Quotient.mk I P) ^ m := by
          simpa [hmul]
    _ = (Ideal.Quotient.mk I A) ^ m * (Ideal.Quotient.mk I P) ^ m := by
          simpa using (mul_pow (Ideal.Quotient.mk I A) (Ideal.Quotient.mk I P) m)
    _ = (Ideal.Quotient.mk I A) ^ m * 0 := by
          simp [hm]
    _ = 0 := by
          simp

/-- Helper for n000004: Bezout identity transported to the quotient ring. -/
lemma helperFor_n000004_bezout_identity_in_quotient
    {F : Type*} [Field F] {P A B : Polynomial F} {k : ℕ}
    (hAB : A * P + B * Polynomial.derivative P = 1) :
    (Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k) B) *
        (Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k)
          (Polynomial.derivative P))
      = 1 -
        (Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k)
          (A * P)) := by
  let I : Ideal (Polynomial F) := helperFor_n000004_polynomialPowerIdeal F P k
  have hAB' :
      Ideal.Quotient.mk I (A * P + B * Polynomial.derivative P) =
        Ideal.Quotient.mk I (1 : Polynomial F) := by
    exact congrArg (Ideal.Quotient.mk I) hAB
  rw [(Ideal.Quotient.mk I).map_add, (Ideal.Quotient.mk I).map_one] at hAB'
  have hAB'' :
      Ideal.Quotient.mk I (B * Polynomial.derivative P) + Ideal.Quotient.mk I (A * P) =
        (1 : Polynomial F ⧸ I) := by
    calc
      Ideal.Quotient.mk I (B * Polynomial.derivative P) + Ideal.Quotient.mk I (A * P) =
          Ideal.Quotient.mk I (A * P) + Ideal.Quotient.mk I (B * Polynomial.derivative P) := by
            exact add_comm _ _
      _ = (1 : Polynomial F ⧸ I) := hAB'
  have hsub :
      Ideal.Quotient.mk I (B * Polynomial.derivative P) =
        (1 : Polynomial F ⧸ I) - Ideal.Quotient.mk I (A * P) := by
    exact (eq_sub_iff_add_eq).2 hAB''
  calc
    (Ideal.Quotient.mk I B) * (Ideal.Quotient.mk I (Polynomial.derivative P)) =
        Ideal.Quotient.mk I (B * Polynomial.derivative P) := by
          simpa using
            ((Ideal.Quotient.mk I).map_mul B (Polynomial.derivative P)).symm
    _ = 1 - Ideal.Quotient.mk I (A * P) := hsub

/-- Helper for n000004: derivative is a unit in the quotient by `(P ^ k)` under separability. -/
theorem helperFor_n000004_derivative_isUnit_quotient_span_pow
    {F : Type*} [Field F] {P : Polynomial F}
    (hsep : IsCoprime P (Polynomial.derivative P)) {k : ℕ} (hk : 1 ≤ k) :
    IsUnit
      (Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k)
        (Polynomial.derivative P)) := by
  rcases hsep with ⟨A, B, hAB⟩
  let I : Ideal (Polynomial F) := helperFor_n000004_polynomialPowerIdeal F P k
  change IsUnit (Ideal.Quotient.mk I (Polynomial.derivative P))
  have hbez :
      (Ideal.Quotient.mk I B) * (Ideal.Quotient.mk I (Polynomial.derivative P)) =
        1 - Ideal.Quotient.mk I (A * P) := by
    exact
      helperFor_n000004_bezout_identity_in_quotient (P := P) (A := A) (B := B) (k := k) hAB
  have hnil : IsNilpotent (Ideal.Quotient.mk I (A * P)) := by
    exact helperFor_n000004_isNilpotent_mk_mul_left (P := P) (k := k) A
  have hunit_one_sub : IsUnit (1 - Ideal.Quotient.mk I (A * P)) :=
    IsNilpotent.isUnit_one_sub hnil
  have hunit_mul :
      IsUnit ((Ideal.Quotient.mk I B) * (Ideal.Quotient.mk I (Polynomial.derivative P))) := by
    rw [hbez]
    exact hunit_one_sub
  exact isUnit_of_mul_isUnit_right hunit_mul

/-- Helper for n000004: a multiple of `Pbar^n` lies in the ideal `(Pbar)` when `1 ≤ n`. -/
lemma helperFor_n000004_mul_pow_mem_span_P
    (F : Type*) [Field F] (P : Polynomial F) (k n : ℕ)
    (hn1 : 1 ≤ n) (c : helperFor_n000004_polynomialPowerQuotient F P k) :
    c * (helperFor_n000004_polynomialPowerQuotientP F P k) ^ n ∈
      Ideal.span ({helperFor_n000004_polynomialPowerQuotientP F P k} :
        Set (helperFor_n000004_polynomialPowerQuotient F P k)) := by
  have hn0 : n ≠ 0 := by
    exact Nat.ne_of_gt (Nat.lt_of_lt_of_le (Nat.succ_pos 0) hn1)
  obtain ⟨m, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hn0
  refine Ideal.mem_span_singleton'.2 ?_
  refine ⟨c * (helperFor_n000004_polynomialPowerQuotientP F P k) ^ m, ?_⟩
  simp [pow_succ, mul_assoc]

/-- Helper for n000004: the square of `c * Pbar^n` lies in the ideal `(Pbar^(n+1))`. -/
lemma helperFor_n000004_sq_mul_pow_mem_span_succ
    (F : Type*) [Field F] (P : Polynomial F) (k n : ℕ)
    (hn1 : 1 ≤ n) (c : helperFor_n000004_polynomialPowerQuotient F P k) :
    (c * (helperFor_n000004_polynomialPowerQuotientP F P k) ^ n) ^ 2 ∈
      Ideal.span ({(helperFor_n000004_polynomialPowerQuotientP F P k) ^ (n + 1)} :
        Set (helperFor_n000004_polynomialPowerQuotient F P k)) := by
  have hn0 : n ≠ 0 := by
    exact Nat.ne_of_gt (Nat.lt_of_lt_of_le (Nat.succ_pos 0) hn1)
  obtain ⟨m, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hn0
  refine Ideal.mem_span_singleton'.2 ?_
  refine ⟨c ^ 2 * (helperFor_n000004_polynomialPowerQuotientP F P k) ^ m, ?_⟩
  calc
    (c ^ 2 * (helperFor_n000004_polynomialPowerQuotientP F P k) ^ m) *
        (helperFor_n000004_polynomialPowerQuotientP F P k) ^ (m + 2)
        =
        c ^ 2 *
          ((helperFor_n000004_polynomialPowerQuotientP F P k) ^ m *
            (helperFor_n000004_polynomialPowerQuotientP F P k) ^ (m + 2)) := by
          simp [mul_assoc]
    _ =
        c ^ 2 *
          (helperFor_n000004_polynomialPowerQuotientP F P k) ^ (m + (m + 2)) := by
          rw [← pow_add]
    _ = c ^ 2 * (helperFor_n000004_polynomialPowerQuotientP F P k) ^ (2 * (m + 1)) := by
          have hmn : m + (m + 2) = 2 * (m + 1) := by
            simp [two_mul, Nat.add_left_comm, Nat.add_comm]
          simp [hmn]
    _ = c ^ 2 * (helperFor_n000004_polynomialPowerQuotientP F P k) ^ ((m + 1) * 2) := by
          simp [Nat.mul_comm]
    _ = c ^ 2 * ((helperFor_n000004_polynomialPowerQuotientP F P k) ^ (m + 1)) ^ 2 := by
          simp [pow_mul]
    _ = (c * (helperFor_n000004_polynomialPowerQuotientP F P k) ^ (m + 1)) ^ 2 := by
          symm
          simp [mul_pow]

/-- Helper for n000004: choose `c` to cancel `a` using a unit `d`. -/
lemma helperFor_n000004_cancel_choice {R : Type*} [CommRing R] (a d : R) (hd : IsUnit d) :
    ∃ c : R, a + c * d = 0 := by
  rcases hd with ⟨u, rfl⟩
  refine ⟨-a * (u⁻¹ : Units R), ?_⟩
  simp [mul_assoc, Units.inv_mul]

/-- Helper for n000004: factor a right multiplier in a simple sum. -/
lemma helperFor_n000004_factor_right {R : Type*} [CommRing R] (a b c x : R) :
    a * x + b * (c * x) = (a + c * b) * x := by
  calc
    a * x + b * (c * x) = a * x + (b * c) * x := by
      rw [← mul_assoc]
    _ = (a + b * c) * x := by
      symm
      rw [add_mul]
    _ = (a + c * b) * x := by
      simp [mul_comm]

set_option maxHeartbeats 400000 in
/-- Helper for n000004: one-step lifting in the `(P^k)`-quotient. -/
theorem helperFor_n000004_one_step_lifting
    (F : Type*) [Field F] (P : Polynomial F) (k : ℕ) (hk : 2 ≤ k)
    (n : ℕ) (hn1 : 1 ≤ n) (hnk : n < k)
    (y : helperFor_n000004_polynomialPowerQuotient F P k)
    (hyx :
      y - helperFor_n000004_polynomialPowerQuotientX F P k ∈
        Ideal.span ({helperFor_n000004_polynomialPowerQuotientP F P k} :
          Set (helperFor_n000004_polynomialPowerQuotient F P k)))
    (hyP :
      Polynomial.eval₂ (algebraMap F (helperFor_n000004_polynomialPowerQuotient F P k)) y P ∈
        Ideal.span ({(helperFor_n000004_polynomialPowerQuotientP F P k) ^ n} :
          Set (helperFor_n000004_polynomialPowerQuotient F P k)))
    (hunit :
      IsUnit
        (Polynomial.eval₂ (algebraMap F (helperFor_n000004_polynomialPowerQuotient F P k)) y
          (Polynomial.derivative P))) :
    ∃ c : helperFor_n000004_polynomialPowerQuotient F P k,
      let z : helperFor_n000004_polynomialPowerQuotient F P k :=
        y + c * (helperFor_n000004_polynomialPowerQuotientP F P k) ^ n
      z - y ∈
          Ideal.span ({helperFor_n000004_polynomialPowerQuotientP F P k} :
            Set (helperFor_n000004_polynomialPowerQuotient F P k)) ∧
        Polynomial.eval₂ (algebraMap F (helperFor_n000004_polynomialPowerQuotient F P k)) z P ∈
          Ideal.span ({(helperFor_n000004_polynomialPowerQuotientP F P k) ^ (n + 1)} :
            Set (helperFor_n000004_polynomialPowerQuotient F P k)) :=
  by
    classical
    have _ := hk
    have _ := hnk
    have _ := hyx
    let Pbar : helperFor_n000004_polynomialPowerQuotient F P k :=
      helperFor_n000004_polynomialPowerQuotientP F P k
    have hyP' :
        Polynomial.aeval y P ∈
          Ideal.span ({Pbar ^ n} : Set (helperFor_n000004_polynomialPowerQuotient F P k)) := by
      simpa [Polynomial.aeval_def, Pbar] using hyP
    have hunit' :
        IsUnit (Polynomial.aeval y (Polynomial.derivative P)) := by
      simpa [Polynomial.aeval_def] using hunit
    obtain ⟨a, ha⟩ := (Ideal.mem_span_singleton'.1 hyP')
    have ha' : Polynomial.aeval y P = a * Pbar ^ n := by
      exact ha.symm
    obtain ⟨c, hc⟩ :=
      helperFor_n000004_cancel_choice a
        (Polynomial.aeval y (Polynomial.derivative P)) hunit'
    refine ⟨c, ?_⟩
    dsimp
    constructor
    · have hmem :
          c * Pbar ^ n ∈
            Ideal.span ({Pbar} : Set (helperFor_n000004_polynomialPowerQuotient F P k)) :=
        helperFor_n000004_mul_pow_mem_span_P F P k n hn1 c
      have hz : (y + c * Pbar ^ n) - y = c * Pbar ^ n := by
        simp [add_sub_cancel_left]
      simpa [hz, Pbar] using hmem
    · let I : Ideal (helperFor_n000004_polynomialPowerQuotient F P k) :=
        Ideal.span ({Pbar ^ (n + 1)} : Set (helperFor_n000004_polynomialPowerQuotient F P k))
      let S := (helperFor_n000004_polynomialPowerQuotient F P k) ⧸ I
      let π : helperFor_n000004_polynomialPowerQuotient F P k →ₐ[F] S :=
        Ideal.Quotient.mkₐ F I
      have hmemsq : (c * Pbar ^ n) ^ 2 ∈ I := by
        have h :=
          helperFor_n000004_sq_mul_pow_mem_span_succ F P k n hn1 c
        simpa [I, Pbar] using h
      have hsq : (π (c * Pbar ^ n)) ^ 2 = 0 := by
        have hzero : π ((c * Pbar ^ n) ^ 2) = 0 := by
          change (Ideal.Quotient.mk I ((c * Pbar ^ n) ^ 2) = 0)
          exact (Ideal.Quotient.eq_zero_iff_mem).2 hmemsq
        calc
          (π (c * Pbar ^ n)) ^ 2 = π ((c * Pbar ^ n) ^ 2) := by
            symm
            exact map_pow π (c * Pbar ^ n) 2
          _ = 0 := hzero
      have h :=
        Polynomial.aeval_add_of_sq_eq_zero (p := P) (x := π y)
          (y := π (c * Pbar ^ n)) hsq
      have hzπ : π (y + c * Pbar ^ n) = π y + π (c * Pbar ^ n) := by
        exact
          (π : helperFor_n000004_polynomialPowerQuotient F P k →+* S).map_add y (c * Pbar ^ n)
      have hTaylor' :
          π (Polynomial.aeval (y + c * Pbar ^ n) P) =
            π (Polynomial.aeval y P) +
              π (Polynomial.aeval y (Polynomial.derivative P)) * π (c * Pbar ^ n) := by
        have h0 := h
        rw [← hzπ] at h0
        rw [Polynomial.aeval_algHom_apply π (y + c * Pbar ^ n) P] at h0
        rw [Polynomial.aeval_algHom_apply π y P] at h0
        rw [Polynomial.aeval_algHom_apply π y (Polynomial.derivative P)] at h0
        exact h0
      have hsum :
          a * Pbar ^ n +
            Polynomial.aeval y (Polynomial.derivative P) * (c * Pbar ^ n) = 0 := by
        have hfac :=
          helperFor_n000004_factor_right a
            (Polynomial.aeval y (Polynomial.derivative P)) c (Pbar ^ n)
        rw [hfac, hc]
        simp
      have hzero :
          π (a * Pbar ^ n +
            Polynomial.aeval y (Polynomial.derivative P) * (c * Pbar ^ n)) = 0 := by
        rw [hsum]
        simp
      have hzero' : π (Polynomial.aeval (y + c * Pbar ^ n) P) = 0 := by
        calc
          π (Polynomial.aeval (y + c * Pbar ^ n) P) =
              π (Polynomial.aeval y P) +
                π (Polynomial.aeval y (Polynomial.derivative P)) * π (c * Pbar ^ n) := hTaylor'
          _ = π (a * Pbar ^ n) +
              π (Polynomial.aeval y (Polynomial.derivative P)) * π (c * Pbar ^ n) := by
                simp [ha']
          _ = π (a * Pbar ^ n +
                Polynomial.aeval y (Polynomial.derivative P) * (c * Pbar ^ n)) := by
                symm
                calc
                  π (a * Pbar ^ n +
                      Polynomial.aeval y (Polynomial.derivative P) * (c * Pbar ^ n)) =
                      π (a * Pbar ^ n) +
                        π (Polynomial.aeval y (Polynomial.derivative P) * (c * Pbar ^ n)) := by
                    exact
                      (π : helperFor_n000004_polynomialPowerQuotient F P k →+* S).map_add
                        (a * Pbar ^ n)
                        (Polynomial.aeval y (Polynomial.derivative P) * (c * Pbar ^ n))
                  _ = π (a * Pbar ^ n) +
                      π (Polynomial.aeval y (Polynomial.derivative P)) * π (c * Pbar ^ n) := by
                    have hmul :=
                      (π : helperFor_n000004_polynomialPowerQuotient F P k →+* S).map_mul
                        (Polynomial.aeval y (Polynomial.derivative P))
                        (c * Pbar ^ n)
                    exact congrArg (fun t => π (a * Pbar ^ n) + t) hmul
          _ = 0 := hzero
      have hmem :
          Polynomial.aeval (y + c * Pbar ^ n) P ∈ I := by
        have hzero'' :
            Ideal.Quotient.mk I (Polynomial.aeval (y + c * Pbar ^ n) P) = 0 := by
          have hzero'' := hzero'
          rw [Ideal.Quotient.mkₐ_eq_mk] at hzero''
          exact hzero''
        exact (Ideal.Quotient.eq_zero_iff_mem).1 hzero''
      have hmem' :
          Polynomial.aeval (y + c * Pbar ^ n) P ∈
            Ideal.span ({Pbar ^ (n + 1)} : Set (helperFor_n000004_polynomialPowerQuotient F P k)) := by
        simpa [I] using hmem
      simpa [Polynomial.aeval_def, Pbar] using hmem'

/-- Helper for n000004: elements of a smaller ideal map to zero in the larger quotient. -/
lemma helperFor_n000004_mkₐ_eq_zero_of_mem
    {F : Type*} [CommRing F] {I J : Ideal (Polynomial F)} (hIJ : I ≤ J) :
    ∀ a : Polynomial F, a ∈ I → (Ideal.Quotient.mkₐ F J) a = 0 := by
  intro a ha
  have hmem : a ∈ J := hIJ ha
  have hzero : Ideal.Quotient.mk J a = 0 := (Ideal.Quotient.eq_zero_iff_mem).2 hmem
  simpa [Ideal.Quotient.mkₐ_eq_mk] using hzero

/-- Helper for n000004: a quotient algebra map agreeing on polynomials is canonical. -/
lemma helperFor_n000004_pi_eq_pi0
    {F : Type*} [CommRing F] {I J : Ideal (Polynomial F)} (hIJ : I ≤ J)
    (pi : AlgHom F ((Polynomial F) ⧸ I) ((Polynomial F) ⧸ J))
    (hpi : ∀ x : Polynomial F, pi (Ideal.Quotient.mk I x) = Ideal.Quotient.mk J x) :
    pi =
      Ideal.Quotient.liftₐ I (Ideal.Quotient.mkₐ F J)
        (helperFor_n000004_mkₐ_eq_zero_of_mem (I := I) (J := J) hIJ) := by
  apply (Ideal.Quotient.algHom_ext (I := I) (R₁ := F))
  apply AlgHom.ext
  intro x
  simp [Ideal.Quotient.liftₐ_comp, Ideal.Quotient.mkₐ_eq_mk, hpi x]

/-- Helper for n000004: if `P(y)=0`, then `aeval y` kills the ideal `(P)`. -/
lemma helperFor_n000004_aeval_mem_span_P_eq_zero
    {F : Type*} [CommRing F] {R : Type*} [CommRing R] [Algebra F R]
    {P : Polynomial F} {y : R} (hy : Polynomial.aeval y P = 0) :
    ∀ q : Polynomial F, q ∈ Ideal.span ({P} : Set (Polynomial F)) →
      (Polynomial.aeval y q : R) = 0 := by
  intro q hq
  rcases Ideal.mem_span_singleton'.1 hq with ⟨r, rfl⟩
  calc
    (Polynomial.aeval y (r * P) : R) =
        Polynomial.aeval y r * Polynomial.aeval y P := by
          simp
    _ = 0 := by
          simp [hy]

/-- Helper for n000004: unit of the derivative is stable under congruence modulo `(Pbar)`. -/
lemma helperFor_n000004_isUnit_aeval_derivative_of_congr
    {F : Type*} [Field F] (P : Polynomial F) {k : Nat}
    (y : helperFor_n000004_polynomialPowerQuotient F P k)
    (hyx :
      y - helperFor_n000004_polynomialPowerQuotientX F P k ∈
        Ideal.span ({helperFor_n000004_polynomialPowerQuotientP F P k} :
          Set (helperFor_n000004_polynomialPowerQuotient F P k)))
    (hu :
      IsUnit (Polynomial.aeval (helperFor_n000004_polynomialPowerQuotientX F P k)
        (Polynomial.derivative P))) :
    IsUnit (Polynomial.aeval y (Polynomial.derivative P)) := by
  classical
  let R := helperFor_n000004_polynomialPowerQuotient F P k
  let Pbar : R := helperFor_n000004_polynomialPowerQuotientP F P k
  let x : R := helperFor_n000004_polynomialPowerQuotientX F P k
  let M : Ideal R := Ideal.span ({Pbar} : Set R)
  have hyx' : y - x ∈ M := by
    simpa [R, Pbar, x, M] using hyx
  let π : R →ₐ[F] R ⧸ M := Ideal.Quotient.mkₐ F M
  have hxy : π y = π x := by
    have hmk :
        Ideal.Quotient.mk M y = Ideal.Quotient.mk M x := by
      exact (Ideal.Quotient.mk_eq_mk_iff_sub_mem (I := M) (x := y) (y := x)).2 hyx'
    simpa [π, Ideal.Quotient.mkₐ_eq_mk] using hmk
  have hderiv :
      π (Polynomial.aeval y (Polynomial.derivative P)) =
        π (Polynomial.aeval x (Polynomial.derivative P)) := by
    calc
      π (Polynomial.aeval y (Polynomial.derivative P)) =
          Polynomial.aeval (π y) (Polynomial.derivative P) := by
            symm
            simpa using
              (Polynomial.aeval_algHom_apply π y (Polynomial.derivative P))
      _ = Polynomial.aeval (π x) (Polynomial.derivative P) := by
            simpa [hxy]
      _ = π (Polynomial.aeval x (Polynomial.derivative P)) := by
            simpa using
              (Polynomial.aeval_algHom_apply π x (Polynomial.derivative P))
  have hmem :
      Polynomial.aeval y (Polynomial.derivative P) -
        Polynomial.aeval x (Polynomial.derivative P) ∈ M := by
    have hmk :
        Ideal.Quotient.mk M (Polynomial.aeval y (Polynomial.derivative P)) =
          Ideal.Quotient.mk M (Polynomial.aeval x (Polynomial.derivative P)) := by
      simpa [π, Ideal.Quotient.mkₐ_eq_mk] using hderiv
    exact
      (Ideal.Quotient.mk_eq_mk_iff_sub_mem (I := M)
        (x := Polynomial.aeval y (Polynomial.derivative P))
        (y := Polynomial.aeval x (Polynomial.derivative P))).1 hmk
  have hnilP : IsNilpotent Pbar := by
    change IsNilpotent
      (Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k) P)
    exact helperFor_n000004_isNilpotent_mk_P (P := P) (k := k)
  have hnil_diff :
      IsNilpotent
        (Polynomial.aeval y (Polynomial.derivative P) -
          Polynomial.aeval x (Polynomial.derivative P)) := by
    rcases Ideal.mem_span_singleton'.1 hmem with ⟨a, ha⟩
    rcases hnilP with ⟨m, hm⟩
    refine ⟨m, ?_⟩
    calc
      (Polynomial.aeval y (Polynomial.derivative P) -
          Polynomial.aeval x (Polynomial.derivative P)) ^ m =
          (a * Pbar) ^ m := by
            simpa [ha.symm]
      _ = a ^ m * Pbar ^ m := by
            simpa using (mul_pow a Pbar m)
      _ = a ^ m * 0 := by
            simp [hm]
      _ = 0 := by
            simp
  have hunit_sum :
      IsUnit
        (Polynomial.aeval x (Polynomial.derivative P) +
          (Polynomial.aeval y (Polynomial.derivative P) -
            Polynomial.aeval x (Polynomial.derivative P))) :=
    IsNilpotent.isUnit_add_left_of_commute hnil_diff hu (Commute.all _ _)
  have hsum :
      Polynomial.aeval x (Polynomial.derivative P) +
          (Polynomial.aeval y (Polynomial.derivative P) -
            Polynomial.aeval x (Polynomial.derivative P)) =
        Polynomial.aeval y (Polynomial.derivative P) := by
    calc
      Polynomial.aeval x (Polynomial.derivative P) +
          (Polynomial.aeval y (Polynomial.derivative P) -
            Polynomial.aeval x (Polynomial.derivative P)) =
          Polynomial.aeval x (Polynomial.derivative P) +
            Polynomial.aeval y (Polynomial.derivative P) -
            Polynomial.aeval x (Polynomial.derivative P) := by
              simp [sub_eq_add_neg, add_assoc]
      _ = Polynomial.aeval y (Polynomial.derivative P) := by
            simp [sub_eq_add_neg, add_assoc, add_comm, add_left_comm]
  simpa [hsum] using hunit_sum

/-- Helper for n000004: lift `Xbar` to a root of `P` in `F[X]/(P^k)` when `k >= 2`. -/
lemma helperFor_n000004_exists_lifted_root
    {F : Type*} [Field F] {P : Polynomial F} {k : Nat} (hk : 2 <= k)
    (hsep : IsCoprime P (Polynomial.derivative P)) :
    let R := helperFor_n000004_polynomialPowerQuotient F P k
    let Pbar : R := helperFor_n000004_polynomialPowerQuotientP F P k
    let x : R := helperFor_n000004_polynomialPowerQuotientX F P k
    ∃ y : R,
      y - x ∈ Ideal.span ({Pbar} : Set R) ∧
      Polynomial.aeval y P = 0 := by
  classical
  let R := helperFor_n000004_polynomialPowerQuotient F P k
  let Pbar : R := helperFor_n000004_polynomialPowerQuotientP F P k
  let x : R := helperFor_n000004_polynomialPowerQuotientX F P k
  let M : Ideal R := Ideal.span ({Pbar} : Set R)
  have hk1 : 1 <= k := le_trans (by decide) hk
  have hunit_mk :
      IsUnit
        (Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k)
          (Polynomial.derivative P)) :=
    helperFor_n000004_derivative_isUnit_quotient_span_pow (P := P) hsep (k := k) hk1
  have hx_eq :
      Polynomial.aeval x (Polynomial.derivative P) =
        Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k)
          (Polynomial.derivative P) := by
    simpa [Polynomial.aeval_def, x, helperFor_n000004_polynomialPowerQuotientX,
      helperFor_n000004_polynomialPowerIdeal] using
      (helperFor_n000004_eval₂_Xbar_eq_mk F P k (Polynomial.derivative P))
  have hunitx :
      IsUnit (Polynomial.aeval x (Polynomial.derivative P)) := by
    simpa [hx_eq] using hunit_mk
  have hprop :
      ∀ t : Nat, t < k →
        ∃ y : R,
          y - x ∈ M ∧
          Polynomial.eval₂ (algebraMap F R) y P ∈
            Ideal.span ({Pbar ^ (t + 1)} : Set R) := by
    intro t ht
    induction t with
    | zero =>
        refine ⟨x, ?_, ?_⟩
        · have hzero : (0 : R) ∈ M := Ideal.zero_mem M
          simpa using hzero
        · have hmemP : Pbar ∈ Ideal.span ({Pbar} : Set R) := by
            exact Ideal.subset_span (by simp)
          have hPeval : Polynomial.eval₂ (algebraMap F R) x P = Pbar := by
            simpa [x, Pbar, helperFor_n000004_polynomialPowerQuotientX,
              helperFor_n000004_polynomialPowerQuotientP,
              helperFor_n000004_polynomialPowerIdeal] using
              (helperFor_n000004_eval₂_Xbar_eq_mk F P k P)
          simpa [hPeval, pow_one] using hmemP
    | succ t ih =>
        have ht' : t < k := Nat.lt_of_succ_lt ht
        rcases ih ht' with ⟨y, hyx, hyP⟩
        have hyx' :
            y - helperFor_n000004_polynomialPowerQuotientX F P k ∈
              Ideal.span ({helperFor_n000004_polynomialPowerQuotientP F P k} :
                Set (helperFor_n000004_polynomialPowerQuotient F P k)) := by
          simpa [x, Pbar, M] using hyx
        have hyP' :
            Polynomial.eval₂ (algebraMap F R) y P ∈
              Ideal.span ({(helperFor_n000004_polynomialPowerQuotientP F P k) ^ (Nat.succ t)} :
                Set (helperFor_n000004_polynomialPowerQuotient F P k)) := by
          simpa [Pbar] using hyP
        have hunitx' :
            IsUnit
              (Polynomial.aeval (helperFor_n000004_polynomialPowerQuotientX F P k)
                (Polynomial.derivative P)) := by
          simpa [x] using hunitx
        have hunit' :
            IsUnit
              (Polynomial.eval₂ (algebraMap F R) y (Polynomial.derivative P)) := by
          have hunit'' :
              IsUnit (Polynomial.aeval y (Polynomial.derivative P)) :=
            helperFor_n000004_isUnit_aeval_derivative_of_congr (P := P) (k := k) (y := y)
              (hyx := hyx') (hu := hunitx')
          simpa [Polynomial.aeval_def] using hunit''
        have hn1 : 1 <= Nat.succ t := Nat.succ_le_succ (Nat.zero_le t)
        have hnk : Nat.succ t < k := ht
        rcases
          helperFor_n000004_one_step_lifting F P k hk (n := Nat.succ t) hn1 hnk y hyx' hyP' hunit'
          with ⟨c, hz⟩
        dsimp at hz
        let z : R := y + c * (helperFor_n000004_polynomialPowerQuotientP F P k) ^ (Nat.succ t)
        have hz_y :
            z - y ∈ M := by
          simpa [z, M, Pbar] using hz.1
        have hzP :
            Polynomial.eval₂ (algebraMap F R) z P ∈
              Ideal.span ({(helperFor_n000004_polynomialPowerQuotientP F P k) ^ (Nat.succ (Nat.succ t))} :
                Set (helperFor_n000004_polynomialPowerQuotient F P k)) := by
          simpa [z] using hz.2
        have hz_sum : (z - y) + (y - x) ∈ M := Ideal.add_mem M hz_y hyx
        have hz_eq : (z - y) + (y - x) = z - x := by
          simpa using (sub_add_sub_cancel z y x)
        have hz_x : z - x ∈ M := by
          simpa [hz_eq] using hz_sum
        refine ⟨z, hz_x, ?_⟩
        simpa [Pbar] using hzP
  obtain ⟨m, hk_eq⟩ := Nat.exists_eq_add_of_le' hk
  have ht : m + 1 < k := by
    have hlt : m + 1 < m + 2 := Nat.lt_succ_self (m + 1)
    simpa [hk_eq] using hlt
  rcases hprop (t := m + 1) ht with ⟨y, hyx, hyP⟩
  have hyP' :
      Polynomial.eval₂ (algebraMap F R) y P ∈
        Ideal.span ({Pbar ^ k} : Set R) := by
    simpa [hk_eq, Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using hyP
  have hPbar_pow_zero : (Pbar ^ k) = 0 := by
    have hPbar_pow :
        (Pbar ^ k) =
          Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k) (P ^ k) := by
      calc
        (Pbar ^ k) =
            (Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k) P) ^ k := by
              simp [Pbar, helperFor_n000004_polynomialPowerQuotientP]
        _ = Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k) (P ^ k) := by
              symm
              exact (Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k)).map_pow P k
    calc
      (Pbar ^ k) =
          Ideal.Quotient.mk (helperFor_n000004_polynomialPowerIdeal F P k) (P ^ k) := hPbar_pow
      _ = 0 := by
          simpa [helperFor_n000004_polynomialPowerIdeal] using
            (helperFor_n000004_mk_P_pow_eq_zero (P := P) (k := k))
  rcases Ideal.mem_span_singleton'.1 hyP' with ⟨a, ha⟩
  have hroot_eval : Polynomial.eval₂ (algebraMap F R) y P = 0 := by
    calc
      Polynomial.eval₂ (algebraMap F R) y P = a * Pbar ^ k := by
        exact ha.symm
      _ = 0 := by
        simp [hPbar_pow_zero]
  have hroot : Polynomial.aeval y P = 0 := by
    simpa [Polynomial.aeval_def] using hroot_eval
  exact ⟨y, hyx, hroot⟩

set_option maxHeartbeats 400000 in
/-- n000004: For a field `F`, an irreducible and separable polynomial `P`, and `k >= 1`, let
`R = F[X]/(P^k)` and `K = F[X]/(P)` with quotient map `pi`; there is an `F`-algebra section
`s : K -> R` such that `pi` composed with `s` is the identity on `K`. -/
theorem exists_alg_section_quotient_map
    {F : Type*} [Field F] {P : Polynomial F} (hPirr : Irreducible P) (hPsep : P.Separable)
    {k : Nat} (hk : 1 <= k) :
    let I : Ideal (Polynomial F) := Ideal.span ({P ^ k} : Set (Polynomial F))
    let J : Ideal (Polynomial F) := Ideal.span ({P} : Set (Polynomial F))
    let R := (Polynomial F) ⧸ I
    let K := (Polynomial F) ⧸ J
    forall pi : AlgHom F R K,
      (forall x : Polynomial F, pi (Ideal.Quotient.mk I x) = Ideal.Quotient.mk J x) ->
      Exists fun s : AlgHom F K R => AlgHom.comp pi s = AlgHom.id F K := by
  classical
  dsimp
  intro pi hpi
  let I : Ideal (Polynomial F) := Ideal.span ({P ^ k} : Set (Polynomial F))
  let J : Ideal (Polynomial F) := Ideal.span ({P} : Set (Polynomial F))
  let R := (Polynomial F) ⧸ I
  let K := (Polynomial F) ⧸ J
  have hIJ : I ≤ J := ideal_span_pow_le_span P hk
  let pi0 : AlgHom F R K :=
    Ideal.Quotient.liftₐ I (Ideal.Quotient.mkₐ F J)
      (helperFor_n000004_mkₐ_eq_zero_of_mem (I := I) (J := J) hIJ)
  have hpi_eq :
      pi = pi0 :=
    helperFor_n000004_pi_eq_pi0 (I := I) (J := J) hIJ pi hpi
  by_cases hk1 : k = 1
  · subst hk1
    have hIeq : I = J := by
      simp [I, J, pow_one]
    have hJI : J ≤ I := by
      simpa [hIeq] using (le_rfl : I ≤ I)
    let s : AlgHom F K R :=
      Ideal.Quotient.liftₐ J (Ideal.Quotient.mkₐ F I)
        (helperFor_n000004_mkₐ_eq_zero_of_mem (I := J) (J := I) hJI)
    have hs_comp :
        s.comp (Ideal.Quotient.mkₐ F J) = Ideal.Quotient.mkₐ F I := by
      simpa [s] using
        (Ideal.Quotient.liftₐ_comp (I := J) (f := Ideal.Quotient.mkₐ F I)
          (helperFor_n000004_mkₐ_eq_zero_of_mem (I := J) (J := I) hJI))
    have hpi0_comp :
        pi0.comp (Ideal.Quotient.mkₐ F I) = Ideal.Quotient.mkₐ F J := by
      simpa [pi0] using
        (Ideal.Quotient.liftₐ_comp (I := I) (f := Ideal.Quotient.mkₐ F J)
          (helperFor_n000004_mkₐ_eq_zero_of_mem (I := I) (J := J) hIJ))
    have hpi0_comp_s : AlgHom.comp pi0 s = AlgHom.id F K := by
      apply (Ideal.Quotient.algHom_ext (I := J) (R₁ := F))
      calc
        (pi0.comp s).comp (Ideal.Quotient.mkₐ F J) =
            pi0.comp (s.comp (Ideal.Quotient.mkₐ F J)) := by
              simp [AlgHom.comp_assoc]
        _ = pi0.comp (Ideal.Quotient.mkₐ F I) := by
              simpa [hs_comp]
        _ = Ideal.Quotient.mkₐ F J := by
              simpa [hpi0_comp]
        _ = (AlgHom.id F K).comp (Ideal.Quotient.mkₐ F J) := by
              simp
    refine ⟨s, ?_⟩
    simpa [hpi_eq] using hpi0_comp_s
  · have hk2 : 2 <= k := by
      have hklt : 1 < k := lt_of_le_of_ne hk (Ne.symm hk1)
      simpa using hklt
    have hsep : IsCoprime P (Polynomial.derivative P) := by
      simpa [Polynomial.separable_def] using hPsep
    have hy :
        let R := helperFor_n000004_polynomialPowerQuotient F P k
        let Pbar : R := helperFor_n000004_polynomialPowerQuotientP F P k
        let x : R := helperFor_n000004_polynomialPowerQuotientX F P k
        ∃ y : R,
          y - x ∈ Ideal.span ({Pbar} : Set R) ∧
          Polynomial.aeval y P = 0 :=
      helperFor_n000004_exists_lifted_root (P := P) (k := k) hk2 hsep
    dsimp at hy
    rcases hy with ⟨y, hyx, hyP⟩
    let Pbar : R := helperFor_n000004_polynomialPowerQuotientP F P k
    let x : R := helperFor_n000004_polynomialPowerQuotientX F P k
    let M : Ideal R := Ideal.span ({Pbar} : Set R)
    have hy_ideal :
        ∀ q : Polynomial F, q ∈ J → (Polynomial.aeval y q : R) = 0 :=
      helperFor_n000004_aeval_mem_span_P_eq_zero (P := P) (y := y) hyP
    let s : AlgHom F K R := Ideal.Quotient.liftₐ J (Polynomial.aeval y) hy_ideal
    have hs_comp :
        s.comp (Ideal.Quotient.mkₐ F J) = Polynomial.aeval y := by
      simpa [s] using
        (Ideal.Quotient.liftₐ_comp (I := J) (f := Polynomial.aeval y) hy_ideal)
    have hpi0_comp :
        pi0.comp (Ideal.Quotient.mkₐ F I) = Ideal.Quotient.mkₐ F J := by
      simpa [pi0] using
        (Ideal.Quotient.liftₐ_comp (I := I) (f := Ideal.Quotient.mkₐ F J)
          (helperFor_n000004_mkₐ_eq_zero_of_mem (I := I) (J := J) hIJ))
    have hpi0x :
        pi0 x = Ideal.Quotient.mk J Polynomial.X := by
      have hpi0x' :=
        congrArg (fun f : Polynomial F →ₐ[F] K => f Polynomial.X) hpi0_comp
      simpa [x, Ideal.Quotient.mkₐ_eq_mk] using hpi0x'
    have hPmem : P ∈ J := Ideal.subset_span (by simp)
    have hmkP : Ideal.Quotient.mk J P = 0 := (Ideal.Quotient.eq_zero_iff_mem).2 hPmem
    have hpi0P :
        pi0 (Ideal.Quotient.mk I P) = Ideal.Quotient.mk J P := by
      have hpi0P' :=
        congrArg (fun f : Polynomial F →ₐ[F] K => f P) hpi0_comp
      simpa [Ideal.Quotient.mkₐ_eq_mk] using hpi0P'
    have hpi0_Pbar : pi0 Pbar = 0 := by
      have hpi0P0 : pi0 (Ideal.Quotient.mk I P) = 0 := by
        simpa [hmkP] using hpi0P
      simpa [Pbar, helperFor_n000004_polynomialPowerQuotientP] using hpi0P0
    rcases Ideal.mem_span_singleton'.1 hyx with ⟨a, ha⟩
    have ha' : y - x = a * Pbar := by
      simpa [Pbar] using ha.symm
    have hpi0_sub : pi0 y - pi0 x = pi0 a * pi0 Pbar := by
      calc
        pi0 y - pi0 x = pi0 (y - x) := by
          symm
          simpa using (map_sub pi0 y x)
        _ = pi0 (a * Pbar) := by
          exact congrArg pi0 ha'
        _ = pi0 a * pi0 Pbar := by
          simpa using map_mul pi0 a Pbar
    have hpi0_sub_zero : pi0 y - pi0 x = 0 := by
      simpa [hpi0_Pbar] using hpi0_sub
    have hpi0y : pi0 y = Ideal.Quotient.mk J Polynomial.X := by
      have hpi0yx : pi0 y = pi0 x := sub_eq_zero.mp hpi0_sub_zero
      simpa [hpi0x] using hpi0yx
    have hpi0_aeval : pi0.comp (Polynomial.aeval y) = Ideal.Quotient.mkₐ F J := by
      apply AlgHom.ext
      intro f
      calc
        pi0 (Polynomial.aeval y f) = Polynomial.aeval (pi0 y) f := by
          simpa using (Polynomial.aeval_algHom_apply pi0 y f).symm
        _ = Polynomial.aeval (Ideal.Quotient.mk J Polynomial.X) f := by
          exact congrArg (fun t => Polynomial.aeval t f) hpi0y
        _ = Ideal.Quotient.mk J f := by
          have h :=
            (Polynomial.eval₂_algebraMap_X (p := f) (f := Ideal.Quotient.mkₐ F J))
          simpa [Polynomial.aeval_def, Ideal.Quotient.mkₐ_eq_mk] using h
    have hpi0_comp_s : AlgHom.comp pi0 s = AlgHom.id F K := by
      apply (Ideal.Quotient.algHom_ext (I := J) (R₁ := F))
      calc
        (pi0.comp s).comp (Ideal.Quotient.mkₐ F J) =
            pi0.comp (s.comp (Ideal.Quotient.mkₐ F J)) := by
              simp [AlgHom.comp_assoc]
        _ = pi0.comp (Polynomial.aeval y) := by
              simpa [hs_comp]
        _ = Ideal.Quotient.mkₐ F J := by
              simpa [hpi0_aeval]
        _ = (AlgHom.id F K).comp (Ideal.Quotient.mkₐ F J) := by
              simp
    refine ⟨s, ?_⟩
    simpa [hpi_eq] using hpi0_comp_s

end
