import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.

/-- Ideal generated by `P^k` in `K[X]`. -/
def polynomialPowerIdeal (K : Type*) [Field K] (P : Polynomial K) (k : ℕ) :
    Ideal (Polynomial K) :=
  Ideal.span ({P ^ k} : Set (Polynomial K))

/-- The quotient ring `K[X]/(P^k)`. -/
abbrev polynomialPowerQuotient (K : Type*) [Field K] (P : Polynomial K) (k : ℕ) :=
  (Polynomial K) ⧸ polynomialPowerIdeal K P k

/-- The ideal generated by the class of `P` in the quotient `K[X]/(P^k)`. -/
def quotientIdealByClassOfP (K : Type*) [Field K] (P : Polynomial K) (k : ℕ) :
    Ideal (polynomialPowerQuotient K P k) :=
  Ideal.span
    ({Ideal.Quotient.mk (polynomialPowerIdeal K P k) P} :
      Set (polynomialPowerQuotient K P k))

/-- Recursive power of an ideal: `idealPower I 0 = ⊤` and `idealPower I (n+1) = I * idealPower I n`. -/
def idealPower (R : Type*) [Semiring R] (I : Ideal R) : ℕ → Ideal R
  | 0 => ⊤
  | n + 1 => I * idealPower R I n

/-- Helper for n000002: the quotient ideal generated by the class of `P` is the map of `(P)`. -/
lemma helperFor_n000002_quotientIdealByClassOfP_eq_map_spanP
    (K : Type*) [Field K] (P : Polynomial K) (k : ℕ) :
    quotientIdealByClassOfP K P k =
      (Ideal.span ({P} : Set (Polynomial K))).map
        (Ideal.Quotient.mk (polynomialPowerIdeal K P k)) := by
  simpa [quotientIdealByClassOfP, Set.image_singleton] using
    (Ideal.map_span (Ideal.Quotient.mk (polynomialPowerIdeal K P k)) ({P} : Set (Polynomial K))).symm

/-- Helper for n000002: the ideal `(P^k)` is contained in `(P)` for `k ≥ 1`. -/
lemma helperFor_n000002_polynomialPowerIdeal_le_spanP
    (K : Type*) [Field K] (P : Polynomial K) (k : ℕ) (hk : 1 ≤ k) :
    polynomialPowerIdeal K P k ≤ Ideal.span ({P} : Set (Polynomial K)) := by
  refine Ideal.span_le.2 ?_
  intro f hf
  have hf' : f = P ^ k := by
    simpa using hf
  subst hf'
  have hk0 : 0 < k := lt_of_lt_of_le (Nat.succ_pos 0) hk
  obtain ⟨n, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt hk0)
  have hdiv : P ∣ P ^ (n + 1) := by
    refine ⟨P ^ n, ?_⟩
    simp [pow_succ, mul_comm]
  exact (Ideal.mem_span_singleton).2 hdiv

/-- Helper for n000002: `idealPower` agrees with `Ideal.pow` in commutative semirings. -/
lemma helperFor_n000002_idealPower_eq_pow
    (R : Type*) [CommSemiring R] (I : Ideal R) (n : ℕ) :
    idealPower R I n = I ^ n := by
  induction n with
  | zero =>
      simp [idealPower]
  | succ n ih =>
      simp [idealPower, ih, pow_succ, mul_comm]

/-- Helper for n000002: `idealPower` commutes with `Ideal.map`. -/
lemma helperFor_n000002_idealPower_map
    (R S : Type*) [CommSemiring R] [CommSemiring S] (f : R →+* S) (I : Ideal R) :
    ∀ n, idealPower S (Ideal.map f I) n = Ideal.map f (idealPower R I n) := by
  intro n
  induction n with
  | zero =>
      simp [idealPower, Ideal.map_top]
  | succ n ih =>
      calc
        idealPower S (Ideal.map f I) (n + 1) =
            Ideal.map f I * idealPower S (Ideal.map f I) n := by
              simp [idealPower]
        _ = Ideal.map f I * Ideal.map f (idealPower R I n) := by
              simpa [ih]
        _ = Ideal.map f (I * idealPower R I n) := by
              exact (Ideal.map_mul f I (idealPower R I n)).symm

/-- Helper for n000002: the ideal generated by the class of `P` in the quotient is maximal. -/
lemma helperFor_n000002_quotientIdealByClassOfP_isMaximal
    (K : Type*) [Field K] (P : Polynomial K) (k : ℕ) (hk : 1 ≤ k) (hP : Irreducible P) :
    (quotientIdealByClassOfP K P k).IsMaximal := by
  classical
  let I : Ideal (Polynomial K) := polynomialPowerIdeal K P k
  let J : Ideal (Polynomial K) := Ideal.span ({P} : Set (Polynomial K))
  let f : Polynomial K →+* polynomialPowerQuotient K P k := Ideal.Quotient.mk I
  have hsurj : Function.Surjective f := Ideal.Quotient.mk_surjective
  have hIJ : I ≤ J := helperFor_n000002_polynomialPowerIdeal_le_spanP K P k hk
  letI : Fact (Irreducible P) := ⟨hP⟩
  have hJmax : J.IsMaximal := by
    simpa [J] using
      (inferInstance :
        (Ideal.span ({P} : Set (Polynomial K)) : Ideal (Polynomial K)).IsMaximal)
  have hker : RingHom.ker f ≤ J := by
    simpa [f] using hIJ
  have hmapmax : (J.map f).IsMaximal := by
    haveI : J.IsMaximal := hJmax
    exact Ideal.IsMaximal.map_of_surjective_of_ker_le (f := f) hsurj hker
  have hEq :
      quotientIdealByClassOfP K P k =
        (Ideal.span ({P} : Set (Polynomial K))).map (Ideal.Quotient.mk I) :=
    helperFor_n000002_quotientIdealByClassOfP_eq_map_spanP K P k
  simpa [hEq, J, f] using hmapmax

/-- Helper for n000002: the quotient has a unique maximal ideal. -/
lemma helperFor_n000002_unique_maximalIdeal_quotient
    (K : Type*) [Field K] (P : Polynomial K) (k : ℕ) (hk : 1 ≤ k) (hP : Irreducible P) :
    ∃! M : Ideal (polynomialPowerQuotient K P k), M.IsMaximal := by
  classical
  let I : Ideal (Polynomial K) := polynomialPowerIdeal K P k
  let J : Ideal (Polynomial K) := Ideal.span ({P} : Set (Polynomial K))
  let f : Polynomial K →+* polynomialPowerQuotient K P k := Ideal.Quotient.mk I
  have hsurj : Function.Surjective f := Ideal.Quotient.mk_surjective
  have hIJ : I ≤ J := helperFor_n000002_polynomialPowerIdeal_le_spanP K P k hk
  have hQmax : (quotientIdealByClassOfP K P k).IsMaximal :=
    helperFor_n000002_quotientIdealByClassOfP_isMaximal K P k hk hP
  refine ⟨quotientIdealByClassOfP K P k, hQmax, ?_⟩
  intro M hM
  haveI : M.IsMaximal := hM
  have hcomapmax : (Ideal.comap f M).IsMaximal :=
    Ideal.comap_isMaximal_of_surjective (f := f) hsurj (K := M)
  have hPk_mem_I : P ^ k ∈ I := by
    have hx : P ^ k ∈ ({P ^ k} : Set (Polynomial K)) := by
      simp
    exact Ideal.subset_span hx
  have hPk_mem_comap : P ^ k ∈ Ideal.comap f M := by
    have hPk_mem_ker : P ^ k ∈ RingHom.ker f := by
      simpa [f] using hPk_mem_I
    exact (Ideal.ker_le_comap f) hPk_mem_ker
  haveI : (Ideal.comap f M).IsMaximal := hcomapmax
  have hP_mem_comap : P ∈ Ideal.comap f M := by
    have hprime : (Ideal.comap f M).IsPrime := inferInstance
    exact hprime.mem_of_pow_mem k hPk_mem_comap
  have hJle : J ≤ Ideal.comap f M := by
    refine Ideal.span_le.2 ?_
    intro x hx
    have hx' : x = P := by
      simpa using hx
    subst hx'
    exact hP_mem_comap
  letI : Fact (Irreducible P) := ⟨hP⟩
  have hJmax : J.IsMaximal := by
    simpa [J] using
      (inferInstance :
        (Ideal.span ({P} : Set (Polynomial K)) : Ideal (Polynomial K)).IsMaximal)
  have hcomap_ne_top : Ideal.comap f M ≠ ⊤ := by
    exact (Ideal.IsMaximal.ne_top hcomapmax)
  have hJeq : J = Ideal.comap f M :=
    hJmax.eq_of_le hcomap_ne_top hJle
  have hmap_comap : Ideal.map f (Ideal.comap f M) = M :=
    Ideal.map_comap_of_surjective (f := f) hsurj M
  calc
    M = Ideal.map f (Ideal.comap f M) := by
      symm
      exact hmap_comap
    _ = Ideal.map f J := by
      simpa [hJeq]
    _ = quotientIdealByClassOfP K P k := by
      simpa using
        (helperFor_n000002_quotientIdealByClassOfP_eq_map_spanP K P k).symm

/-- Helper for n000002: the residue field identification. -/
lemma helperFor_n000002_residueField_ringEquiv
    (K : Type*) [Field K] (P : Polynomial K) (k : ℕ) (hk : 1 ≤ k) :
    Nonempty
      (polynomialPowerQuotient K P k ⧸ quotientIdealByClassOfP K P k ≃+*
        (Polynomial K) ⧸ Ideal.span ({P} : Set (Polynomial K))) := by
  classical
  let I : Ideal (Polynomial K) := polynomialPowerIdeal K P k
  let J : Ideal (Polynomial K) := Ideal.span ({P} : Set (Polynomial K))
  have hIJ : I ≤ J := helperFor_n000002_polynomialPowerIdeal_le_spanP K P k hk
  have hEq :
      quotientIdealByClassOfP K P k =
        (Ideal.span ({P} : Set (Polynomial K))).map (Ideal.Quotient.mk I) :=
    helperFor_n000002_quotientIdealByClassOfP_eq_map_spanP K P k
  refine ⟨(Ideal.quotEquivOfEq hEq).trans ?_⟩
  exact DoubleQuot.quotQuotEquivQuotOfLE (I := I) (J := J) hIJ

/-- n000002: Let `K` be a field, `P ∈ K[X]` irreducible, and `k ≥ 1`. Set `R := K[X]/(P^k)`. Then
`R` is local with maximal ideal generated by the class of `P`, `m^k = 0`, and the residue field
`R/m` is (canonically) isomorphic to `K[X]/(P)`. -/
theorem local_quotient_by_irreducible_power
    (K : Type*) [Field K] (P : Polynomial K) (k : ℕ) (hk : 1 ≤ k) (hP : Irreducible P) :
    ∃ hR : IsLocalRing (polynomialPowerQuotient K P k),
      @IsLocalRing.maximalIdeal (polynomialPowerQuotient K P k) _ hR =
          quotientIdealByClassOfP K P k ∧
        idealPower (polynomialPowerQuotient K P k) (quotientIdealByClassOfP K P k) k =
          (⊥ : Ideal (polynomialPowerQuotient K P k)) ∧
        Nonempty
          (polynomialPowerQuotient K P k ⧸ quotientIdealByClassOfP K P k ≃+*
            (Polynomial K) ⧸ Ideal.span ({P} : Set (Polynomial K))) := by
  classical
  have huniq :
      ∃! M : Ideal (polynomialPowerQuotient K P k), M.IsMaximal :=
    helperFor_n000002_unique_maximalIdeal_quotient K P k hk hP
  let hR : IsLocalRing (polynomialPowerQuotient K P k) :=
    IsLocalRing.of_unique_max_ideal huniq
  refine ⟨hR, ?_⟩
  haveI : IsLocalRing (polynomialPowerQuotient K P k) := hR
  have hQmax : (quotientIdealByClassOfP K P k).IsMaximal :=
    helperFor_n000002_quotientIdealByClassOfP_isMaximal K P k hk hP
  have hmax_eq :
      @IsLocalRing.maximalIdeal (polynomialPowerQuotient K P k) _ hR =
        quotientIdealByClassOfP K P k := by
    simpa using (IsLocalRing.eq_maximalIdeal hQmax).symm
  refine ⟨hmax_eq, ?_⟩
  have hpow_zero :
      idealPower (polynomialPowerQuotient K P k) (quotientIdealByClassOfP K P k) k =
        (⊥ : Ideal (polynomialPowerQuotient K P k)) := by
    let I : Ideal (Polynomial K) := polynomialPowerIdeal K P k
    let J : Ideal (Polynomial K) := Ideal.span ({P} : Set (Polynomial K))
    let f : Polynomial K →+* polynomialPowerQuotient K P k := Ideal.Quotient.mk I
    have hEq :
        quotientIdealByClassOfP K P k = J.map f :=
      helperFor_n000002_quotientIdealByClassOfP_eq_map_spanP K P k
    have hJpow : idealPower (Polynomial K) J k = I := by
      have hpow :
          idealPower (Polynomial K) J k = J ^ k := by
        simpa using (helperFor_n000002_idealPower_eq_pow (Polynomial K) J k)
      have hJpow' : J ^ k = I := by
        simpa [J, polynomialPowerIdeal] using (Ideal.span_singleton_pow P k)
      exact hpow.trans hJpow'
    have hmap_pow :
        idealPower (polynomialPowerQuotient K P k) (quotientIdealByClassOfP K P k) k =
          Ideal.map f I := by
      have hmap :
          idealPower (polynomialPowerQuotient K P k) (Ideal.map f J) k =
            Ideal.map f (idealPower (Polynomial K) J k) :=
        helperFor_n000002_idealPower_map (Polynomial K)
          (polynomialPowerQuotient K P k) f J k
      simpa [hEq, hJpow] using hmap
    have hmap_bot :
        Ideal.map f I = (⊥ : Ideal (polynomialPowerQuotient K P k)) := by
      simpa [f] using (Ideal.map_quotient_self (I := I))
    calc
      idealPower (polynomialPowerQuotient K P k) (quotientIdealByClassOfP K P k) k
          = Ideal.map f I := hmap_pow
      _ = (⊥ : Ideal (polynomialPowerQuotient K P k)) := hmap_bot
  refine ⟨hpow_zero, ?_⟩
  exact helperFor_n000002_residueField_ringEquiv K P k hk
