import Mathlib

/-- If some pair of elements does not commute, then the center is not `⊤`. -/
lemma center_ne_top_of_exists_noncommute {G : Type*} [Group G]
    (h : ∃ x y : G, x * y ≠ y * x) : (Subgroup.center G : Subgroup G) ≠ ⊤ := by
  intro hZ
  rcases h with ⟨x, y, hxy⟩
  have hx : x ∈ Subgroup.center G := by
    simp [hZ]
  have : y * x = x * y := (Subgroup.mem_center_iff.mp hx) y
  exact hxy this.symm

/-- In a group of order `p^3` (`p` prime), noncommutativity forces the center to have order `p`. -/
lemma card_center_eq_p_of_card_eq_p_pow_three_and_center_ne_top {G : Type*} [Group G] {p : ℕ}
    [hp : Fact p.Prime] (hG : Nat.card G = p ^ 3) (hZ : (Subgroup.center G : Subgroup G) ≠ ⊤) :
    Nat.card (Subgroup.center G) = p := by
  classical
  haveI : Finite G := Nat.finite_of_card_ne_zero (hG ▸ pow_ne_zero 3 hp.out.ne_zero)
  rcases IsPGroup.card_center_eq_prime_pow (G := G) (p := p) (n := 3) hG (by decide) with
    ⟨k, hk0, hk_card⟩
  have hk_dvd : p ^ k ∣ p ^ 3 := by
    have hdiv : Nat.card (Subgroup.center G) ∣ Nat.card G :=
      Subgroup.card_subgroup_dvd_card (Subgroup.center G)
    simpa [hk_card, hG] using hdiv
  have hk_le3 : k ≤ 3 :=
    (Nat.pow_dvd_pow_iff_le_right hp.out.one_lt).1 hk_dvd
  have hk_ge1 : 1 ≤ k := Nat.succ_le_of_lt hk0
  have hk_lt4 : k < 4 := Nat.lt_of_le_of_lt hk_le3 (Nat.lt_succ_self 3)
  interval_cases k using hk_ge1, hk_lt4
  · simp [hk_card, pow_one]
  ·
    -- If `|Z(G)| = p^2`, then `G/Z(G)` has prime order, hence is cyclic; this forces `G` to be
    -- commutative, so `Z(G) = ⊤`, contradicting `hZ`.
    have hZcard : Nat.card (Subgroup.center G) = p ^ 2 := by simp [hk_card]
    have hQcard : Nat.card (G ⧸ Subgroup.center G) = p := by
      have hmul :
          Nat.card G =
            Nat.card (G ⧸ Subgroup.center G) * Nat.card (Subgroup.center G) :=
        Subgroup.card_eq_card_quotient_mul_card_subgroup (s := Subgroup.center G) (α := G)
      have hmul' : p ^ 3 = Nat.card (G ⧸ Subgroup.center G) * p ^ 2 := by
        simpa [hG, hZcard] using hmul
      apply Nat.mul_right_cancel (pow_pos hp.out.pos 2)
      calc
        Nat.card (G ⧸ Subgroup.center G) * p ^ 2 = p ^ 3 := by
          simpa using hmul'.symm
        _ = p ^ 2 * p := by simp [pow_succ]
        _ = p * p ^ 2 := by ac_rfl
    have hcyc : IsCyclic (G ⧸ Subgroup.center G) :=
      isCyclic_of_prime_card (α := G ⧸ Subgroup.center G) (p := p) hQcard
    have hcomm : ∀ a b : G, a * b = b * a := by
      letI : IsCyclic (G ⧸ Subgroup.center G) := hcyc
      intro a b
      simpa using
        (commutative_of_cyclic_center_quotient
          (G := G)
          (G' := G ⧸ Subgroup.center G)
          (f := QuotientGroup.mk' (Subgroup.center G))
          (hf := (QuotientGroup.ker_mk' (Subgroup.center G)).le) a b)
    letI : CommGroup G := { toGroup := (inferInstance : Group G), mul_comm := hcomm }
    have : Subgroup.center G = ⊤ := by
      simpa using (CommGroup.center_eq_top (G := G))
    exact (hZ this).elim
  ·
    -- If `|Z(G)| = |G|`, then `Z(G) = ⊤`, contradicting `hZ`.
    have hcard : Nat.card (Subgroup.center G) = Nat.card G := by
      calc
        Nat.card (Subgroup.center G) = p ^ 3 := by simp [hk_card]
        _ = Nat.card G := by simp [hG]
    have : Subgroup.center G = ⊤ :=
      Subgroup.eq_top_of_card_eq (H := Subgroup.center G) hcard
    exact (hZ this).elim

/-- If `|G| = p^3` and `|Z(G)| = p`, then `G/Z(G)` has order `p^2`, hence is commutative; this
implies `commutator G ≤ Z(G)`. -/
lemma commutator_le_center_of_card_center_eq_p {G : Type*} [Group G] {p : ℕ} [hp : Fact p.Prime]
    (hG : Nat.card G = p ^ 3) (hc : Nat.card (Subgroup.center G) = p) :
    commutator G ≤ Subgroup.center G := by
  classical
  haveI : Finite G := Nat.finite_of_card_ne_zero (hG ▸ pow_ne_zero 3 hp.out.ne_zero)
  have hQcard : Nat.card (G ⧸ Subgroup.center G) = p ^ 2 := by
    have hmul :
        Nat.card G =
          Nat.card (G ⧸ Subgroup.center G) * Nat.card (Subgroup.center G) :=
      Subgroup.card_eq_card_quotient_mul_card_subgroup (s := Subgroup.center G) (α := G)
    have hmul' : p ^ 3 = Nat.card (G ⧸ Subgroup.center G) * p := by
      simpa [hG, hc] using hmul
    apply Nat.mul_right_cancel hp.out.pos
    calc
      Nat.card (G ⧸ Subgroup.center G) * p = p ^ 3 := by
        simpa using hmul'.symm
      _ = p ^ 2 * p := by simp [pow_succ]
  have hcommQ : ∀ a b : G ⧸ Subgroup.center G, a * b = b * a :=
    IsPGroup.commutative_of_card_eq_prime_sq (G := G ⧸ Subgroup.center G) (p := p) hQcard
  have hcommStd : Std.Commutative (· * · : (G ⧸ Subgroup.center G) → _ → _) :=
    ⟨hcommQ⟩
  exact
    (Subgroup.Normal.quotient_commutative_iff_commutator_le
      (G := G) (N := Subgroup.center G)).1 hcommStd

/-- Prove that if $G$ is a nonabelian group of order $p^3$ ($p$ prime),
    then the center of $G$ is the subgroup generated by all elements of
    the form $aba^{-1}b^{-1}$ ($a, b \in G$). -/
theorem center_eq_commutator_of_pow_three_eq_card {G : Type} [Group G] {p : ℕ} [hp : Fact p.Prime]
    (hG : p ^ 3 = Nat.card G) (h : ∃ x y : G, x * y ≠ y * x) :
    Subgroup.center G = commutator G := by
  classical
  have hG' : Nat.card G = p ^ 3 := hG.symm
  haveI : Finite G := Nat.finite_of_card_ne_zero (hG' ▸ pow_ne_zero 3 hp.out.ne_zero)
  have hZ : (Subgroup.center G : Subgroup G) ≠ ⊤ :=
    center_ne_top_of_exists_noncommute (G := G) h
  have hc : Nat.card (Subgroup.center G) = p :=
    card_center_eq_p_of_card_eq_p_pow_three_and_center_ne_top (G := G) (p := p) hG' hZ
  have hle : commutator G ≤ Subgroup.center G :=
    commutator_le_center_of_card_center_eq_p (G := G) (p := p) hG' hc
  have hne : commutator G ≠ ⊥ := by
    intro hbot
    exact hZ ((commutator_eq_bot_iff_center_eq_top (G := G)).1 hbot)
  have hdiv : Nat.card (commutator G) ∣ p := by
    have hdivZ :
        Nat.card (commutator G) ∣ Nat.card (Subgroup.center G) :=
      Subgroup.card_dvd_of_le hle
    simpa [hc] using hdivZ
  have hcardC : Nat.card (commutator G) = p := by
    rcases (Nat.dvd_prime hp.out).1 hdiv with h1 | hp'
    ·
      have : commutator G = ⊥ :=
        (Subgroup.eq_bot_iff_card (H := commutator G)).2 h1
      exact (hne this).elim
    · exact hp'
  have hEq : commutator G = Subgroup.center G := by
    apply Subgroup.eq_of_le_of_card_ge (H := commutator G) (K := Subgroup.center G) hle
    simp [hc, hcardC]
  exact hEq.symm
