import Mathlib

open Polynomial IntermediateField AdjoinRoot

-- A K-algebra automorphism fixes the simple intermediate field K⟮β⟯ iff it fixes β.
lemma mem_fixingSubgroup_adjoin_simple_iff {K L : Type*} [Field K] [Field L] [Algebra K L]
    {β : L} (τ : L ≃ₐ[K] L) : τ ∈ (K⟮β⟯).fixingSubgroup ↔ τ β = β := by
  constructor
  · intro hτ
    have hτ' := (IntermediateField.mem_fixingSubgroup_iff (K:=K⟮β⟯) τ).1 hτ
    exact hτ' β (IntermediateField.mem_adjoin_simple_self (F:=K) (α:=β))
  · intro hτβ
    refine (IntermediateField.mem_fixingSubgroup_iff (K:=K⟮β⟯) τ).2 ?_
    intro x hx
    refine IntermediateField.adjoin_induction (F:=K) (E:=L) (s:={β})
      (p := fun x _ => τ x = x)
      ?mem ?alg ?add ?inv ?mul (by simpa using hx)
    · intro x hx
      rcases Set.mem_singleton_iff.mp hx with rfl
      simp [hτβ]
    · intro x
      simp [τ.commutes x]
    · intro x y hx hy hx' hy'
      simp [map_add, hx', hy']
    · intro x hx hx'
      simp [map_inv₀, hx']
    · intro x y hx hy hx' hy'
      simp [map_mul, hx', hy']

-- If an algebra automorphism fixes x, then all its powers fix x.
lemma pow_fix_of_fix {K L : Type*} [Field K] [Field L] [Algebra K L]
    (τ : L ≃ₐ[K] L) {x : L} (h : τ x = x) : ∀ n : ℕ, (τ ^ n) x = x := by
  intro n
  induction n with
  | zero => simp
  | succ n ih =>
      simp [pow_succ, AlgEquiv.mul_apply, ih, h]

-- In a cyclic group, the subgroups generated by σ^a and σ^b intersect trivially
-- when a and b are coprime and orderOf σ = a*b.
lemma zpowers_inf_eq_bot_of_coprime {G : Type*} [Group G] (σ : G) (n a b : ℕ)
    (hσ : orderOf σ = n) (hn' : n = a * b) (hab : Nat.Coprime a b) :
    Subgroup.zpowers (σ ^ a) ⊓ Subgroup.zpowers (σ ^ b) = ⊥ := by
  have hpow_ab : σ ^ (a * b) = 1 := by
    simpa [hσ, hn'] using (pow_orderOf_eq_one σ)
  have hpow_a : (σ ^ a) ^ b = 1 := by
    simpa [pow_mul] using hpow_ab
  have hpow_b : (σ ^ b) ^ a = 1 := by
    have : σ ^ (b * a) = 1 := by
      simpa [mul_comm] using hpow_ab
    simpa [pow_mul] using this
  have horder_a : orderOf (σ ^ a) ∣ b := orderOf_dvd_of_pow_eq_one hpow_a
  have horder_b : orderOf (σ ^ b) ∣ a := orderOf_dvd_of_pow_eq_one hpow_b
  ext τ
  constructor
  · intro hτ
    rcases hτ with ⟨hτa, hτb⟩
    have hτa' : orderOf τ ∣ orderOf (σ ^ a) := orderOf_dvd_of_mem_zpowers hτa
    have hτb' : orderOf τ ∣ orderOf (σ ^ b) := orderOf_dvd_of_mem_zpowers hτb
    have hτb'' : orderOf τ ∣ b := hτa'.trans horder_a
    have hτa'' : orderOf τ ∣ a := hτb'.trans horder_b
    have hτgcd : orderOf τ ∣ Nat.gcd a b := Nat.dvd_gcd hτa'' hτb''
    have hτone : orderOf τ = 1 := by
      apply Nat.dvd_one.mp
      simpa [hab.gcd_eq_one] using hτgcd
    have hτ1 : τ = 1 := (orderOf_eq_one_iff).1 hτone
    simp [hτ1]
  · intro hτ
    have hτ1 : τ = 1 := by simpa [Subgroup.mem_bot] using hτ
    simp [hτ1]

/-- Let $L/K$ be a Galois extension of fields such that $\mathrm{Gal}(L/K)$ is cyclic of order $n$,
generated by $\sigma$. Write $n = ab$ with $\gcd(a,b) =1$. Let $F_1$ be the fixed field of
$\sigma^a$ and $F_2$ be the fixed field of $\sigma^b$. Suppose that $F_1 = K(\alpha)$ and
$F_2 = K(\beta)$.  Prove that $L = K(\alpha+\beta)$. -/
theorem adjoin_add_eq_top_of_fixedField_zpowers {K L : Type} [Field K]
    [Field L] [Algebra K L] [IsGalois K L] (n a b : ℕ)
    (σ : L ≃ₐ[K] L) (hσ : orderOf σ = n) (cycle : Subgroup.zpowers σ = ⊤) (hn : n > 0)
    (hn' : n = a * b) (hab : Nat.Coprime a b) {α β : L}
    (hα : K⟮α⟯ = IntermediateField.fixedField (Subgroup.zpowers (σ ^ a)))
    (hβ : K⟮β⟯ = IntermediateField.fixedField (Subgroup.zpowers (σ ^ b))) : K⟮α + β⟯ = ⊤ := by
  classical
  have hcard : Nat.card (L ≃ₐ[K] L) = n := by
    simpa [hσ] using (orderOf_eq_card_of_zpowers_eq_top (g:=σ) cycle).symm
  have hfinite : Finite (L ≃ₐ[K] L) := by
    apply Nat.finite_of_card_ne_zero
    have : (n : ℕ) ≠ 0 := Nat.ne_zero_of_lt hn
    simpa [hcard] using this
  haveI := hfinite
  haveI : FiniteDimensional K L := IsGalois.finiteDimensional_of_finite (F:=K) (E:=L)
  let H1 : Subgroup (L ≃ₐ[K] L) := Subgroup.zpowers (σ ^ a)
  let H2 : Subgroup (L ≃ₐ[K] L) := Subgroup.zpowers (σ ^ b)
  have hfixα : (K⟮α⟯).fixingSubgroup = H1 := by
    simpa [H1, hα] using (IntermediateField.fixingSubgroup_fixedField (H:=H1))
  have hfixβ : (K⟮β⟯).fixingSubgroup = H2 := by
    simpa [H2, hβ] using (IntermediateField.fixingSubgroup_fixedField (H:=H2))
  have hHinf : H1 ⊓ H2 = ⊥ := by
    simpa [H1, H2] using zpowers_inf_eq_bot_of_coprime σ n a b hσ hn' hab
  have hfix : (K⟮α + β⟯).fixingSubgroup = ⊥ := by
    ext τ
    constructor
    · intro hτ
      have hτ_add : τ (α + β) = α + β := by
        have hτ' := (IntermediateField.mem_fixingSubgroup_iff (K:=K⟮α + β⟯) τ).1 hτ
        exact hτ' (α + β) (IntermediateField.mem_adjoin_simple_self (F:=K) (α:=α + β))
      have hτ_mem : τ ∈ Subgroup.zpowers σ := by
        simp [cycle]
      rcases (by
        simpa [Subgroup.zpowers] using hτ_mem : ∃ k : ℤ, σ ^ k = τ) with ⟨k, hk⟩
      subst hk
      have hpow_comm : (σ ^ a) ^ k = (σ ^ k) ^ a := by
        calc
          (σ ^ a) ^ k = σ ^ ((a : ℤ) * k) := by
            simpa [zpow_natCast, mul_comm] using (zpow_mul' σ k (a : ℤ)).symm
          _ = σ ^ (k * (a : ℤ)) := by
            simp [mul_comm]
          _ = (σ ^ k) ^ a := by
            simpa [zpow_natCast] using (zpow_mul σ k (a : ℤ))
      have hpow_comm' : (σ ^ b) ^ k = (σ ^ k) ^ b := by
        calc
          (σ ^ b) ^ k = σ ^ ((b : ℤ) * k) := by
            simpa [zpow_natCast, mul_comm] using (zpow_mul' σ k (b : ℤ)).symm
          _ = σ ^ (k * (b : ℤ)) := by
            simp [mul_comm]
          _ = (σ ^ k) ^ b := by
            simpa [zpow_natCast] using (zpow_mul σ k (b : ℤ))
      have hτa_mem : (σ ^ k) ^ a ∈ H1 := by
        refine ⟨k, ?_⟩
        simpa [H1] using hpow_comm
      have hτa_fixα : ((σ ^ k) ^ a) α = α := by
        have hτa_mem' : (σ ^ k) ^ a ∈ (K⟮α⟯).fixingSubgroup := by
          simpa [hfixα] using hτa_mem
        exact (mem_fixingSubgroup_adjoin_simple_iff (τ:=(σ ^ k) ^ a) (β:=α)).1 hτa_mem'
      have hτa_add : ((σ ^ k) ^ a) (α + β) = α + β := by
        exact (pow_fix_of_fix (τ:=σ ^ k) (x:=α + β) hτ_add a)
      have hτa_fixβ : ((σ ^ k) ^ a) β = β := by
        have hτa_add' : ((σ ^ k) ^ a) α + ((σ ^ k) ^ a) β = α + β := by
          simpa using hτa_add
        have hτa_add'' : α + ((σ ^ k) ^ a) β = α + β := by
          simpa [hτa_fixα] using hτa_add'
        exact add_left_cancel hτa_add''
      have hτa_memβ : (σ ^ k) ^ a ∈ (K⟮β⟯).fixingSubgroup := by
        exact (mem_fixingSubgroup_adjoin_simple_iff (τ:=(σ ^ k) ^ a) (β:=β)).2 hτa_fixβ
      have hτa_memH2 : (σ ^ k) ^ a ∈ H2 := by
        simpa [hfixβ] using hτa_memβ
      have hτa_mem_inf : (σ ^ k) ^ a ∈ H1 ⊓ H2 := ⟨hτa_mem, hτa_memH2⟩
      have hτa_one : (σ ^ k) ^ a = 1 := by
        have : (σ ^ k) ^ a ∈ (⊥ : Subgroup (L ≃ₐ[K] L)) := by
          simpa [hHinf] using hτa_mem_inf
        simpa [Subgroup.mem_bot] using this
      have hτb_mem : (σ ^ k) ^ b ∈ H2 := by
        refine ⟨k, ?_⟩
        simpa [H2] using hpow_comm'
      have hτb_fixβ : ((σ ^ k) ^ b) β = β := by
        have hτb_mem' : (σ ^ k) ^ b ∈ (K⟮β⟯).fixingSubgroup := by
          simpa [hfixβ] using hτb_mem
        exact (mem_fixingSubgroup_adjoin_simple_iff (τ:=(σ ^ k) ^ b) (β:=β)).1 hτb_mem'
      have hτb_add : ((σ ^ k) ^ b) (α + β) = α + β := by
        exact (pow_fix_of_fix (τ:=σ ^ k) (x:=α + β) hτ_add b)
      have hτb_fixα : ((σ ^ k) ^ b) α = α := by
        have hτb_add' : ((σ ^ k) ^ b) α + ((σ ^ k) ^ b) β = α + β := by
          simpa using hτb_add
        have hτb_add'' : ((σ ^ k) ^ b) α + β = α + β := by
          simpa [hτb_fixβ] using hτb_add'
        exact add_right_cancel hτb_add''
      have hτb_memα : (σ ^ k) ^ b ∈ (K⟮α⟯).fixingSubgroup := by
        exact (mem_fixingSubgroup_adjoin_simple_iff (τ:=(σ ^ k) ^ b) (β:=α)).2 hτb_fixα
      have hτb_memH1 : (σ ^ k) ^ b ∈ H1 := by
        simpa [hfixα] using hτb_memα
      have hτb_mem_inf : (σ ^ k) ^ b ∈ H1 ⊓ H2 := ⟨hτb_memH1, hτb_mem⟩
      have hτb_one : (σ ^ k) ^ b = 1 := by
        have : (σ ^ k) ^ b ∈ (⊥ : Subgroup (L ≃ₐ[K] L)) := by
          simpa [hHinf] using hτb_mem_inf
        simpa [Subgroup.mem_bot] using this
      have horder_a : orderOf (σ ^ k) ∣ a := orderOf_dvd_of_pow_eq_one hτa_one
      have horder_b : orderOf (σ ^ k) ∣ b := orderOf_dvd_of_pow_eq_one hτb_one
      have horder_gcd : orderOf (σ ^ k) ∣ Nat.gcd a b := Nat.dvd_gcd horder_a horder_b
      have horder_one : orderOf (σ ^ k) = 1 := by
        apply Nat.dvd_one.mp
        simpa [hab.gcd_eq_one] using horder_gcd
      have hτ1 : σ ^ k = 1 := (orderOf_eq_one_iff).1 horder_one
      simp [hτ1]
    · intro hτ
      have hτ1 : τ = 1 := by
        simpa [Subgroup.mem_bot] using hτ
      subst hτ1
      simp
  calc
    K⟮α + β⟯ = IntermediateField.fixedField (K⟮α + β⟯).fixingSubgroup := by
      simpa using
        (IsGalois.fixedField_fixingSubgroup (K:=K⟮α + β⟯)).symm
    _ = ⊤ := by
      simp [hfix]
