import Mathlib

open Polynomial
/--Let \( f \in \mathbb{Q}[X] \) and \( \xi \in \mathbb{C} \) be a root of unity. Show that \( f(\xi) \neq 2^{\frac{1}{4}} \).-/
-- `2^(1/4)` is not equal to `1` in `ℂ` (used to rule out trivial equalities).
lemma one_ne_two_cpow_one_div_four : (1 : ℂ) ≠ (2 : ℂ) ^ ((1 : ℂ) / 4) := by
  have hlt : (1 : ℝ) < (2 : ℝ) ^ (1 / 4 : ℝ) := by
    have hpos : (0 : ℝ) ≤ (1 : ℝ) := by norm_num
    have h12 : (1 : ℝ) < (2 : ℝ) := by norm_num
    have hexp : 0 < (1 / 4 : ℝ) := by norm_num
    simpa using (Real.rpow_lt_rpow hpos h12 hexp)
  have hne_real : (1 : ℝ) ≠ (2 : ℝ) ^ (1 / 4 : ℝ) := by
    exact ne_of_lt hlt
  intro hEq
  apply hne_real
  have hEq' : (1 : ℂ) = Complex.ofReal ((2 : ℝ) ^ (1 / 4 : ℝ)) := by
    simpa [Complex.ofReal_cpow (by norm_num : (0 : ℝ) ≤ (2 : ℝ))] using hEq
  exact (Complex.ofReal_inj).mp hEq'

-- Evaluation at `ξ` lands in the ℚ-subalgebra generated by `ξ`.
lemma eval₂_mem_adjoin_singleton (f : ℚ[X]) (ξ : ℂ) :
    f.eval₂ (algebraMap ℚ ℂ) ξ ∈ Algebra.adjoin ℚ ({ξ} : Set ℂ) := by
  simpa [Polynomial.aeval_def] using
    (Polynomial.aeval_mem_adjoin_singleton (R := ℚ) (x := ξ) (p := f))

-- `2^(1/4)` is real in `ℂ`, so it is fixed by `star`.
lemma star_two_pow_one_div_four :
    star ((2 : ℂ) ^ ((1 : ℂ) / 4)) = (2 : ℂ) ^ ((1 : ℂ) / 4) := by
  have hExp : ((1 : ℂ) / 4) = ((1 / 4 : ℝ) : ℂ) := by
    norm_num
  let r : ℝ := (2 : ℝ) ^ (1 / 4 : ℝ)
  have hreal : (2 : ℂ) ^ ((1 : ℂ) / 4) = (r : ℂ) := by
    have h := (Complex.ofReal_cpow (by norm_num : (0 : ℝ) ≤ (2 : ℝ)) (1 / 4 : ℝ))
    simpa [hExp, r] using h.symm
  have hreal' : (2 : ℂ) ^ ((4 : ℂ)⁻¹) = (r : ℂ) := by
    simpa [div_eq_mul_inv] using hreal
  simp [div_eq_mul_inv, hreal']

-- Any element of `ℚ⟮α⟯` is fixed by `star` when `α` is.
lemma star_eq_self_of_mem_adjoin {α x : ℂ} (hα : star α = α)
    (hx : x ∈ IntermediateField.adjoin ℚ ({α} : Set ℂ)) : star x = x := by
  refine IntermediateField.adjoin_induction (F := ℚ) (s := ({α} : Set ℂ))
    (p := fun x _ => star x = x) ?mem ?alg ?add ?inv ?mul hx
  · intro x hx
    rcases (Set.mem_singleton_iff.mp hx) with rfl
    simpa using hα
  · intro r
    simp
  · intro x y hx hy hx' hy'
    simp [star_add, hx', hy']
  · intro x hx hx'
    simp [hx']
  · intro x y hx hy hx' hy'
    simp [star_mul, hx', hy', mul_comm]

-- Eisenstein at `2` for `X^4 - 2` in `ℤ[X]`.
lemma eisenstein_X_pow_four_sub_two_Z :
    (X ^ 4 - C (2 : ℤ)).IsEisensteinAt (Ideal.span ({2} : Set ℤ)) := by
  refine Polynomial.IsEisensteinAt.mk ?leading ?mem ?notMem
  · intro hx
    have hx' : (2 : ℤ) ∣ (X ^ 4 - C (2 : ℤ)).leadingCoeff :=
      (Ideal.mem_span_singleton.mp hx)
    have hlead : (X ^ 4 - C (2 : ℤ)).leadingCoeff = (1 : ℤ) := by
      simpa using (Polynomial.leadingCoeff_X_pow_sub_C (R := ℤ) (n := 4) (r := (2 : ℤ))
        (by decide))
    have hx'' := hx'
    rw [hlead] at hx''
    exact (by norm_num : ¬ (2 : ℤ) ∣ (1 : ℤ)) hx''
  · intro n hn
    have hdeg : (X ^ 4 - C (2 : ℤ)).natDegree = 4 := by
      simpa using (Polynomial.natDegree_X_pow_sub_C (R := ℤ) (n := 4) (r := (2 : ℤ)))
    have hn' := hn
    rw [hdeg] at hn'
    by_cases h0 : n = 0
    · subst h0
      have hcoeffC : (2 : ℤ[X]).coeff 0 = if (0 : ℕ) = 0 then (2 : ℤ) else 0 := by
        simp
      have hcoeff : (X ^ 4 - C (2 : ℤ)).coeff 0 = -2 := by
        simp [coeff_X_pow, hcoeffC]
      have hdiv : (2 : ℤ) ∣ (-2 : ℤ) := by
        exact dvd_neg.mpr (dvd_refl (2 : ℤ))
      refine Ideal.mem_span_singleton.mpr ?_
      rw [hcoeff]
      exact hdiv
    · have h4 : n ≠ 4 := by exact ne_of_lt hn'
      have hcoeffC : (2 : ℤ[X]).coeff n = if n = 0 then (2 : ℤ) else 0 := by
        simpa using (Polynomial.coeff_C (a := (2 : ℤ)) (n := n))
      have hcoeff : (X ^ 4 - C (2 : ℤ)).coeff n = 0 := by
        simp [coeff_X_pow, h0, h4, hcoeffC]
      have hdiv : (2 : ℤ) ∣ (0 : ℤ) := by simp
      refine Ideal.mem_span_singleton.mpr ?_
      rw [hcoeff]
      exact hdiv
  · simp [Ideal.span_singleton_pow, Ideal.mem_span_singleton]

-- `X^4 - 2` is irreducible over `ℚ`.
lemma irreducible_X_pow_sub_two_Q : Irreducible (X ^ 4 - 2 : ℚ[X]) := by
  have hE : (X ^ 4 - C (2 : ℤ)).IsEisensteinAt (Ideal.span ({2} : Set ℤ)) :=
    eisenstein_X_pow_four_sub_two_Z
  have hprime : (Ideal.span ({2} : Set ℤ)).IsPrime := by
    have hp : Prime (2 : ℤ) := (Nat.prime_iff_prime_int).1 Nat.prime_two
    exact (Ideal.span_singleton_prime (α := ℤ) (p := (2 : ℤ)) (by norm_num)).2 hp
  have hmonic : (X ^ 4 - C (2 : ℤ)).Monic := by
    simpa using (Polynomial.monic_X_pow_sub_C (R := ℤ) (a := (2 : ℤ)) (n := 4) (by decide))
  have hprim : (X ^ 4 - C (2 : ℤ)).IsPrimitive := hmonic.isPrimitive
  have hdeg : (X ^ 4 - C (2 : ℤ)).natDegree = 4 := by
    simpa using (Polynomial.natDegree_X_pow_sub_C (R := ℤ) (n := 4) (r := (2 : ℤ)))
  have hdeg_pos : 0 < (X ^ 4 - C (2 : ℤ)).natDegree := by
    rw [hdeg]
    decide
  have hIrredZ : Irreducible (X ^ 4 - C (2 : ℤ)) :=
    (hE.irreducible hprime hprim) hdeg_pos
  have hIrredQ : Irreducible ((X ^ 4 - C (2 : ℤ)).map (Int.castRingHom ℚ)) :=
    (Polynomial.IsPrimitive.Int.irreducible_iff_irreducible_map_cast hprim).1 hIrredZ
  simpa using hIrredQ

-- The minimal polynomial of `2^(1/4)` over `ℚ`.
lemma minpoly_two_pow_one_div_four :
    minpoly ℚ ((2 : ℂ) ^ ((1 : ℂ) / 4)) = (X ^ 4 - 2 : ℚ[X]) := by
  have h := (minpoly.eq_of_irreducible_of_monic (A := ℚ)
    (B := ℂ) (x := (2 : ℂ) ^ ((1 : ℂ) / 4)) (p := (X ^ 4 - 2 : ℚ[X]))
    irreducible_X_pow_sub_two_Q (by simp [Polynomial.aeval_def])
    (by simpa using (Polynomial.monic_X_pow_sub_C (R := ℚ) (a := (2 : ℚ)) (n := 4)
      (by decide))))
  simpa using h.symm

-- The cyclotomic field generated by a root of unity is abelian Galois over `ℚ`.
lemma rootOfUnity_adjoin_isAbelianGalois {n : ℕ} (hn : 1 ≤ n) (ξ : ℂˣ)
    (h : ξ ∈ rootsOfUnity n ℂ) :
    IsAbelianGalois ℚ (IntermediateField.adjoin ℚ ({(ξ : ℂ)} : Set ℂ)) := by
  have hn0 : n ≠ 0 := by
    exact Nat.ne_of_gt (Nat.succ_le_iff.mp hn)
  haveI : NeZero n := ⟨hn0⟩
  obtain ⟨d, hd0, hdvd, hprim_unit⟩ := isPrimitiveRoot_of_mem_rootsOfUnity (u := ξ) (n := n) h
  haveI : NeZero d := ⟨hd0⟩
  have hprim : IsPrimitiveRoot (ξ : ℂ) d :=
    (IsPrimitiveRoot.map_of_injective (f := Units.coeHom ℂ) hprim_unit Units.coeHom_injective)
  let K : IntermediateField ℚ ℂ :=
    IntermediateField.adjoin ℚ {b : ℂ | ∃ n ∈ ({d} : Set ℕ), n ≠ 0 ∧ b ^ n = 1}
  have hcycl : IsCyclotomicExtension {d} ℚ K := by
    have h' : ∀ n ∈ ({d} : Set ℕ), n ≠ 0 → ∃ r : ℂ, IsPrimitiveRoot r n := by
      intro n hn hne
      rcases (Set.mem_singleton_iff.mp hn) with rfl
      exact ⟨(ξ : ℂ), hprim⟩
    simpa [K] using (IntermediateField.isCyclotomicExtension_adjoin_of_exists_isPrimitiveRoot
      (K := ℚ) (L := ℂ) (S := ({d} : Set ℕ)) h')
  haveI : IsAbelianGalois ℚ K := by
    simpa [K] using (IsCyclotomicExtension.isAbelianGalois (S := ({d} : Set ℕ)) (K := ℚ) (L := K))
  let F : IntermediateField ℚ ℂ := IntermediateField.adjoin ℚ ({(ξ : ℂ)} : Set ℂ)
  have hξ_in_set : (ξ : ℂ) ∈ {b : ℂ | ∃ n ∈ ({d} : Set ℕ), n ≠ 0 ∧ b ^ n = 1} := by
    refine ⟨d, by simp, hd0, ?_⟩
    simpa using hprim.pow_eq_one
  have hξ_mem : (ξ : ℂ) ∈ K := by
    exact IntermediateField.subset_adjoin (F := ℚ)
      (S := {b : ℂ | ∃ n ∈ ({d} : Set ℕ), n ≠ 0 ∧ b ^ n = 1}) hξ_in_set
  have hFK : F ≤ K := by
    refine (IntermediateField.adjoin_le_iff).2 ?_
    intro x hx
    rcases (Set.mem_singleton_iff.mp hx) with rfl
    exact hξ_mem
  haveI : IsAbelianGalois ℚ F :=
    IsAbelianGalois.of_algHom (f := IntermediateField.inclusion hFK)
  simpa [F] using (inferInstance : IsAbelianGalois ℚ F)

-- `ℚ(2^(1/4))` is not Galois over `ℚ`.
lemma not_isGalois_adjoin_two_pow_one_div_four :
    ¬ IsGalois ℚ (IntermediateField.adjoin ℚ ({(2 : ℂ) ^ ((1 : ℂ) / 4)} : Set ℂ)) := by
  intro hG
  let α : ℂ := (2 : ℂ) ^ ((1 : ℂ) / 4)
  let F : IntermediateField ℚ ℂ := IntermediateField.adjoin ℚ ({α} : Set ℂ)
  have hαmem : α ∈ F := by
    exact IntermediateField.subset_adjoin (F := ℚ) (S := ({α} : Set ℂ)) (by simp)
  let x : F := ⟨α, hαmem⟩
  have hminpoly : minpoly ℚ x = (X ^ 4 - 2 : ℚ[X]) := by
    have hmap := minpoly.algebraMap_eq (A := ℚ) (B := F) (B' := ℂ)
      (x := x) (h := (algebraMap F ℂ).injective)
    have hmin : minpoly ℚ (algebraMap F ℂ x) = (X ^ 4 - 2 : ℚ[X]) := by
      simpa [α, x] using minpoly_two_pow_one_div_four
    calc
      minpoly ℚ x = minpoly ℚ (algebraMap F ℂ x) := by
        simpa using hmap.symm
      _ = (X ^ 4 - 2 : ℚ[X]) := hmin
  have hsplit : ((X ^ 4 - 2 : ℚ[X]).map (algebraMap ℚ F)).Splits := by
    have hsplit' : ((minpoly ℚ x).map (algebraMap ℚ F)).Splits :=
      IsGalois.splits ℚ (E := F) (x := x)
    simpa [hminpoly] using hsplit'
  have hsplitC : ((X ^ 4 - 2 : ℚ[X]).map (algebraMap ℚ ℂ)).Splits :=
    IsAlgClosed.splits_codomain (p := (X ^ 4 - 2 : ℚ[X])) (f := algebraMap ℚ ℂ)
  have hrootmem : ∀ z ∈ (X ^ 4 - 2 : ℚ[X]).rootSet ℂ, z ∈ F := by
    have hiff := (IntermediateField.splits_iff_mem (F := F) (L := ℂ) (K := ℚ)
      (p := (X ^ 4 - 2 : ℚ[X])) hsplitC)
    exact (hiff.mp hsplit)
  have hIroot : (Complex.I * α) ∈ (X ^ 4 - 2 : ℚ[X]).rootSet ℂ := by
    have hne : (X ^ 4 - 2 : ℚ[X]) ≠ 0 := by
      simpa using (Polynomial.X_pow_sub_C_ne_zero (R := ℚ) (n := 4) (a := (2 : ℚ)) (by decide))
    have hzero : aeval (Complex.I * α) (X ^ 4 - 2 : ℚ[X]) = 0 := by
      simp [Polynomial.aeval_def, mul_pow, α]
    exact (Polynomial.mem_rootSet).2 ⟨hne, hzero⟩
  have hI_mem : (Complex.I * α) ∈ F := hrootmem _ hIroot
  have hstar : star (Complex.I * α) = Complex.I * α := by
    have hα' : star α = α := by
      simpa [α] using star_two_pow_one_div_four
    exact star_eq_self_of_mem_adjoin (α := α) (x := Complex.I * α) hα' hI_mem
  have hstar' : star (Complex.I * α) = -Complex.I * α := by
    have hα' : star α = α := by
      simpa [α] using star_two_pow_one_div_four
    simp [star_mul, hα', mul_comm]
  have hneq : Complex.I * α ≠ 0 := by
    have hαne : α ≠ 0 := by
      have h2 : (2 : ℂ) ≠ 0 := by norm_num
      have hαne' : (2 : ℂ) ^ ((1 : ℂ) / 4) ≠ 0 :=
        (Complex.cpow_ne_zero_iff).2 (Or.inl h2)
      dsimp [α]
      exact hαne'
    exact mul_ne_zero Complex.I_ne_zero hαne
  have hneg : -(Complex.I * α) = Complex.I * α := by
    calc
      -(Complex.I * α) = star (Complex.I * α) := by
        symm
        simpa using hstar'
      _ = Complex.I * α := hstar
  have hzero : Complex.I * α = 0 := by
    have hsum : Complex.I * α + Complex.I * α = 0 := by
      exact (neg_eq_iff_add_eq_zero.mp hneg)
    have hmul : (2 : ℂ) * (Complex.I * α) = 0 := by
      simpa [two_mul] using hsum
    have h2 : (2 : ℂ) ≠ 0 := by norm_num
    exact (mul_eq_zero.mp hmul).resolve_left h2
  exact hneq hzero

-- Key obstruction: `2^(1/4)` should not lie in a cyclotomic subalgebra.
lemma two_pow_one_div_four_not_mem_adjoin {n : ℕ} (hn : 1 ≤ n) (ξ : ℂˣ)
    (h : ξ ∈ rootsOfUnity n ℂ) :
    (2 : ℂ) ^ ((1 : ℂ) / 4) ∉ Algebra.adjoin ℚ ({(ξ : ℂ)} : Set ℂ) := by
  intro hmem
  let Fξ : IntermediateField ℚ ℂ := IntermediateField.adjoin ℚ ({(ξ : ℂ)} : Set ℂ)
  let Fα : IntermediateField ℚ ℂ :=
    IntermediateField.adjoin ℚ ({(2 : ℂ) ^ ((1 : ℂ) / 4)} : Set ℂ)
  have hFξ : IsAbelianGalois ℚ Fξ :=
    rootOfUnity_adjoin_isAbelianGalois (hn := hn) (ξ := ξ) (h := h)
  have hαmem : (2 : ℂ) ^ ((1 : ℂ) / 4) ∈ Fξ := by
    exact (IntermediateField.algebra_adjoin_le_adjoin ℚ ({(ξ : ℂ)} : Set ℂ)) hmem
  have hFα_le : Fα ≤ Fξ := by
    refine (IntermediateField.adjoin_le_iff).2 ?_
    intro x hx
    rcases (Set.mem_singleton_iff.mp hx) with rfl
    exact hαmem
  haveI : IsAbelianGalois ℚ Fξ := hFξ
  haveI : IsAbelianGalois ℚ Fα :=
    IsAbelianGalois.of_algHom (f := IntermediateField.inclusion hFα_le)
  haveI : IsGalois ℚ Fα := (inferInstance : IsGalois ℚ Fα)
  -- contradiction with non-Galoisness of `ℚ(2^(1/4))`
  have hG' : IsGalois ℚ
      (IntermediateField.adjoin ℚ ({(2 : ℂ) ^ ((1 : ℂ) / 4)} : Set ℂ)) := by
    simpa [Fα] using (inferInstance : IsGalois ℚ Fα)
  exact not_isGalois_adjoin_two_pow_one_div_four hG'
theorem eval₂_algebraMap_ne_two_pow_one_dvd_four {n : ℕ} (hn : 1 ≤ n) (f : ℚ[X]) (ξ : ℂˣ)
    (h : ξ ∈ rootsOfUnity n ℂ) : f.eval₂ (algebraMap ℚ ℂ) ξ ≠ (2 : ℂ) ^ ((1 : ℂ) / 4) := by
  intro hEq
  have hmem : (2 : ℂ) ^ ((1 : ℂ) / 4) ∈ Algebra.adjoin ℚ ({(ξ : ℂ)} : Set ℂ) := by
    simpa [hEq] using eval₂_mem_adjoin_singleton (f := f) (ξ := (ξ : ℂ))
  exact (two_pow_one_div_four_not_mem_adjoin (hn := hn) (ξ := ξ) (h := h)) hmem
