import Mathlib

open Polynomial
/-- Evaluation at a point sends `I.map C` back into `I`. -/
lemma eval_mem_of_mem_map_C {R : Type} [CommRing R] (I : Ideal R) (x : R) {p : R[X]}
    (hp : p ∈ I.map (C : R →+* R[X])) : Polynomial.eval x p ∈ I := by
  have hmap : Ideal.map (C : R →+* R[X]) I ≤ Ideal.comap (Polynomial.evalRingHom x) I := by
    refine (Ideal.map_le_iff_le_comap (f := (C : R →+* R[X]))).2 ?_
    intro r hr
    refine (Ideal.mem_comap (f := (C : R →+* R[X]))).2 ?_
    refine (Ideal.mem_comap (f := Polynomial.evalRingHom x)).2 ?_
    simpa using hr
  exact hmap hp

/-- Polynomials in `Ideal.span {1 - X}` vanish under evaluation at `1`. -/
lemma eval_one_mem_span_one_sub_X {R : Type} [CommRing R] {p : R[X]}
    (hp : p ∈ Ideal.span ({1 - X} : Set R[X])) : Polynomial.eval (1 : R) p = 0 := by
  have hle : Ideal.span ({1 - X} : Set R[X]) ≤
      Ideal.comap (Polynomial.evalRingHom (1 : R)) ⊥ := by
    refine (Ideal.span_le).2 ?_
    intro r hr
    rcases Set.mem_singleton_iff.mp hr with rfl
    refine (Ideal.mem_comap (f := Polynomial.evalRingHom (1 : R))).2 ?_
    simp
  have hp' : p ∈ Ideal.comap (Polynomial.evalRingHom (1 : R)) ⊥ := hle hp
  have : Polynomial.eval (1 : R) p ∈ (⊥ : Ideal R) :=
    (Ideal.mem_comap (f := Polynomial.evalRingHom (1 : R))).1 hp'
  simp at this
  exact this

/-- Polynomials in `Ideal.span {X}` vanish under evaluation at `0`. -/
lemma eval_zero_mem_span_X {R : Type} [CommRing R] {p : R[X]}
    (hp : p ∈ Ideal.span ({X} : Set R[X])) : Polynomial.eval (0 : R) p = 0 := by
  have hle : Ideal.span ({X} : Set R[X]) ≤
      Ideal.comap (Polynomial.evalRingHom (0 : R)) ⊥ := by
    refine (Ideal.span_le).2 ?_
    intro r hr
    rcases Set.mem_singleton_iff.mp hr with rfl
    refine (Ideal.mem_comap (f := Polynomial.evalRingHom (0 : R))).2 ?_
    simp
  have hp' : p ∈ Ideal.comap (Polynomial.evalRingHom (0 : R)) ⊥ := hle hp
  have : Polynomial.eval (0 : R) p ∈ (⊥ : Ideal R) :=
    (Ideal.mem_comap (f := Polynomial.evalRingHom (0 : R))).1 hp'
  simp at this
  exact this

/-- Evaluation at `x` sends `Ideal.span {X} • I.map C` into `I`. -/
lemma span_X_smul_map_C_le_comap_eval {R : Type} [CommRing R] (I : Ideal R) (x : R) :
    Ideal.span ({X} : Set R[X]) • I.map C ≤ Ideal.comap (Polynomial.evalRingHom x) I := by
  have hmul : Ideal.span ({X} : Set R[X]) * I.map C ≤
      Ideal.comap (Polynomial.evalRingHom x) I := by
    refine (Ideal.mul_le).2 ?_
    intro r hr s hs
    refine (Ideal.mem_comap (f := Polynomial.evalRingHom x)).2 ?_
    have hs' : Polynomial.eval x s ∈ I := eval_mem_of_mem_map_C I x hs
    have hmul' : Polynomial.eval x r * Polynomial.eval x s ∈ I := I.mul_mem_left _ hs'
    simpa [Polynomial.eval_mul] using hmul'
  simpa [Ideal.smul_eq_mul] using hmul

/-- Evaluation at `x` sends `Ideal.span {1 - X} • I.map C` into `I`. -/
lemma span_one_sub_X_smul_map_C_le_comap_eval {R : Type} [CommRing R] (I : Ideal R) (x : R) :
    Ideal.span ({1 - X} : Set R[X]) • I.map C ≤ Ideal.comap (Polynomial.evalRingHom x) I := by
  have hmul : Ideal.span ({1 - X} : Set R[X]) * I.map C ≤
      Ideal.comap (Polynomial.evalRingHom x) I := by
    refine (Ideal.mul_le).2 ?_
    intro r hr s hs
    refine (Ideal.mem_comap (f := Polynomial.evalRingHom x)).2 ?_
    have hs' : Polynomial.eval x s ∈ I := eval_mem_of_mem_map_C I x hs
    have hmul' : Polynomial.eval x r * Polynomial.eval x s ∈ I := I.mul_mem_left _ hs'
    simpa [Polynomial.eval_mul] using hmul'
  simpa [Ideal.smul_eq_mul] using hmul

/-- Evaluation at `1` kills the ideal generated by `(1 - X)`. -/
lemma span_one_sub_X_smul_map_C_le_comap_eval_one_bot {R : Type} [CommRing R] (I : Ideal R) :
    Ideal.span ({1 - X} : Set R[X]) • I.map C ≤
      Ideal.comap (Polynomial.evalRingHom (1 : R)) ⊥ := by
  have hmul : Ideal.span ({1 - X} : Set R[X]) * I.map C ≤
      Ideal.comap (Polynomial.evalRingHom (1 : R)) ⊥ := by
    refine (Ideal.mul_le).2 ?_
    intro r hr s hs
    refine (Ideal.mem_comap (f := Polynomial.evalRingHom (1 : R))).2 ?_
    have hr0 : Polynomial.eval (1 : R) r = 0 := eval_one_mem_span_one_sub_X hr
    have : Polynomial.eval (1 : R) (r * s) = 0 := by
      simp [Polynomial.eval_mul, hr0]
    simpa [Ideal.mem_bot] using this
  simpa [Ideal.smul_eq_mul] using hmul

/-- Evaluation at `0` kills the ideal generated by `X`. -/
lemma span_X_smul_map_C_le_comap_eval_zero_bot {R : Type} [CommRing R] (I : Ideal R) :
    Ideal.span ({X} : Set R[X]) • I.map C ≤
      Ideal.comap (Polynomial.evalRingHom (0 : R)) ⊥ := by
  have hmul : Ideal.span ({X} : Set R[X]) * I.map C ≤
      Ideal.comap (Polynomial.evalRingHom (0 : R)) ⊥ := by
    refine (Ideal.mul_le).2 ?_
    intro r hr s hs
    refine (Ideal.mem_comap (f := Polynomial.evalRingHom (0 : R))).2 ?_
    have hr0 : Polynomial.eval (0 : R) r = 0 := eval_zero_mem_span_X hr
    have : Polynomial.eval (0 : R) (r * s) = 0 := by
      simp [Polynomial.eval_mul, hr0]
    simpa [Ideal.mem_bot] using this
  simpa [Ideal.smul_eq_mul] using hmul

/--Let \( I_1, I_2 \subseteq K[x_1, \dots, x_n] \) be two ideals. With \( y \) an additional
indeterminate, form the ideal
\[
J := \big( y \cdot I_1 \cup (1 - y) \cdot I_2 \big) K[x_1, \dots, x_n, y] \subseteq K[x_1, \dots,
x_n, y].
\]Show that
\[
I_1 \cap I_2 = K[x_1, \dots, x_n] \cap J.
\]-/
theorem inf_eq_span_X_smul_sup_one_sub_X_smul_comap_C {K : Type} [Field K] (n : ℕ) 
    (I1 I2 : Ideal (MvPolynomial (Fin n) K)) :
    I1 ⊓ I2 = (Ideal.span {(X : (MvPolynomial (Fin n) K)[X])} • (I1.map C) ⊔
    Ideal.span {(1 - X : (MvPolynomial (Fin n) K)[X])} • (I2.map C) ).comap C := by
  ext f
  constructor
  · intro hf
    rcases (Ideal.mem_inf).1 hf with ⟨hf1, hf2⟩
    refine (Submodule.mem_sup).2 ?_
    refine ⟨(X : (MvPolynomial (Fin n) K)[X]) * C f, ?_,
      (1 - X : (MvPolynomial (Fin n) K)[X]) * C f, ?_, ?_⟩
    · have hX : (X : (MvPolynomial (Fin n) K)[X]) ∈
          Ideal.span ({X} : Set (MvPolynomial (Fin n) K)[X]) :=
        Ideal.subset_span (by simp)
      have hCf : (C f : (MvPolynomial (Fin n) K)[X]) ∈ I1.map C :=
        Ideal.mem_map_of_mem (f := (C : MvPolynomial (Fin n) K →+* (MvPolynomial (Fin n) K)[X]))
          hf1
      have hmul : (X : (MvPolynomial (Fin n) K)[X]) * C f ∈
          Ideal.span ({X} : Set (MvPolynomial (Fin n) K)[X]) * I1.map C :=
        Ideal.mul_mem_mul hX hCf
      simpa [Ideal.smul_eq_mul] using hmul
    · have hX : (1 - X : (MvPolynomial (Fin n) K)[X]) ∈
          Ideal.span ({1 - X} : Set (MvPolynomial (Fin n) K)[X]) :=
        Ideal.subset_span (by simp)
      have hCf : (C f : (MvPolynomial (Fin n) K)[X]) ∈ I2.map C :=
        Ideal.mem_map_of_mem (f := (C : MvPolynomial (Fin n) K →+* (MvPolynomial (Fin n) K)[X]))
          hf2
      have hmul : (1 - X : (MvPolynomial (Fin n) K)[X]) * C f ∈
          Ideal.span ({1 - X} : Set (MvPolynomial (Fin n) K)[X]) * I2.map C :=
        Ideal.mul_mem_mul hX hCf
      simpa [Ideal.smul_eq_mul] using hmul
    · ring
  · intro hf
    have hJ1 : (Ideal.span ({X} : Set (MvPolynomial (Fin n) K)[X]) • I1.map C ⊔
        Ideal.span ({1 - X} : Set (MvPolynomial (Fin n) K)[X]) • I2.map C) ≤
        Ideal.comap (Polynomial.evalRingHom (1 : MvPolynomial (Fin n) K)) I1 := by
      refine (sup_le_iff).2 ?_
      refine ⟨span_X_smul_map_C_le_comap_eval I1 (1 : MvPolynomial (Fin n) K), ?_⟩
      have hle_bot : Ideal.span ({1 - X} : Set (MvPolynomial (Fin n) K)[X]) • I2.map C ≤
          Ideal.comap (Polynomial.evalRingHom (1 : MvPolynomial (Fin n) K)) ⊥ :=
        span_one_sub_X_smul_map_C_le_comap_eval_one_bot I2
      exact hle_bot.trans (Ideal.comap_mono
        (f := Polynomial.evalRingHom (1 : MvPolynomial (Fin n) K))
        (show (⊥ : Ideal (MvPolynomial (Fin n) K)) ≤ I1 from bot_le))
    have hJ0 : (Ideal.span ({X} : Set (MvPolynomial (Fin n) K)[X]) • I1.map C ⊔
        Ideal.span ({1 - X} : Set (MvPolynomial (Fin n) K)[X]) • I2.map C) ≤
        Ideal.comap (Polynomial.evalRingHom (0 : MvPolynomial (Fin n) K)) I2 := by
      refine (sup_le_iff).2 ?_
      refine ⟨?_, span_one_sub_X_smul_map_C_le_comap_eval I2 (0 : MvPolynomial (Fin n) K)⟩
      have hle_bot : Ideal.span ({X} : Set (MvPolynomial (Fin n) K)[X]) • I1.map C ≤
          Ideal.comap (Polynomial.evalRingHom (0 : MvPolynomial (Fin n) K)) ⊥ :=
        span_X_smul_map_C_le_comap_eval_zero_bot I1
      exact hle_bot.trans (Ideal.comap_mono
        (f := Polynomial.evalRingHom (0 : MvPolynomial (Fin n) K))
        (show (⊥ : Ideal (MvPolynomial (Fin n) K)) ≤ I2 from bot_le))
    have hf1 : (C f : (MvPolynomial (Fin n) K)[X]) ∈
        Ideal.comap (Polynomial.evalRingHom (1 : MvPolynomial (Fin n) K)) I1 :=
      hJ1 hf
    have hf2 : (C f : (MvPolynomial (Fin n) K)[X]) ∈
        Ideal.comap (Polynomial.evalRingHom (0 : MvPolynomial (Fin n) K)) I2 :=
      hJ0 hf
    have hf1' : Polynomial.eval (1 : MvPolynomial (Fin n) K) (C f) ∈ I1 :=
      (Ideal.mem_comap (f := Polynomial.evalRingHom (1 : MvPolynomial (Fin n) K))).1 hf1
    have hf2' : Polynomial.eval (0 : MvPolynomial (Fin n) K) (C f) ∈ I2 :=
      (Ideal.mem_comap (f := Polynomial.evalRingHom (0 : MvPolynomial (Fin n) K))).1 hf2
    have hf1'' : f ∈ I1 := by
      simpa using hf1'
    have hf2'' : f ∈ I2 := by
      simpa using hf2'
    exact (Ideal.mem_inf).2 ⟨hf1'', hf2''⟩
