import Mathlib

open RingTheory

/-!
# Principal class prime ⇒ complete intersection (elementary infrastructure)

This file contains the elementary lemmas used by the principal-class scaffolding in
`Question_bench.FATEH.«98»`.
-/

namespace PrincipalClass

section Elementary

/-- In a subsingleton ring, every ideal is ⊤. -/
lemma ideal_eq_top_of_subsingleton {A : Type*} [CommRing A] [Subsingleton A] (I : Ideal A) :
    I = ⊤ := by
  apply (I.eq_top_iff_one).2
  have h1 : (1 : A) = 0 := Subsingleton.elim _ _
  simp [h1]

/--
If `a ∉ I` but `a * x ∈ I`, then `I ⊔ (x) ≠ ⊤`.

This is the correct weak consequence: it does **not** imply `x ∈ I` in general.
-/
lemma sup_span_singleton_ne_top_of_mul_mem {A : Type*} [CommRing A]
    (I : Ideal A) {a x : A} (ha : a ∉ I) (hax : a * x ∈ I) :
    I ⊔ Ideal.span ({x} : Set A) ≠ ⊤ := by
  intro hsup
  have hone : (1 : A) ∈ (I ⊔ Ideal.span ({x} : Set A) : Ideal A) := by
    simp [hsup]
  rcases (Submodule.mem_sup).1
      (show (1 : A) ∈ ((I ⊔ Ideal.span ({x} : Set A) : Ideal A) : Submodule A A) from hone)
    with ⟨u, huI, v, hv, huv⟩
  rcases (Ideal.mem_span_singleton'.1 (by simpa using hv)) with ⟨t, rfl⟩
  have haI : a ∈ I := by
    have huI' : a * u ∈ I := I.mul_mem_left _ huI
    have htI' : a * (t * x) ∈ I := by
      have : t * (a * x) ∈ I := I.mul_mem_left t hax
      simpa [mul_assoc, mul_left_comm, mul_comm] using this
    have : a = a * u + a * (t * x) := by
      have := congrArg (fun z : A => a * z) huv.symm
      simpa [mul_add, mul_assoc] using this
    exact this ▸ I.add_mem huI' htI'
  exact ha haI

/--
If `P` is generated by `r` elements (given as `a : Fin r → A`), then `P` is `Ideal.ofList` of a
list of length `r`.
-/
theorem exists_eq_ofList_length_and_eq {A : Type*} [CommRing A] [IsNoetherianRing A]
    (P : Ideal A) [P.IsPrime] (r : ℕ) (a : Fin r → A) (hP : P = Ideal.span (Set.range a)) :
    ∃ b : List A, b.length = r ∧ P = Ideal.ofList b := by
  classical
  have hset : Set.range a = {x | x ∈ List.ofFn a} := by
    ext x
    simp [List.mem_ofFn']
  have hP' : P = Ideal.ofList (List.ofFn a) := by
    simpa [Ideal.ofList, hset] using hP
  refine ⟨List.ofFn a, ?_, hP'⟩
  simp

end Elementary

end PrincipalClass

