import Question_bench.FATEH.«98_Localization»

open RingTheory

/-!
# Principal class prime ⇒ complete intersection (principal-class scaffolding)

This file contains the structured proof skeleton for the principal class theorem route.
It keeps only the genuinely deep commutative-algebra inputs as `sorry`.
-/

namespace PrincipalClass

section PrincipalClassSplit

variable {A : Type*} [CommRing A] [IsNoetherianRing A]
variable (P : Ideal A) [P.IsPrime]

local notation "Aₚ" => Localization.AtPrime P
local notation "ι" => (algebraMap A Aₚ)
local notation "Pₚ" => (Ideal.map ι P : Ideal Aₚ)

/--
Step D（深输入）：局部环版本的 principal class theorem。

在 Noetherian 局部环 `R` 中，如果极大理想 `m` 的高度是 `r`，
且 `m` 可由 `r` 个元素生成，则 `m` 可由一个 regular sequence 生成。
-/
theorem principalClass_local_maximal
    {R : Type*} [CommRing R] [IsNoetherianRing R] [IsLocalRing R]
    (r : ℕ) (hr : 0 < r)
    (b : List R) (hb_len : b.length = r)
    (h : r = (IsLocalRing.maximalIdeal R).primeHeight)
    (hb : (IsLocalRing.maximalIdeal R) = Ideal.ofList b) :
    ∃ b' : List R, Sequence.IsRegular R b' ∧ (IsLocalRing.maximalIdeal R) = Ideal.ofList b' := by
  sorry

/--
Step E：把 Step D 应用于 `Aₚ = Localization.AtPrime P`。

输入：`P = ofList b` 且 `b.length = r`。
输出：在 `Aₚ` 里存在 regular sequence 生成 `Pₚ`。
-/
theorem principalClass_exists_regularSequence_atPrime
    (r : ℕ) (hr : 0 < r) (h : r = P.primeHeight)
    (b : List A) (hb_len : b.length = r) (hbP : P = Ideal.ofList b) :
    ∃ bp : List Aₚ, Sequence.IsRegular Aₚ bp ∧ Pₚ = Ideal.ofList bp := by
  classical
  haveI : (Pₚ : Ideal Aₚ).IsPrime := map_isPrime_atPrime (A := A) (P := P)
  have hbPp : Pₚ = Ideal.ofList (b.map ι) :=
    map_ofList_eq_ofList_map (A := A) (P := P) b hbP

  have hb_len' : (b.map ι).length = r := by
    simp [List.length_map, hb_len]

  have hheight' : r = (IsLocalRing.maximalIdeal Aₚ).primeHeight := by
    have hPp_max : (Pₚ : Ideal Aₚ) = IsLocalRing.maximalIdeal Aₚ :=
      map_eq_maximalIdeal_atPrime (A := A) (P := P)
    have h' : r = (Pₚ : Ideal Aₚ).primeHeight := by
      exact h.trans (by simpa using (primeHeight_map_atPrime (A := A) (P := P)).symm)
    simpa [hPp_max] using h'

  have hb_max : (IsLocalRing.maximalIdeal Aₚ) = Ideal.ofList (b.map ι) := by
    have hPp_max : Pₚ = IsLocalRing.maximalIdeal Aₚ :=
      map_eq_maximalIdeal_atPrime (A := A) (P := P)
    simpa [hPp_max] using hbPp

  rcases principalClass_local_maximal (R := Aₚ) (r := r) hr (b := b.map ι) hb_len' hheight' hb_max with
    ⟨bp, hbp_reg, hbp_eq⟩
  refine ⟨bp, hbp_reg, ?_⟩
  have hPp_max : Pₚ = IsLocalRing.maximalIdeal Aₚ :=
    map_eq_maximalIdeal_atPrime (A := A) (P := P)
  simpa [hPp_max] using hbp_eq

/--
Step F（深输入）：把 `Aₚ` 中的 regular sequence 生成 `Pₚ` 的结论下降回 `A`。

This bundles:
* clearing denominators / replacing localized elements by elements of `A`;
* local-to-global regularity criteria (in this benchmark, usually only at `P`).
-/
theorem principalClass_descend_from_atPrime
    (bp : List Aₚ) (hbp_reg : Sequence.IsRegular Aₚ bp) (hbp_gen : Pₚ = Ideal.ofList bp) :
    ∃ b' : List A, Sequence.IsRegular A b' ∧ P = Ideal.ofList b' := by
  sorry

/--
Assemble Steps D–F: if `P = Ideal.ofList b` with `b.length = r` and `r = primeHeight(P)`,
then `P` can be generated by a regular sequence.
-/
theorem principalClass_exists_regularSequence_ofList
    (r : ℕ) (hr : 0 < r) (h : r = P.primeHeight)
    (b : List A) (hb_len : b.length = r) (hbP : P = Ideal.ofList b) :
    ∃ b' : List A, Sequence.IsRegular A b' ∧ P = Ideal.ofList b' := by
  classical
  rcases principalClass_exists_regularSequence_atPrime (A := A) (P := P)
      (r := r) hr h (b := b) hb_len hbP with
    ⟨bp, hbp_reg, hbp_gen⟩
  exact principalClass_descend_from_atPrime (A := A) (P := P) bp hbp_reg hbp_gen

end PrincipalClassSplit

end PrincipalClass
